# Generated by Django 5.1.7 on 2025-08-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='transaction_files/'),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
