# Generated by Django 5.1.7 on 2026-07-21 06:33

import django.db.models.deletion
from models.transactional.company_collaboration.utils import upload_document_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0008_auto_20260709_1852'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCollaboration',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_license_fee_paid', models.BooleanField(default=False)),
                ('is_security_fee_paid', models.BooleanField(default=False)),
                ('is_renewal', models.BooleanField(default=False)),
                ('financial_year', models.CharField(blank=True, max_length=10)),
                ('application_year', models.CharField(default='2025-26', max_length=9)),
                ('brand_owner', models.CharField(max_length=120)),
                ('brand_owner_code', models.CharField(blank=True, max_length=120, null=True)),
                ('brand_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_owner_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_owner_office_address', models.TextField(blank=True, null=True)),
                ('brand_owner_factory_address', models.TextField(blank=True, null=True)),
                ('brand_owner_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('brand_owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('licensee_name', models.CharField(max_length=255)),
                ('licensee_address', models.TextField()),
                ('license_number', models.CharField(max_length=100)),
                ('selected_brand_ids', models.JSONField(blank=True, default=list)),
                ('selected_brands', models.JSONField(blank=True, default=list)),
                ('fee_structure', models.JSONField(blank=True, default=dict)),
                ('overview_summary', models.JSONField(blank=True, default=dict)),
                ('undertaking', models.FileField(max_length=255, upload_to=upload_document_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_collaborations', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_collaborations', to='workflow.workflowstage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_collaborations', to='workflow.workflow')),
            ],
            options={
                'db_table': 'company_collaboration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['financial_year'], name='comp_collab_year_idx'), models.Index(fields=['application_year'], name='comp_collab_app_year_idx'), models.Index(fields=['licensee_name'], name='comp_collab_licensee_idx'), models.Index(fields=['current_stage'], name='comp_collab_stage_idx'), models.Index(fields=['applicant'], name='comp_collab_applicant_idx')],
            },
        ),
    ]
