# Generated by Django 5.1.7 on 2026-04-06 08:24

from models.transactional.company_collaboration.models import upload_document_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCollaboration',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('financial_year', models.CharField(default='2025-2026', max_length=9)),
                ('application_year', models.CharField(default='2025-2026', max_length=9)),
                ('brand_owner', models.CharField(max_length=120)),
                ('brand_owner_code', models.CharField(blank=True, max_length=120, null=True)),
                ('brand_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_owner_address', models.TextField(blank=True, null=True)),
                ('brand_owner_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_owner_office_address', models.TextField(blank=True, null=True)),
                ('brand_owner_factory_address', models.TextField(blank=True, null=True)),
                ('brand_owner_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('brand_owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('licensee_name', models.CharField(max_length=255)),
                ('licensee_address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(max_length=100)),
                ('license_type', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_brand_ids', models.JSONField(blank=True, default=list)),
                ('selected_brands', models.JSONField(blank=True, default=list)),
                ('fee_structure', models.JSONField(blank=True, default=dict)),
                ('overview_summary', models.JSONField(blank=True, default=dict)),
                ('undertaking', models.FileField(upload_to=upload_document_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_collaboration',
                'ordering': ['-created_at'],
            },
        ),
    ]
