# Generated by Django 5.1.7 on 2026-07-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_collaboration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycollaboration',
            name='is_security_fee_paid',
        ),
    ]
