# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_collaboration', '0002_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycollaboration',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_collaborations', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='companycollaboration',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_collaborations', to='workflow.workflow'),
        ),
        migrations.AddIndex(
            model_name='companycollaboration',
            index=models.Index(fields=['licensee_name'], name='comp_collab_licensee_idx'),
        ),
        migrations.AddIndex(
            model_name='companycollaboration',
            index=models.Index(fields=['contact_number'], name='comp_collab_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='companycollaboration',
            index=models.Index(fields=['application_year'], name='comp_collab_year_idx'),
        ),
        migrations.AddIndex(
            model_name='companycollaboration',
            index=models.Index(fields=['current_stage'], name='comp_collab_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='companycollaboration',
            index=models.Index(fields=['applicant'], name='comp_collab_applicant_idx'),
        ),
    ]
