# Generated by Django 5.1.7 on 2026-04-15 09:50

from models.transactional.company_collaboration.utils import upload_document_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_collaboration', '0003_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companycollaboration',
            name='comp_collab_contact_idx',
        ),
        migrations.RenameIndex(
            model_name='companycollaboration',
            new_name='comp_collab_app_year_idx',
            old_name='comp_collab_year_idx',
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='brand_owner_address',
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='business_reg_number',
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='establishment_type',
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='license_type',
        ),
        migrations.AlterField(
            model_name='companycollaboration',
            name='application_year',
            field=models.CharField(default='2025-26', max_length=9),
        ),
        migrations.AlterField(
            model_name='companycollaboration',
            name='financial_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='companycollaboration',
            name='undertaking',
            field=models.FileField(max_length=255, upload_to=upload_document_path),
        ),
        migrations.AddIndex(
            model_name='companycollaboration',
            index=models.Index(fields=['financial_year'], name='comp_collab_year_idx'),
        ),
    ]
