# Generated by Django 5.1.7 on 2026-07-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_collaboration', '0004_remove_companycollaboration_comp_collab_contact_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycollaboration',
            name='is_license_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companycollaboration',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companycollaboration',
            name='is_security_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
