# Generated by Django 5.2.8 on 2026-07-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_collaboration', '0005_companycollaboration_is_license_fee_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycollaboration',
            name='is_security_fee_paid',
        ),
    ]
