# Generated by Django 5.1.7 on 2025-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(max_length=50, unique=True)),
                ('status_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Master',
                'verbose_name_plural': 'Status Masters',
                'db_table': 'status_master',
                'managed': False,
            },
        ),
    ]
