# Generated by Django 5.1.7 on 2025-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_master', '0002_workflowrule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workflowrule',
            name='allowed_role',
            field=models.CharField(default='permit-section', help_text='Role allowed to perform this action (e.g., permit-section, commissioner)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workflowrule',
            unique_together={('current_status', 'action', 'allowed_role')},
        ),
    ]
