# Generated by Django 5.1.7 on 2025-11-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'purpose',
                'ordering': ['purpose_name'],
            },
        ),
    ]
