# Generated by Django 5.1.7 on 2026-06-28 03:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveRaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subject', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'masters_preventiveraid',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveRaidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='preventive_raids/images/')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preventive_raids.preventiveraid')),
            ],
            options={
                'db_table': 'masters_preventiveraidimage',
            },
        ),
    ]
