# Generated by Django 5.1.7 on 2026-08-04 07:21

from models.masters.preventive_raids.models import upload_preventive_raid_image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_raids', '0002_seed_preventive_raids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventiveraidimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=upload_preventive_raid_image_path),
        ),
    ]
