errors = {
    "credentials_error": "API Key and Secret are required.",
    "encryption_key_error": "Encryption Key is required.",
    "environment_error": "SDK environment should be LIVE or SANDBOX",
    "logging_error": "logging should be boolean (true/false)",
    "payload_encrypt_error": "Payload is required for encryption",
    "payload_decrypt_error": "Payload is required for decryption",
    "decode_callback_error": "Payload is required for callback decoding",
}

exceptions = {
    "encryption_error_code": 621,
    "encryption_error_msg": "Encryption failed, Please check the encryption key and request.",
    "decryption_error_code": 622,
    "decryption_error_msg": "Decryption failed, Please check the encryption key!",
    "json_processing_error_code": 623,
    "io_exception_error_code": 601,
    "io_exception_error_msg": "InValid Response from Server.",
    "invalid_response_error_code": 602,
    "invalid_response_error_msg": "SBI EPay Business Validation Errors: {0}",
    "error_response_code": 603,
    "customer_payload_required": 2000,
    "customer_id_required": 2001,
    "customer_status_required": 2002,
    # "customer_create_error_code": 651,
    # "customer_fetch_error_code": 651,
    # "customer_update_error_code": 651,
    "customer_create_error_msg": "Issue in Customer Creation.",
    "customer_fetch_error_msg": "Issue in Customer Get.",
    "customer_update_error_msg": "Issue in Customer Update.",
    "order_payload_required": 2003,
    # "order_create_error_code": 652,
    # "order_search_error_code": 652,
    "order_create_error_msg": "Issue in Order Creation.",
    "order_search_error_msg": "Issue in Order Search.",
    "refund_payload_required": 2004,
    # "refund_initiate_error_code": 653,
    # "refund_search_error_code": 654,
    "refund_initiate_error_msg": "Issue in Transaction Refund Initiation.",
    "refund_search_error_msg": "Issue in getting Refund Search.",
    "transaction_status_error_code": 655,
    "exception_while_calling_access_token_api": "Exception while calling access token api.",
    "encryption_decryption_error_msg": "Encryption Decryption Service Failed.",
}

log_titles = {
    "sbi_epay_client_initialization_error": "SBIEpayClient initialization error.",
    "network_error": "Connection error: Network connection failed.",
    "request_error": "Request Error.",
    "timeout_error": "Timeout error: Request timed out.",
    "unexpected_error": "Unexpected Error.",
    "json_decode_error": "JSON decode error: Failed to parse response.",
    "access_token": "Get token.",
    "customer_create": "Customer create.",
    "customer_fetch": "Customer fetch.",
    "customer_update": "Customer update.",
    "order_create": "Order create.",
    "order_search": "Order search.",
    "refund_book": "Refund book.",
    "refund_search": "Refund search.",
    "payload_encrypt": "Payload encrypt.",
    "payload_decrypt": "Payload decrypt.",
    "decode_callback": "Decode callback.",
}

status = {
    "active": "ACTIVE",
    "inactive": "INACTIVE",
    "delete": "DELETE",
}