# Generated by Django 5.1.7 on 2026-04-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHeadOfAccount',
            fields=[
                ('head_of_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('visible_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'eabgari_master_head_of_accounts',
                'managed': False,
            },
        ),
    ]
