# Generated by Django 5.1.7 on 2026-04-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentheadofaccount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentheadofaccount',
            table='wallet_master_head_of_accounts',
        ),
    ]
