# Generated by Django 5.1.7 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnaRevalidationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_ref_no', models.CharField(max_length=50)),
                ('requisition_date', models.DateTimeField()),
                ('grain_ena_number', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bulk_spirit_type', models.CharField(blank=True, default='', max_length=255)),
                ('strength', models.CharField(blank=True, default='', max_length=255)),
                ('lifted_from', models.CharField(max_length=255)),
                ('via_route', models.CharField(max_length=255)),
                ('total_bl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('br_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('requisiton_number_of_permits', models.IntegerField()),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.CharField(max_length=500)),
                ('branch_purpose', models.CharField(max_length=255)),
                ('govt_officer', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('revalidation_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('revalidation_br_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('details_permits_number', models.CharField(blank=True, max_length=500, null=True)),
                ('licensee_id', models.CharField(max_length=50)),
                ('establishment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distillery_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ena_revalidation_detail',
                'ordering': ['-created_at'],
            },
        ),
    ]
