# Generated by Django 5.1.7 on 2025-12-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_revalidation_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enarevalidationdetail',
            name='strength_from',
        ),
        migrations.RemoveField(
            model_name='enarevalidationdetail',
            name='strength_to',
        ),
        migrations.AddField(
            model_name='enarevalidationdetail',
            name='bulk_spirit_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enarevalidationdetail',
            name='strength',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
