# Generated by Django 5.1.7 on 2025-12-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_revalidation_details', '0002_remove_enarevalidationdetail_strength_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enarevalidationdetail',
            name='status_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
