# Generated by Django 5.1.7 on 2025-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_revalidation_details', '0003_enarevalidationdetail_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enarevalidationdetail',
            name='status_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
