# Generated by Django 5.1.7 on 2025-08-02 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('license_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('establishment_name', models.CharField(max_length=255)),
                ('licensee_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_up_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issued_license', to='license_application.licenseapplication')),
                ('excise_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.district')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensetype')),
            ],
            options={
                'db_table': 'license',
                'indexes': [models.Index(fields=['excise_district'], name='license_excise__b99738_idx'), models.Index(fields=['license_type'], name='license_license_af1c07_idx'), models.Index(fields=['is_active'], name='license_is_acti_d88885_idx')],
            },
        ),
    ]
