WORKFLOW_IDS = {
    'LICENSE_APPROVAL': 1,
    'SALESMAN_BARMAN': 2,
    'COMPANY_REGISTRATION': 9,
    'ENA_REQUISITION': 3,
    'ENA_REVALIDATION': 4,
    'ENA_CANCELLATION': 5,
    'HOLOGRAM_PROCUREMENT': 6,
    'HOLOGRAM_REQUEST': 7,
    'TRANSIT_PERMIT': 8,
}
