# Generated by Django 5.1.7 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpost_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'checkpost',
                'ordering': ['checkpost_name'],
            },
        ),
    ]
