# Generated by Django 5.1.6 on 2025-03-20 07:53

import django.db.models.deletion
import registration_renewal.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_licensetype_state_district_subdivision_policestation'),
        ('registration_renewal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='license_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.licensetype'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[registration_renewal.helpers.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='name',
            field=models.CharField(max_length=100, validators=[registration_renewal.helpers.validate_name]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[registration_renewal.helpers.validate_pan_number]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='registered_office_address',
            field=models.CharField(max_length=255, validators=[registration_renewal.helpers.validate_address]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='state',
            field=models.CharField(choices=[('Sikkim', 'Sikkim')], default='Sikkim', max_length=50),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='email',
            field=models.EmailField(max_length=100, validators=[registration_renewal.helpers.validate_email]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='member_address',
            field=models.CharField(max_length=255, validators=[registration_renewal.helpers.validate_address]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='member_designation',
            field=models.CharField(max_length=100, validators=[registration_renewal.helpers.validate_address]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='member_name',
            field=models.CharField(max_length=100, validators=[registration_renewal.helpers.validate_name]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[registration_renewal.helpers.validate_mobile_number]),
        ),
    ]
