# Generated by Django 5.1.4 on 2025-06-28 16:00

import django.db.models.deletion
import masters.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_category', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('state_code', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('district_code', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('state_code', models.ForeignKey(db_column='state_code', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='masters.state', to_field='state_code')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('subdivision_code', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district_code', models.ForeignKey(db_column='district_code', on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='masters.district', to_field='district_code')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('police_station_code', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subdivision_code', models.ForeignKey(db_column='subdivision_code', on_delete=django.db.models.deletion.CASCADE, related_name='policestations', to='masters.subdivision', to_field='subdivision_code')),
            ],
        ),
    ]
