# Generated by Django 5.1.7 on 2025-06-19 10:27

import django.db.models.deletion
import masters.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseCategoryDescription', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseType', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('StateCode', models.IntegerField(unique=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('DistrictCode', models.IntegerField(unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('StateCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='masters.state', to_field='StateCode')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubDivisionName', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('SubDivisionCode', models.IntegerField(unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('DistrictCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='masters.district', to_field='DistrictCode')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoliceStationName', models.CharField(max_length=30, validators=[masters.validators.validate_name])),
                ('PoliceStationCode', models.IntegerField(unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('SubDivisionCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policestations', to='masters.subdivision', to_field='SubDivisionCode')),
            ],
        ),
    ]
