# Generated by Django 5.1.6 on 2025-02-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseCategoryDescription', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
