# Generated by Django 5.1.7 on 2025-07-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='masters.state', to_field='state_code'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='subdivision_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policestations', to='masters.subdivision', to_field='subdivision_code'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='district_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='masters.district', to_field='district_code'),
        ),
    ]
