# Generated by Django 5.1.7 on 2025-07-10 05:08

import django.db.models.deletion
import masters.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_district_state_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200, validators=[masters.validators.validate_name_extended])),
                ('category', models.ForeignKey(db_column='license_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='masters.licensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=100, validators=[masters.validators.validate_name_extended])),
                ('road_type', models.CharField(choices=[('NH', 'National Highway'), ('SH', 'State Highway'), ('LINK ROAD', 'Link Road')], default='NH', max_length=10)),
                ('district_id', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='masters.district', to_field='district_code')),
            ],
        ),
    ]
