# Generated by Django 5.2.8 on 2026-08-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0003_seed_imfl_workflows'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='distributorpermitlineitem',
            new_name='distributor_applica_266aad_idx',
            old_name='imfl_brands_applica_ca5571_idx',
        ),
        migrations.RenameIndex(
            model_name='distributorpermitlineitem',
            new_name='distributor_brand_i_d3fd55_idx',
            old_name='imfl_brands_brand_i_eca62b_idx',
        ),
        migrations.AlterModelTable(
            name='distributorpermitlineitem',
            table='distributor_permit_line_item',
        ),
    ]
