# Generated by Django 5.2.8 on 2026-08-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0004_rename_imfl_brands_applica_ca5571_idx_distributor_applica_266aad_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='distributorpermitlineitem',
            new_name='imfl_brands_applica_ca5571_idx',
            old_name='distributor_applica_266aad_idx',
        ),
        migrations.RenameIndex(
            model_name='distributorpermitlineitem',
            new_name='imfl_brands_brand_i_eca62b_idx',
            old_name='distributor_brand_i_d3fd55_idx',
        ),
        migrations.AlterModelTable(
            name='distributorpermitlineitem',
            table='imfl_brands',
        ),
    ]
