# Generated by Django 5.2.8 on 2026-08-20 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0005_rename_distributor_applica_266aad_idx_imfl_brands_applica_ca5571_idx_and_more'),
        ('workflow', '0008_auto_20260709_1852'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='distributorpermitlineitem',
            new_name='distributor_applica_266aad_idx',
            old_name='imfl_brands_applica_ca5571_idx',
        ),
        migrations.RenameIndex(
            model_name='distributorpermitlineitem',
            new_name='distributor_brand_i_d3fd55_idx',
            old_name='imfl_brands_brand_i_eca62b_idx',
        ),
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributor_permit_applications', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributor_permit_applications', to='workflow.workflow'),
        ),
        migrations.AlterModelTable(
            name='distributorpermitlineitem',
            table='distributor_permit_line_item',
        ),
    ]
