# Generated by Django 5.2.8 on 2026-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0006_rename_imfl_brands_applica_ca5571_idx_distributor_applica_266aad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='is_excise_duty_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
