# Generated by Django 5.2.8 on 2026-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0007_add_is_excise_duty_fee_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorpermitapplication',
            name='status',
            field=models.CharField(default='Submitted', max_length=100),
        ),
    ]
