# Generated by Django 5.2.8 on 2026-08-20 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_imfl_revalidation_timer(apps, schema_editor):
    try:
        SupplyChainTimerConfig = apps.get_model('core', 'SupplyChainTimerConfig')
        SupplyChainTimerConfig.objects.update_or_create(
            code='IMFL_REVALIDATION_ACTIVATION',
            defaults={
                'description': 'Delay after requisition approval before IMFL revalidation is auto-created.',
                'delay_value': 10,
                'delay_unit': 'minute',
                'is_active': True,
                'validity_period_days': 45,
            }
        )
    except Exception as e:
        print(f"Warning: Could not seed IMFL_REVALIDATION_ACTIVATION timer: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0008_alter_status_max_length'),
        ('workflow', '0008_auto_20260709_1852'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='valid_up_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IMFLCancellation',
            fields=[
                ('reference_no', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Submitted', max_length=100)),
                ('officer_remarks', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imfl_cancellations', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imfl_cancellations', to='workflow.workflowstage')),
                ('distributor_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='distributor_permit.distributorpermitapplication')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imfl_cancellations', to='workflow.workflow')),
            ],
            options={
                'db_table': 'imfl_cancellation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IMFLRevalidation',
            fields=[
                ('reference_no', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('revalidation_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Submitted', max_length=100)),
                ('officer_remarks', models.TextField(blank=True, default='')),
                ('valid_up_to', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imfl_revalidations', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imfl_revalidations', to='workflow.workflowstage')),
                ('distributor_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revalidations', to='distributor_permit.distributorpermitapplication')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imfl_revalidations', to='workflow.workflow')),
            ],
            options={
                'db_table': 'imfl_revalidation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IMFLRevalidationActivationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_permit_ref_no', models.CharField(db_index=True, max_length=50)),
                ('approval_date', models.DateTimeField()),
                ('activation_due_at', models.DateTimeField(db_index=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor_permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revalidation_activation_schedule', to='distributor_permit.distributorpermitapplication')),
            ],
            options={
                'db_table': 'imfl_revalidation_activation_schedule',
                'ordering': ['activation_due_at', '-updated_at'],
            },
        ),
        migrations.RunPython(seed_imfl_revalidation_timer, reverse_code=migrations.RunPython.noop),
    ]
