# Generated by Django 5.2.8 on 2026-08-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0009_distributorpermitapplication_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='permit_wise_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='distributorpermitlineitem',
            name='permit_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
