# Generated by Django 5.2.8 on 2026-08-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0010_distributorpermitapplication_permit_wise_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributorpermitlineitem',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='distributorpermitlineitem',
            name='total_education_cess',
        ),
        migrations.RemoveField(
            model_name='distributorpermitlineitem',
            name='total_import',
        ),
    ]
