# Generated by Django 5.2.8 on 2026-08-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0011_remove_distributorpermitlineitem_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imflcancellation',
            name='cancelled_permit_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imflcancellation',
            name='permit_wise_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
