# Generated by Django 5.2.8 on 2026-08-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0012_imflcancellation_cancelled_permit_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imflrevalidation',
            name='permit_wise_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='imflrevalidation',
            name='revalidated_permit_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
