# Generated by Django 5.2.8 on 2026-08-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0013_imflrevalidation_permit_wise_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imflrevalidationactivationschedule',
            name='distributor_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revalidation_activation_schedules', to='distributor_permit.distributorpermitapplication'),
        ),
    ]
