# Generated by Django 5.2.8 on 2026-08-22 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0014_alter_imflrevalidationactivationschedule_distributor_permit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMFLArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(db_index=True, max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=255)),
                ('size_ml', models.IntegerField(default=750)),
                ('expected_cases', models.IntegerField(default=0)),
                ('arrived_cases', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imfl_arrivals', to=settings.AUTH_USER_MODEL)),
                ('distributor_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='distributor_permit.distributorpermitapplication')),
            ],
            options={
                'db_table': 'imfl_arrival',
                'ordering': ['-arrived_at', '-id'],
            },
        ),
    ]
