# Generated by Django 5.2.8 on 2026-08-22 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0015_imflarrival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMFLCasesProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(db_index=True, max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=255)),
                ('size_ml', models.IntegerField(default=750)),
                ('expected_cases', models.IntegerField(default=0)),
                ('arrived_cases', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='under_review', max_length=50)),
                ('officer_remarks', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_arrivals', to='distributor_permit.distributorpermitapplication')),
                ('oic_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_imfl_cases_processed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_imfl_cases_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imfl_cases_processed',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
