# Generated by Django 5.2.8 on 2026-08-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0016_imflcasesprocessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributorpermitlineitem',
            name='bulk_litres',
        ),
        migrations.RemoveField(
            model_name='distributorpermitlineitem',
            name='education_cess_per_case',
        ),
    ]
