# Generated by Django 5.2.8 on 2026-08-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0017_remove_distributorpermitlineitem_bulk_litres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributorpermitlineitem',
            name='total_additional_ed',
        ),
    ]
