# Generated by Django 5.2.8 on 2026-08-26 04:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0018_rename_distributor_applica_266aad_idx_imfl_brands_applica_ca5571_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpermitlineitem',
            name='education_cess_per_case',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
