# Generated by Django 5.2.8 on 2026-08-26 05:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0019_rename_distributor_applica_266aad_idx_imfl_brands_applica_ca5571_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMFLSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('route_details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'imfl_suppliers',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='IMFLBrand',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='imfl_supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='distributor_permit.imflsupplier'),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE public.imfl_brands ADD COLUMN IF NOT EXISTS imfl_supplier_id bigint REFERENCES public.imfl_suppliers(id) ON DELETE CASCADE;
            """,
            reverse_sql=""
        ),
    ]
