# Generated by Django 5.2.8 on 2026-08-29 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0020_imflsupplier_imflbrand'),
        ('liquor_data', '0003_alter_masterliquorcapacity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='imflsupplier',
                    name='supplier_master_name',
                    field=models.CharField(blank=True, default='', max_length=255),
                ),
            ],
            database_operations=[]
        ),
        migrations.AlterField(
            model_name='distributorpermitlineitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_permit_line_items', to='liquor_data.masterbrandlist'),
        ),
        migrations.CreateModel(
            name='IMFLBrandWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('brand_type', models.CharField(blank=True, default='WHISKY', max_length=100)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('distributor_establishment', models.CharField(blank=True, default='', max_length=255)),
                ('pack_size', models.IntegerField(default=750)),
                ('pieces_per_case', models.IntegerField(default=12)),
                ('expected_cases', models.IntegerField(default=0)),
                ('expected_bottles', models.IntegerField(default=0)),
                ('arrived_cases', models.IntegerField(default=0)),
                ('arrived_bottles', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('total_utilized', models.IntegerField(default=0)),
                ('total_capacity', models.IntegerField(default=0)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=100)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='IN_STOCK', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_warehouse_records', to='distributor_permit.distributorpermitapplication')),
                ('officer_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imfl_brand_warehouse_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imfl_brand_warehouse',
                'ordering': ['-arrival_date', '-id'],
                'indexes': [models.Index(fields=['brand_name', 'pack_size'], name='imfl_brand__brand_n_ddd649_idx'), models.Index(fields=['permit_number'], name='imfl_brand__permit__507ac3_idx'), models.Index(fields=['arrival_date'], name='imfl_brand__arrival_06ad55_idx')],
            },
        ),
    ]
