# Generated by Django 5.2.8 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0021_imflsupplier_supplier_master_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imflarrival',
            name='arrived_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='brand_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='damaged_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='damaged_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='expected_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='good_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='good_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='pieces_per_case',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='damaged_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='damaged_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='good_bottles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='good_cases',
            field=models.IntegerField(default=0),
        ),
    ]
