# Generated by Django 5.2.8 on 2026-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0022_imflarrival_arrived_bottles_imflarrival_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imflarrival',
            name='damaged_holograms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='hologram_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='hologram_from',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imflarrival',
            name='hologram_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='damaged_holograms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='hologram_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='hologram_from',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='hologram_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
