# Generated by Django 5.2.8 on 2026-08-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0023_imflarrival_damaged_holograms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imflarrival',
            name='damaged_cases_holograms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imflbrandwarehouse',
            name='damaged_cases_holograms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
