# Generated by Django 5.2.8 on 2026-08-30 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0024_imflarrival_damaged_cases_holograms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMFLRetailerStockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_reference_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('retailer_name', models.CharField(db_index=True, max_length=255)),
                ('retailer_license_no', models.CharField(blank=True, default='', max_length=100)),
                ('retailer_shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('retailer_address', models.TextField(blank=True, default='')),
                ('retailer_contact', models.CharField(blank=True, default='', max_length=50)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('brand_type', models.CharField(blank=True, default='WHISKY', max_length=100)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('pack_size', models.IntegerField(default=750)),
                ('pieces_per_case', models.IntegerField(default=12)),
                ('dispatched_cases', models.IntegerField(default=0)),
                ('dispatched_loose_bottles', models.IntegerField(default=0)),
                ('dispatched_bottles', models.IntegerField(default=0)),
                ('hologram_from', models.CharField(blank=True, default='', max_length=100)),
                ('hologram_to', models.CharField(blank=True, default='', max_length=100)),
                ('hologram_count', models.IntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=100)),
                ('driver_name', models.CharField(blank=True, default='', max_length=100)),
                ('driver_phone', models.CharField(blank=True, default='', max_length=50)),
                ('challan_no', models.CharField(blank=True, default='', max_length=100)),
                ('dispatch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='DISPATCHED', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imfl_retailer_dispatches', to=settings.AUTH_USER_MODEL)),
                ('officer_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imfl_retailer_dispatches_verified', to=settings.AUTH_USER_MODEL)),
                ('warehouse_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_dispatches', to='distributor_permit.imflbrandwarehouse')),
            ],
            options={
                'db_table': 'imfl_retailers_stock_details',
                'ordering': ['-dispatch_date', '-id'],
                'indexes': [models.Index(fields=['dispatch_reference_no'], name='imfl_retail_dispatc_3c8870_idx'), models.Index(fields=['brand_name', 'pack_size'], name='imfl_retail_brand_n_cd603d_idx'), models.Index(fields=['retailer_name'], name='imfl_retail_retaile_a48dc8_idx'), models.Index(fields=['dispatch_date'], name='imfl_retail_dispatc_1a3906_idx')],
            },
        ),
    ]
