# Generated by Django 5.2.8 on 2026-09-08 13:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0026_seed_imfl_forward_transitions'),
        ('workflow', '0009_objection_deadline_auto_reject_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMFLHologramProcurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('distributor_name', models.CharField(blank=True, default='', max_length=255)),
                ('license_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('establishment_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Number of holograms requested')),
                ('rate_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(default='PENDING', max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='Submitted', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imfl_hologram_procurements', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imfl_hologram_procurements', to='workflow.workflowstage')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imfl_hologram_procurements', to='workflow.workflow')),
            ],
            options={
                'db_table': 'imfl_hologram_procurement_details',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant'], name='imfl_hologr_applica_de0dbd_idx'), models.Index(fields=['ref_no'], name='imfl_hologr_ref_no_9d295b_idx'), models.Index(fields=['status'], name='imfl_hologr_status_d498dd_idx'), models.Index(fields=['created_at'], name='imfl_hologr_created_8050b4_idx')],
            },
        ),
    ]
