# Generated by Django 5.2.8 on 2026-09-08 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0028_seed_imfl_hologram_procurement_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMFLHologramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imfl_hologram_ref_no', models.CharField(db_index=True, help_text='Procurement reference number', max_length=100)),
                ('distributor_name', models.CharField(blank=True, default='', max_length=255)),
                ('license_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('establishment_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_holograms', models.PositiveIntegerField(default=0, help_text='Total holograms received')),
                ('hologram_from_range', models.CharField(help_text='Starting hologram serial/barcode range', max_length=100)),
                ('hologram_to_range', models.CharField(help_text='Ending hologram serial/barcode range', max_length=100)),
                ('hologram_ranges', models.JSONField(blank=True, default=list, help_text='Breakdown of usable hologram range segments')),
                ('damaged_total', models.PositiveIntegerField(default=0, help_text='Total damaged holograms')),
                ('damaged_holograms_range', models.JSONField(blank=True, default=list, help_text='Damaged hologram ranges')),
                ('recorded_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(db_index=True, default='RECEIVED', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_records', to='distributor_permit.imflhologramprocurement')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imfl_hologram_arrivals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imfl_hologram_details',
                'ordering': ['-arrival_date', '-created_at'],
                'indexes': [models.Index(fields=['imfl_hologram_ref_no'], name='imfl_hologr_imfl_ho_0de328_idx'), models.Index(fields=['license_number'], name='imfl_hologr_license_1d835b_idx'), models.Index(fields=['status'], name='imfl_hologr_status_3dc6ce_idx'), models.Index(fields=['arrival_date'], name='imfl_hologr_arrival_3e21ca_idx')],
            },
        ),
    ]
