# Generated by Django 5.2.8 on 2026-09-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0029_imflhologramdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imflhologramdetails',
            name='hologram_from_range',
            field=models.CharField(blank=True, default='', help_text='Starting hologram serial/barcode range', max_length=100),
        ),
        migrations.AlterField(
            model_name='imflhologramdetails',
            name='hologram_to_range',
            field=models.CharField(blank=True, default='', help_text='Ending hologram serial/barcode range', max_length=100),
        ),
        migrations.AlterField(
            model_name='imflhologramdetails',
            name='status',
            field=models.CharField(db_index=True, default='PENDING_SERIALS', max_length=50),
        ),
    ]
