# Generated by Django 5.2.8 on 2026-09-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0030_alter_imflhologramdetails_hologram_from_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='assigned_hologram_ranges',
            field=models.JSONField(blank=True, default=list, help_text='Allocated hologram ranges with batch ref, from, to, count'),
        ),
        migrations.AddField(
            model_name='distributorpermitapplication',
            name='total_holograms_assigned',
            field=models.PositiveIntegerField(default=0, help_text='Total holograms allocated for this permit application'),
        ),
    ]
