# Generated by Django 5.2.8 on 2026-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0031_distributorpermitapplication_assigned_hologram_ranges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imflhologramdetails',
            name='used_hologram_ranges',
            field=models.JSONField(blank=True, default=list, help_text='List of allocated/used hologram ranges for permits and requisitions'),
        ),
    ]
