# Generated by Django 5.1.7 on 2026-09-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_permit', '0035_seed_workflow14_stage_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='imflrevalidationactivationschedule',
            name='permit_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imflrevalidationactivationschedule',
            name='permit_wise_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
