# Generated by Django 5.1.7 on 2025-11-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransitPermitDistributorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('depo_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Transit Permit Distributor Data',
                'verbose_name_plural': 'Transit Permit Distributor Data',
                'db_table': 'transit_permit_distributor_data',
            },
        ),
    ]
