# Generated by Django 5.1.7 on 2026-05-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('license', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitPermitDistributorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('depo_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license', models.ForeignKey(blank=True, db_column='license_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transit_permit_distributor_data', to='license.license')),
            ],
            options={
                'verbose_name': 'Transit Permit Distributor Data',
                'verbose_name_plural': 'Transit Permit Distributor Data',
                'db_table': 'transit_permit_distributor_data',
            },
        ),
    ]
