# Generated by Django 5.1.7 on 2025-11-07 10:15

import django.db.models.deletion
from models.transactional.salesman_barman.helpers import validate_address, validate_pan_number, validate_aadhaar_number, validate_phone_number, validate_email
from models.transactional.salesman_barman.models import upload_document_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('license', '0002_initial'),
        ('roles', '0001_initial'),
        ('workflow', '0002_alter_workflowtransition_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanBarmanModel',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('is_print_fee_paid', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=10)),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('middleName', models.CharField(blank=True, db_column='middle_name', max_length=100, null=True)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('fatherHusbandName', models.CharField(db_column='father_husband_name', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('address', models.TextField(validators=[validate_address])),
                ('pan', models.CharField(max_length=10, validators=[validate_pan_number])),
                ('aadhaar', models.CharField(max_length=12, validators=[validate_aadhaar_number])),
                ('mobileNumber', models.CharField(db_column='mobile_number', max_length=10, validators=[validate_phone_number])),
                ('emailId', models.EmailField(blank=True, db_column='email_id', max_length=254, validators=[validate_email])),
                ('sikkimSubject', models.BooleanField(db_column='sikkim_subject', default=False)),
                ('passPhoto', models.ImageField(db_column='pass_photo', upload_to=upload_document_path)),
                ('aadhaarCard', models.FileField(db_column='aadhaar_card', upload_to=upload_document_path)),
                ('residentialCertificate', models.FileField(db_column='residential_certificate', upload_to=upload_document_path)),
                ('dateofBirthProof', models.FileField(db_column='dateof_birth_proof', upload_to=upload_document_path)),
                ('IsActive', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sb_apps', to='workflow.workflowstage')),
                ('excise_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.district')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='license.license')),
                ('license_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sb_apps', to='workflow.workflow')),
            ],
            options={
                'db_table': 'salesman_barman_application',
            },
        ),
        migrations.CreateModel(
            name='SalesmanBarmanObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=255)),
                ('remarks', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('raised_on', models.DateTimeField(auto_now_add=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='salesman_barman.salesmanbarmanmodel')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstage')),
            ],
            options={
                'db_table': 'salesman_barman_objection',
                'ordering': ['raised_on'],
            },
        ),
        migrations.CreateModel(
            name='SalesmanBarmanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='salesman_barman.salesmanbarmanmodel')),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.workflowstage')),
            ],
            options={
                'db_table': 'salesman_barman_transaction',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='salesmanbarmanmodel',
            index=models.Index(fields=['excise_district'], name='salesman_ba_excise__022328_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmanbarmanmodel',
            index=models.Index(fields=['license_category'], name='salesman_ba_license_3e2ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmanbarmanmodel',
            index=models.Index(fields=['current_stage'], name='salesman_ba_current_6dc7b0_idx'),
        ),
    ]
