# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from models.transactional.salesman_barman.helpers import validate_address, validate_aadhaar_number, validate_email, validate_pan_number, validate_phone_number
from models.transactional.salesman_barman.models import upload_document_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanBarmanModel',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('is_print_fee_paid', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=10)),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('middleName', models.CharField(blank=True, db_column='middle_name', max_length=100, null=True)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('fatherHusbandName', models.CharField(db_column='father_husband_name', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('address', models.TextField(validators=[validate_address])),
                ('pan', models.CharField(max_length=10, validators=[validate_pan_number])),
                ('aadhaar', models.CharField(max_length=12, validators=[validate_aadhaar_number])),
                ('mobileNumber', models.CharField(db_column='mobile_number', max_length=10, validators=[validate_phone_number])),
                ('emailId', models.EmailField(blank=True, db_column='email_id', max_length=254, validators=[validate_email])),
                ('sikkimSubject', models.BooleanField(db_column='sikkim_subject', default=False)),
                ('passPhoto', models.ImageField(db_column='pass_photo', upload_to=upload_document_path)),
                ('aadhaarCard', models.FileField(db_column='aadhaar_card', upload_to=upload_document_path)),
                ('residentialCertificate', models.FileField(db_column='residential_certificate', upload_to=upload_document_path)),
                ('dateofBirthProof', models.FileField(db_column='dateof_birth_proof', upload_to=upload_document_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salesman_barman_application',
            },
        ),
    ]
