# Generated by Django 5.1.7 on 2025-08-18 07:49

from models.transactional.salesman_barman.helpers import validate_address, validate_aadhaar_number, validate_email, validate_pan_number, validate_phone_number
from models.transactional.salesman_barman.models import upload_document_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanBarmanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=10)),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('middleName', models.CharField(blank=True, db_column='middle_name', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('fatherHusbandName', models.CharField(db_column='father_husband_name', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('address', models.TextField(validators=[validate_address])),
                ('pan', models.CharField(max_length=10, validators=[validate_pan_number])),
                ('aadhaar', models.CharField(max_length=12, validators=[validate_aadhaar_number])),
                ('mobileNumber', models.CharField(db_column='mobile_number', max_length=10, validators=[validate_phone_number])),
                ('emailId', models.EmailField(blank=True, db_column='email_id', max_length=254, validators=[validate_email])),
                ('sikkimSubject', models.BooleanField(db_column='sikkim_subject', default=False)),
                ('applicationYear', models.CharField(db_column='application_year', default='2025-2026', max_length=9)),
                ('applicationId', models.CharField(db_column='application_id', max_length=100, unique=True)),
                ('applicationDate', models.DateField(db_column='application_date')),
                ('district', models.CharField(max_length=100)),
                ('licenseCategory', models.CharField(db_column='license_category', max_length=100)),
                ('license', models.CharField(db_column='license', max_length=100)),
                ('passPhoto', models.ImageField(db_column='pass_photo', upload_to=upload_document_path)),
                ('aadhaarCard', models.FileField(db_column='aadhaar_card', upload_to=upload_document_path)),
                ('residentialCertificate', models.FileField(db_column='residential_certificate', upload_to=upload_document_path)),
                ('dateofBirthProof', models.FileField(db_column='dateof_birth_proof', upload_to=upload_document_path)),
                ('IsActive', models.BooleanField(db_column='is_active', default=True)),
            ],
            options={
                'verbose_name': 'Salesman/Barman Registration',
                'verbose_name_plural': 'Salesmen/Barmen Registrations',
                'db_table': 'salesman_barman_details',
            },
        ),
    ]
