# Generated by Django 5.1.7 on 2025-11-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0001_initial'),
        ('workflow', '0003_workflowobjection_workflowtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanbarmantransaction',
            name='application',
        ),
        migrations.RemoveField(
            model_name='salesmanbarmantransaction',
            name='forwarded_by',
        ),
        migrations.RemoveField(
            model_name='salesmanbarmantransaction',
            name='forwarded_to',
        ),
        migrations.RemoveField(
            model_name='salesmanbarmantransaction',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='salesmanbarmantransaction',
            name='stage',
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_applications', to='workflow.workflowstage'),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_applications', to='workflow.workflow'),
        ),
        migrations.DeleteModel(
            name='SalesmanBarmanObjection',
        ),
        migrations.DeleteModel(
            name='SalesmanBarmanTransaction',
        ),
    ]
