# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('license', '0002_initial'),
        ('salesman_barman', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanbarmanmodel',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_applications', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='salesmanbarmanmodel',
            name='excise_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.district'),
        ),
        migrations.AddField(
            model_name='salesmanbarmanmodel',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='license.license'),
        ),
        migrations.AddField(
            model_name='salesmanbarmanmodel',
            name='license_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory'),
        ),
        migrations.AddField(
            model_name='salesmanbarmanmodel',
            name='renewal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_renewal', to='license.license'),
        ),
        migrations.AddField(
            model_name='salesmanbarmanmodel',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_applications', to='workflow.workflow'),
        ),
        migrations.AddIndex(
            model_name='salesmanbarmanmodel',
            index=models.Index(fields=['excise_district'], name='salesman_ba_excise__022328_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmanbarmanmodel',
            index=models.Index(fields=['license_category'], name='salesman_ba_license_3e2ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmanbarmanmodel',
            index=models.Index(fields=['current_stage'], name='salesman_ba_current_6dc7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmanbarmanmodel',
            index=models.Index(fields=['applicant'], name='salesman_ba_applica_e7b1e3_idx'),
        ),
    ]
