# Generated by Django 5.1.7 on 2026-05-05 04:19

import django.db.models.deletion
from models.transactional.salesman_barman.helpers import validate_address, validate_aadhaar_number, validate_email, validate_pan_number, validate_phone_number
from models.transactional.salesman_barman.models import upload_document_path, upload_document_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_initial'),
        ('new_license_application', '0005_newlicenseapplication_coi_rc_ss_and_more'),
        ('salesman_barman', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanbarmanmodel',
            name='new_license_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_details', to='new_license_application.newlicenseapplication'),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[validate_aadhaar_number]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='aadhaarCard',
            field=models.FileField(blank=True, db_column='aadhaar_card', null=True, upload_to=upload_document_path),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='address',
            field=models.TextField(blank=True, null=True, validators=[validate_address]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='dateofBirthProof',
            field=models.FileField(blank=True, db_column='dateof_birth_proof', null=True, upload_to=upload_document_path),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='emailId',
            field=models.EmailField(blank=True, db_column='email_id', max_length=254, null=True, validators=[validate_email]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='fatherHusbandName',
            field=models.CharField(blank=True, db_column='father_husband_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='firstName',
            field=models.CharField(blank=True, db_column='first_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='lastName',
            field=models.CharField(blank=True, db_column='last_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='license.license'),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='mobileNumber',
            field=models.CharField(blank=True, db_column='mobile_number', max_length=10, null=True, validators=[validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[validate_pan_number]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='passPhoto',
            field=models.ImageField(blank=True, db_column='pass_photo', null=True, upload_to=upload_document_path),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='residentialCertificate',
            field=models.FileField(blank=True, db_column='residential_certificate', null=True, upload_to=upload_document_path),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='sikkimSubject',
            field=models.BooleanField(blank=True, db_column='sikkim_subject', default=False, null=True),
        ),
        migrations.CreateModel(
            name='SalesmanBarmanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=10, null=True)),
                ('firstName', models.CharField(blank=True, db_column='first_name', max_length=100, null=True)),
                ('middleName', models.CharField(blank=True, db_column='middle_name', max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, db_column='last_name', max_length=100, null=True)),
                ('fatherHusbandName', models.CharField(blank=True, db_column='father_husband_name', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('mobileNumber', models.CharField(blank=True, db_column='mobile_number', max_length=10, null=True)),
                ('emailId', models.EmailField(blank=True, db_column='email_id', max_length=254, null=True)),
                ('sikkimSubject', models.BooleanField(blank=True, db_column='sikkim_subject', default=False, null=True)),
                ('passPhoto', models.ImageField(blank=True, db_column='pass_photo', null=True, upload_to=upload_document_path)),
                ('aadhaarCard', models.FileField(blank=True, db_column='aadhaar_card', null=True, upload_to=upload_document_path)),
                ('residentialCertificate', models.FileField(blank=True, db_column='residential_certificate', null=True, upload_to=upload_document_path)),
                ('dateofBirthProof', models.FileField(blank=True, db_column='dateof_birth_proof', null=True, upload_to=upload_document_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesman_barman_requests', to=settings.AUTH_USER_MODEL)),
                ('new_license_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salesman_barman_request', to='new_license_application.newlicenseapplication')),
            ],
            options={
                'db_table': 'salesman_barman_request',
                'indexes': [models.Index(fields=['new_license_application'], name='salesman_ba_new_lic_2fe5db_idx'), models.Index(fields=['applicant'], name='salesman_ba_applica_c17b88_idx')],
            },
        ),
    ]
