# Generated by Django 5.1.7 on 2025-12-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0002_remove_salesmanbarmantransaction_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanbarmanmodel',
            name='IsActive',
        ),
    ]
