# Generated by Django 5.1.7 on 2026-05-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0003_salesmanbarmanmodel_new_license_application_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesmanBarmanRequest',
        ),
    ]
