# Generated by Django 5.1.7 on 2026-10-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0004_delete_salesmanbarmanrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesmanbarmanmodel',
            options={'ordering': ['-created_at', '-application_id']},
        ),
    ]
