# Generated by Django 5.1.4 on 2025-07-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='is_license_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
