# Generated by Django 5.1.7 on 2025-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
