# Generated by Django 5.1.7 on 2026-04-24 05:45

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHeadOfAccount',
            fields=[
                ('head_of_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('visible_status', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'eabgari_master_head_of_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('wallet_balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('licensee_id', models.CharField(max_length=50)),
                ('licensee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('manufacturing_unit', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('module_type', models.CharField(max_length=20)),
                ('wallet_type', models.CharField(max_length=30)),
                ('head_of_account', models.CharField(max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wallet_balances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('wallet_transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'wallet_balance',
                    models.ForeignKey(
                        db_column='wallet_balance_id',
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='wallet.walletbalance',
                        to_field='wallet_balance_id',
                    ),
                ),
                ('transaction_id', models.CharField(max_length=100)),
                ('licensee_id', models.CharField(max_length=50)),
                ('licensee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('module_type', models.CharField(max_length=20)),
                ('wallet_type', models.CharField(max_length=30)),
                ('head_of_account', models.CharField(max_length=50)),
                ('entry_type', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('source_module', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'managed': False,
            },
        ),
    ]
