# Generated by Codex on 2026-04-24

from django.db import migrations, models


def _create_wallet_tables(apps, schema_editor):
    connection = schema_editor.connection
    existing = set(connection.introspection.table_names())

    WalletBalance = apps.get_model("wallet", "WalletBalance")
    WalletTransaction = apps.get_model("wallet", "WalletTransaction")

    if WalletBalance._meta.db_table not in existing:
        schema_editor.create_model(WalletBalance)
        existing.add(WalletBalance._meta.db_table)

    if WalletTransaction._meta.db_table not in existing:
        schema_editor.create_model(WalletTransaction)


def _drop_wallet_tables(apps, schema_editor):
    connection = schema_editor.connection
    existing = set(connection.introspection.table_names())

    WalletBalance = apps.get_model("wallet", "WalletBalance")
    WalletTransaction = apps.get_model("wallet", "WalletTransaction")

    if WalletTransaction._meta.db_table in existing:
        schema_editor.delete_model(WalletTransaction)
        existing.remove(WalletTransaction._meta.db_table)

    if WalletBalance._meta.db_table in existing:
        schema_editor.delete_model(WalletBalance)


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="walletbalance",
            options={"db_table": "wallet_balances"},
        ),
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={"db_table": "wallet_transactions"},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="wallettransaction",
                    name="wallet_balance",
                    field=models.ForeignKey(
                        db_column="wallet_balance_id",
                        on_delete=models.RESTRICT,
                        to="wallet.walletbalance",
                        to_field="wallet_balance_id",
                    ),
                )
            ],
            database_operations=[],
        ),
        migrations.RunPython(_create_wallet_tables, reverse_code=_drop_wallet_tables),
    ]

