# Generated by Django 5.1.7 on 2026-04-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_create_wallet_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet_balance",
            field=models.ForeignKey(
                db_column="wallet_balance_id",
                on_delete=django.db.models.deletion.RESTRICT,
                to="wallet.walletbalance",
            ),
        ),
    ]

