# Generated by Django 5.1.7 on 2026-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWalletType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sems_master_wallet_type',
            },
        ),
    ]
