# Generated by Django 5.1.7 on 2026-05-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_masterwallettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbalance',
            name='wallet_type',
            field=models.ForeignKey(db_column='wallet_type', on_delete=django.db.models.deletion.RESTRICT, to='wallet.masterwallettype'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet_type',
            field=models.ForeignKey(db_column='wallet_type', on_delete=django.db.models.deletion.RESTRICT, to='wallet.masterwallettype'),
        ),
    ]
