# Generated by Django 5.1.7 on 2026-06-17

from django.db import migrations
from datetime import timedelta

def link_legacy_utrs(apps, schema_editor):
    WalletTransaction = apps.get_model('wallet', 'WalletTransaction')
    PaymentBilldeskTransaction = apps.get_model('payment_gateway', 'PaymentBilldeskTransaction')
    
    # Get all wallet debit transactions with 24-character hexadecimal transaction IDs
    w_txs = WalletTransaction.objects.filter(entry_type='DR')
    for tx in w_txs:
        tx_id = tx.transaction_id
        if tx_id and len(tx_id) == 24 and all(c in '0123456789ABCDEFabcdef' for c in tx_id):
            candidates = [c for c in [str(tx.user_id).strip(), str(tx.licensee_id).strip()] if c]
            if not candidates:
                continue
            
            time_margin = timedelta(hours=2)
            bd_match = PaymentBilldeskTransaction.objects.filter(
                payer_id__in=candidates,
                payment_status='S',
                transaction_amount=tx.amount,
                transaction_date__gte=tx.created_at - time_margin,
                transaction_date__lte=tx.created_at + time_margin
            ).order_by('-transaction_date').first()
            
            if bd_match:
                tx.transaction_id = bd_match.utr
                tx.save(update_fields=['transaction_id'])

def reverse_link_legacy_utrs(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_walletbalance_wallet_type_and_more'),
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(link_legacy_utrs, reverse_link_legacy_utrs),
    ]
