# Generated by Django 5.2.8 on 2026-09-25 13:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_add_bottling_fee_wallet_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDepositRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applicant_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('application_id', models.CharField(db_index=True, max_length=100)),
                ('reference_no', models.CharField(blank=True, max_length=150, null=True)),
                ('license_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('establishment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('REFUNDED', 'REFUNDED'), ('PARTIALLY_REFUNDED', 'PARTIALLY_REFUNDED'), ('ADJUSTED', 'ADJUSTED')], db_index=True, default='PAID', max_length=50)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_deposit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Deposit Record',
                'verbose_name_plural': 'Security Deposit Records',
                'db_table': 'security_deposit_record',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['application_id'], name='security_de_applica_3923cb_idx'), models.Index(fields=['username'], name='security_de_usernam_9e7a29_idx'), models.Index(fields=['license_id'], name='security_de_license_54f385_idx'), models.Index(fields=['status'], name='security_de_status_1a9571_idx'), models.Index(fields=['transaction_id'], name='security_de_transac_60f332_idx')],
            },
        ),
    ]
