# Generated by Django 5.2.8 on 2026-09-25 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_securitydepositrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydepositrecord',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitydepositrecord',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='securitydepositrecord',
            index=models.Index(fields=['from_date'], name='security_de_from_da_c7e82c_idx'),
        ),
        migrations.AddIndex(
            model_name='securitydepositrecord',
            index=models.Index(fields=['to_date'], name='security_de_to_date_39ecf1_idx'),
        ),
    ]
