# Generated by Django 5.2.8 on 2026-09-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_securitydepositrecord_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydepositrecord',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('REFUNDED', 'REFUNDED'), ('PARTIALLY_REFUNDED', 'PARTIALLY_REFUNDED'), ('ADJUSTED', 'ADJUSTED'), ('DEDUCTED', 'DEDUCTED'), ('FORFEITED', 'FORFEITED')], db_index=True, default='PAID', max_length=50),
        ),
    ]
