# Generated by Django 5.1.7 on 2026-03-22 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOwnerFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collaboration_fees', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('opr_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'master_brand_owner_fee',
                'managed': False,
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='BrandOwnerType',
            fields=[
                ('brand_owner_type_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('brand_owner_type_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'master_brand_owner_type',
                'managed': False,
                'ordering': ['brand_owner_type_code'],
            },
        ),
        migrations.CreateModel(
            name='LiquorCategory',
            fields=[
                ('liquor_cat_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('liquor_cat_desc', models.CharField(max_length=100)),
                ('liquor_cat_abbr', models.CharField(max_length=10)),
                ('delete_status', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'master_liquor_category',
                'managed': False,
                'ordering': ['liquor_cat_code'],
            },
        ),
        migrations.CreateModel(
            name='LiquorKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_kind_code', models.PositiveSmallIntegerField()),
                ('liquor_kind_desc', models.CharField(max_length=100)),
                ('liquor_kind_abbr', models.CharField(max_length=20)),
                ('delete_status', models.CharField(default='N', max_length=1)),
                ('liquor_cat', models.ForeignKey(db_column='liquor_cat_code', on_delete=django.db.models.deletion.PROTECT, related_name='kinds', to='masters_company_collaboration.liquorcategory')),
            ],
            options={
                'db_table': 'master_liquor_kind',
                'managed': False,
                'ordering': ['liquor_cat', 'liquor_kind_code'],
                'unique_together': {('liquor_cat', 'liquor_kind_code')},
            },
        ),
        migrations.CreateModel(
            name='LiquorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_type_code', models.PositiveSmallIntegerField()),
                ('liquor_type_desc', models.CharField(max_length=100)),
                ('liquor_type_code_old', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delete_status', models.CharField(default='N', max_length=1)),
                ('liquor_cat', models.ForeignKey(db_column='liquor_cat_code', on_delete=django.db.models.deletion.PROTECT, related_name='types', to='masters_company_collaboration.liquorcategory')),
                ('liquor_kind', models.ForeignKey(db_column='liquor_kind_id', on_delete=django.db.models.deletion.PROTECT, related_name='types', to='masters_company_collaboration.liquorkind')),
            ],
            options={
                'db_table': 'master_liquor_type',
                'managed': False,
                'ordering': ['liquor_cat', 'liquor_kind', 'liquor_type_code'],
                'unique_together': {('liquor_cat', 'liquor_kind', 'liquor_type_code')},
            },
        ),
        migrations.CreateModel(
            name='BrandOwner',
            fields=[
                ('brand_owner_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('brand_owner_name', models.CharField(max_length=255)),
                ('brand_owner_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('brand_owner_company_address', models.TextField(blank=True, null=True)),
                ('brand_owner_address', models.TextField(blank=True, null=True)),
                ('brand_owner_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('brand_owner_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('brand_owner_origin', models.CharField(choices=[('I', 'India'), ('F', 'Foreign')], default='I', max_length=1)),
                ('brand_owner_country', models.IntegerField(blank=True, null=True)),
                ('brand_owner_state', models.IntegerField(blank=True, null=True)),
                ('liquor_bowner_code', models.CharField(blank=True, max_length=30, null=True)),
                ('brand_owner_licensee_id_no', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_licensee_id_no', models.CharField(blank=True, max_length=30, null=True)),
                ('renewed_upto', models.DateField(blank=True, null=True)),
                ('enable_status', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], default='E', max_length=1)),
                ('opr_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_owner_type', models.ForeignKey(db_column='brand_owner_type_code', on_delete=django.db.models.deletion.PROTECT, related_name='brand_owners', to='masters_company_collaboration.brandownertype')),
            ],
            options={
                'db_table': 'master_brand_owner',
                'managed': False,
                'ordering': ['brand_owner_code'],
                'indexes': [models.Index(fields=['brand_owner_name'], name='mbo_name_idx'), models.Index(fields=['brand_owner_type'], name='mbo_type_idx'), models.Index(fields=['enable_status'], name='mbo_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiquorBrand',
            fields=[
                ('liquor_brand_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('liquor_brand_desc', models.CharField(max_length=255)),
                ('brand_name_alias', models.CharField(blank=True, max_length=20, null=True)),
                ('liquor_type_code_old', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_flag', models.CharField(blank=True, max_length=10, null=True)),
                ('delete_status', models.CharField(default='N', max_length=1)),
                ('liquor_cat', models.ForeignKey(db_column='liquor_cat_code', on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='masters_company_collaboration.liquorcategory')),
                ('liquor_kind', models.ForeignKey(db_column='liquor_kind_id', on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='masters_company_collaboration.liquorkind')),
                ('liquor_type', models.ForeignKey(db_column='liquor_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='masters_company_collaboration.liquortype')),
            ],
            options={
                'db_table': 'master_liquor_brand',
                'managed': False,
                'ordering': ['liquor_brand_code'],
                'indexes': [models.Index(fields=['liquor_brand_desc'], name='mlb_desc_idx'), models.Index(fields=['liquor_cat'], name='mlb_cat_idx'), models.Index(fields=['liquor_type'], name='mlb_type_idx'), models.Index(fields=['delete_status'], name='mlb_del_idx')],
            },
        ),
    ]
