# Generated by Django 5.1.7 on 2026-04-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters_company_collaboration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquortype',
            name='liquor_cat',
        ),
        migrations.AlterUniqueTogether(
            name='liquortype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='liquortype',
            name='liquor_kind',
        ),
        migrations.DeleteModel(
            name='LiquorCategory',
        ),
        migrations.DeleteModel(
            name='LiquorType',
        ),
    ]
