# Generated by Django 5.2.8 on 2026-07-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters_company_collaboration', '0004_liquorproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquorCategory',
            fields=[
                ('liquor_cat_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('liquor_cat_desc', models.CharField(max_length=100)),
                ('liquor_cat_abbr', models.CharField(max_length=10)),
                ('delete_status', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'master_liquor_category',
                'ordering': ['liquor_cat_code'],
                'managed': False,
            },
        ),
    ]
