# Generated by Django 5.2.8 on 2026-07-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters_company_collaboration', '0005_liquorcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquorType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('liquor_cat', models.PositiveSmallIntegerField(db_column='liquor_cat_code')),
                ('liquor_type_code', models.PositiveSmallIntegerField()),
                ('liquor_type_desc', models.CharField(max_length=100)),
                ('liquor_type_code_old', models.CharField(blank=True, max_length=20, null=True)),
                ('delete_status', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'master_liquor_type_details',
                'ordering': ['liquor_cat', 'liquor_kind', 'liquor_type_code'],
                'managed': False,
            },
        ),
    ]
