# Generated by Django 5.2.8 on 2026-07-19 04:32

from django.db import migrations, models


def populate_brand_owners(apps, schema_editor):
    import os
    master_Brand_owner = apps.get_model('masters_company_collaboration', 'master_Brand_owner')
    file_path = r"F:\excise cloned new\master_bottler.txt"
    if not os.path.exists(file_path):
        return
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    for line in lines[4:]:
        line = line.strip()
        if not line:
            continue
        parts = line.split('\t')
        if len(parts) < 13:
            parts = parts + [''] * (13 - len(parts))
        cleaned = [p.strip() if p.strip() != 'NULL' else None for p in parts]
        if not cleaned[1]:
            continue
        try:
            type_code = int(cleaned[12]) if cleaned[12] else None
        except Exception:
            type_code = None

        master_Brand_owner.objects.update_or_create(
            Liquor_BOwner_Code=cleaned[1],
            defaults={
                'Liquor_BOwner_Origin': cleaned[0],
                'Liquor_BOwner_Country': cleaned[2],
                'Liquor_BOwner_State': cleaned[3],
                'Liquor_BOwner_Name': cleaned[4],
                'Liquor_BOwner_Address': cleaned[5],
                'Liquor_BOwner_PinCode': cleaned[6],
                'Licensee_id_no': cleaned[7],
                'Entry_Flag': cleaned[8],
                'Merged_Flag': cleaned[9],
                'Merged_Liquor_BOwner_Code': cleaned[10],
                'Delete_Status': cleaned[11] or 'N',
                'Brand_Owner_Type_Code': type_code,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('masters_company_collaboration', '0006_liquortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_Brand_owner',
            fields=[
                ('Liquor_BOwner_Origin', models.CharField(blank=True, max_length=10, null=True)),
                ('Liquor_BOwner_Code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Liquor_BOwner_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Liquor_BOwner_State', models.CharField(blank=True, max_length=100, null=True)),
                ('Liquor_BOwner_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Liquor_BOwner_Address', models.TextField(blank=True, null=True)),
                ('Liquor_BOwner_PinCode', models.CharField(blank=True, max_length=20, null=True)),
                ('Licensee_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('Entry_Flag', models.CharField(blank=True, max_length=10, null=True)),
                ('Merged_Flag', models.CharField(blank=True, max_length=10, null=True)),
                ('Merged_Liquor_BOwner_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Delete_Status', models.CharField(default='N', max_length=10)),
                ('Brand_Owner_Type_Code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_brand_owner_table',
                'ordering': ['Liquor_BOwner_Code'],
            },
        ),
        migrations.RunPython(populate_brand_owners),
    ]
