# Generated by Django 5.1.7 on 2026-07-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters_company_collaboration', '0007_master_brand_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandowner',
            options={'managed': False, 'ordering': ['brand_owner_code'], 'verbose_name': 'company details', 'verbose_name_plural': 'company details'},
        ),
        migrations.AlterModelOptions(
            name='master_brand_owner',
            options={'ordering': ['Liquor_BOwner_Code'], 'verbose_name': 'master Brand owner', 'verbose_name_plural': 'master Brand owner'},
        ),
    ]
