# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnaTransitPermitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, default='', max_length=50)),
                ('sole_distributor_name', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('depot_address', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('cases', models.IntegerField(default=0)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('licensee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bottle_type', models.CharField(blank=True, default='', max_length=100)),
                ('bottles_per_case', models.IntegerField(default=12)),
                ('brand_owner', models.CharField(blank=True, default='', max_length=255)),
                ('exfactory_price_rs_per_case', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('excise_duty_rs_per_case', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('education_cess_rs_per_case', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('additional_excise_duty_rs_per_case', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('manufacturing_unit_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_education_cess', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('total_excise_duty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('total_additional_excise', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15)),
                ('to_location', models.CharField(blank=True, default='', max_length=255)),
                ('via_route', models.CharField(blank=True, default='', max_length=255)),
                ('checkpost_entry_name', models.CharField(blank=True, default='', max_length=255)),
                ('checkpost_exit_name', models.CharField(blank=True, default='', max_length=255)),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('driver_license_no', models.CharField(blank=True, default='', max_length=255)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='Ready for Payment', max_length=100)),
                ('status_code', models.CharField(blank=True, default='TRP_01', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transit_permit_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excise_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('additional_excise_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('education_cess_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_details',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('head', models.CharField(max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wallet_transaction_details',
            },
        ),
    ]
