# Generated by Django 5.1.7 on 2025-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnaTransitPermitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('depot_address', models.CharField(max_length=500)),
                ('serial_no', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('ptn', models.IntegerField()),
                ('nlps', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bill_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('sole_distributor', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('item_count', models.IntegerField()),
                ('licensee_id_no', models.CharField(max_length=50)),
                ('education_cess', models.DecimalField(decimal_places=2, max_digits=18)),
                ('excise_duty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('additional_excise_duty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_locked', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ena_transit_permit_detail',
                'ordering': ['-created_at'],
            },
        ),
    ]
