# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ena_transit_permit_details', '0001_initial'),
        ('liquor_data', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_permits', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='liquor_type',
            field=models.ForeignKey(blank=True, db_column='liquor_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_permit_details', to='liquor_data.masterliquortype'),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='size_ml',
            field=models.ForeignKey(blank=True, db_column='size_ml', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_permit_details', to='liquor_data.masterliquorcategory'),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_permits', to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ena_transit_permit_details.wallet'),
        ),
    ]
