# Generated by Django 5.1.7 on 2025-11-28 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_transit_permit_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='additional_excise_duty',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='education_cess',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='excise_duty',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='licensee_id_no',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='nlps',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='ptn',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='sole_distributor',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='total',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='enatransitpermitdetail',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='bill_no',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='size_ml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='sole_distributor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='enatransitpermitdetail',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='enatransitpermitdetail',
            name='depot_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='enatransitpermitdetail',
            table='transit_permit_details',
        ),
    ]
