# Generated by Django 5.1.7 on 2026-04-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena_transit_permit_details', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
