# Generated by Django 5.1.7 on 2026-05-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_data', '0002_rename_masterliquorcategory_to_masterliquorcapacity'),
        ('ena_transit_permit_details', '0003_remove_wallettransaction_wallet_delete_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enatransitpermitdetail',
            name='size_ml',
            field=models.ForeignKey(
                blank=True,
                db_column='size_ml',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='transit_permit_details',
                to='liquor_data.masterliquorcapacity',
            ),
        ),
    ]

