# Generated by Django 5.1.7 on 2026-09-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_transit_permit_details', '0004_update_size_ml_fk_to_masterliquorcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='bottling_fee_rs_per_case',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='enatransitpermitdetail',
            name='total_bottling_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
