# Generated by Django 5.1.7 on 2025-11-07 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('establishment_name', models.CharField(max_length=255)),
                ('licensee_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_up_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'license',
            },
        ),
    ]
