# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.utils.timezone
from models.masters.license.master_license_form import current_time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('source_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source_type', models.CharField(choices=[('new_license_application', 'New License Application'), ('license_application', 'License Application'), ('salesman_barman', 'Salesman/Barman')], max_length=30)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_up_to', models.DateField()),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('is_print_fee_paid', models.BooleanField(default=False)),
                ('printed_on', models.DateTimeField(blank=True, null=True)),
                ('print_fee_paid_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_nonce', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('validation_nonce_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'licenses',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='LicenseValidationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=32, unique=True)),
                ('signed_code', models.TextField(blank=True, default='')),
                ('validation_url', models.TextField(blank=True, default='')),
                ('verification_id', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'license_validation_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterLicenseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensee_cat_code', models.IntegerField(help_text='Primary category code for the license type', verbose_name='Licensee Category Code')),
                ('licensee_scat_code', models.IntegerField(help_text='Secondary category code for the license type', verbose_name='Licensee Subcategory Code')),
                ('license_title', models.CharField(help_text='Title of the license type', max_length=500, verbose_name='License Title')),
                ('counter_foil_statement_1', models.TextField(blank=True, help_text='First counter foil statement for the license', null=True, verbose_name='Counter Foil Statement 1')),
                ('counter_foil_statement_2', models.TextField(blank=True, help_text='Second counter foil statement for the license', null=True, verbose_name='Counter Foil Statement 2')),
                ('counter_foil_statement_3', models.TextField(blank=True, help_text='Third counter foil statement for the license', null=True, verbose_name='Counter Foil Statement 3')),
                ('terms_declaration_statement', models.TextField(blank=True, help_text='Terms and conditions declaration statement', null=True, verbose_name='Terms Declaration Statement')),
                ('opr_date', models.TimeField(default=current_time, help_text='Time when record was created/modified', verbose_name='Operation Time')),
                ('user_id', models.CharField(default='admin', help_text='User who created/modified the record', max_length=50, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Master License Form',
                'verbose_name_plural': 'Master License Forms',
                'db_table': 'master_license_form',
                'ordering': ['licensee_cat_code', 'licensee_scat_code'],
            },
        ),
        migrations.CreateModel(
            name='MasterLicenseFormTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensee_cat_code', models.IntegerField(help_text='Primary category code for the license type', verbose_name='Licensee Category Code')),
                ('licensee_scat_code', models.IntegerField(help_text='Secondary category code for the license type', verbose_name='Licensee Subcategory Code')),
                ('sl_no', models.IntegerField(help_text='Serial Number for multiple terms', verbose_name='Serial Number')),
                ('license_terms', models.TextField(blank=True, help_text='Terms and conditions for the license form', null=True, verbose_name='License Terms')),
                ('user_id', models.CharField(default='admin', help_text='User who created/modified the record', max_length=50, verbose_name='User ID')),
                ('opr_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when record was created/modified', verbose_name='Operation Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Master License Form Terms',
                'verbose_name_plural': 'Master License Form Terms',
                'db_table': 'master_license_form_terms',
                'ordering': ['licensee_cat_code', 'licensee_scat_code', 'sl_no'],
            },
        ),
    ]
