# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_initial'),
        ('license', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='license',
            name='excise_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses_issued_in_districts', to='core.district'),
        ),
        migrations.AddField(
            model_name='license',
            name='license_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory'),
        ),
        migrations.AddField(
            model_name='license',
            name='license_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.licensesubcategory'),
        ),
        migrations.AddField(
            model_name='license',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='licensevalidationtoken',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_tokens', to='license.license'),
        ),
        migrations.AddIndex(
            model_name='masterlicenseform',
            index=models.Index(fields=['licensee_cat_code'], name='master_lice_license_4b6fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='masterlicenseform',
            index=models.Index(fields=['licensee_scat_code'], name='master_lice_license_254119_idx'),
        ),
        migrations.AddIndex(
            model_name='masterlicenseform',
            index=models.Index(fields=['license_title'], name='master_lice_license_aaaa13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterlicenseform',
            unique_together={('licensee_cat_code', 'licensee_scat_code')},
        ),
        migrations.AddIndex(
            model_name='masterlicenseformterms',
            index=models.Index(fields=['licensee_cat_code'], name='master_lice_license_03d85a_idx'),
        ),
        migrations.AddIndex(
            model_name='masterlicenseformterms',
            index=models.Index(fields=['licensee_scat_code'], name='master_lice_license_e928a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterlicenseformterms',
            unique_together={('licensee_cat_code', 'licensee_scat_code', 'sl_no')},
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_id'], name='licenses_license_ca8a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['source_type'], name='licenses_source__5608ee_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_category'], name='licenses_license_202059_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_sub_category'], name='licenses_license_1847ea_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['is_active'], name='licenses_is_acti_e9f0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['valid_up_to'], name='licenses_valid_u_55cab5_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['validation_nonce'], name='licenses_validat_5c075c_idx'),
        ),
        migrations.AddIndex(
            model_name='licensevalidationtoken',
            index=models.Index(fields=['license'], name='license_val_license_c33b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='licensevalidationtoken',
            index=models.Index(fields=['created_at'], name='license_val_created_c682b9_idx'),
        ),
    ]
