# Generated by Django 5.1.7 on 2025-11-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('license', '0001_initial'),
        ('license_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issued_license', to='license_application.licenseapplication'),
        ),
        migrations.AddField(
            model_name='license',
            name='excise_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses_issued_in_districts', to='core.district'),
        ),
        migrations.AddField(
            model_name='license',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensetype'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['excise_district'], name='license_excise__b99738_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_type'], name='license_license_af1c07_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['is_active'], name='license_is_acti_d88885_idx'),
        ),
    ]
