# Generated by Django 5.1.7 on 2025-12-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('license', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='license_excise__b99738_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='license_license_af1c07_idx',
        ),
        migrations.RenameIndex(
            model_name='license',
            new_name='licenses_is_acti_e9f0b1_idx',
            old_name='license_is_acti_d88885_idx',
        ),
        migrations.RemoveField(
            model_name='license',
            name='application',
        ),
        migrations.RemoveField(
            model_name='license',
            name='establishment_name',
        ),
        migrations.RemoveField(
            model_name='license',
            name='license_type',
        ),
        migrations.RemoveField(
            model_name='license',
            name='licensee_name',
        ),
        migrations.AddField(
            model_name='license',
            name='license_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='source_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='source_object_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='source_type',
            field=models.CharField(choices=[('new_license_application', 'New License Application'), ('license_application', 'License Application'), ('salesman_barman', 'Salesman/Barman')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='license_id',
            field=models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_id'], name='licenses_license_ca8a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['source_type'], name='licenses_source__5608ee_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_category'], name='licenses_license_202059_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['valid_up_to'], name='licenses_valid_u_55cab5_idx'),
        ),
        migrations.AlterModelTable(
            name='license',
            table='licenses',
        ),
    ]
