# Generated by Django 5.2.8 on 2026-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_license_issue_valid_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='source_type',
            field=models.CharField(choices=[('new_license_application', 'New License Application'), ('license_application', 'License Application'), ('salesman_barman', 'Salesman/Barman'), ('company_registration', 'Company Registration')], max_length=30),
        ),
    ]
