# Generated by Django 5.1.7 on 2025-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_license_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_id',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
