# Generated by Django 5.1.7 on 2025-12-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_license_license_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_print_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='print_fee_paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='printed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
