# Generated by Django 5.1.7 on 2026-10-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_license_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='source_type',
            field=models.CharField(choices=[('new_license_application', 'New License Application'), ('license_application', 'License Application'), ('salesman_barman', 'Salesman/Barman'), ('company_registration', 'Company Registration'), ('company_collaboration', 'Company Collaboration')], max_length=30),
        ),
    ]
