# Generated by Django 5.1.7 on 2026-05-01 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterHeadOfAccount',
            fields=[
                ('head_of_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sl_no', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('major_head', models.CharField(max_length=10)),
                ('sub_major_head', models.CharField(blank=True, max_length=10, null=True)),
                ('minor_head', models.CharField(max_length=10)),
                ('sub_head', models.CharField(blank=True, max_length=10, null=True)),
                ('detailed_head', models.CharField(max_length=20)),
                ('object_head', models.CharField(blank=True, max_length=10, null=True)),
                ('detailed_head_driscription', models.CharField(max_length=500)),
                ('pay_type', models.CharField(blank=True, max_length=20, null=True)),
                ('visible_status', models.CharField(default='Y', max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sems_master_head_of_account',
            },
        ),
        migrations.CreateModel(
            name='MasterPaymentModule',
            fields=[
                ('module_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('module_desc', models.CharField(max_length=200)),
                ('visibility_status', models.CharField(default='Y', max_length=1)),
                ('active_payment_mode', models.CharField(default='O', max_length=1)),
                ('payment_invoking_page', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_response_page', models.CharField(blank=True, max_length=500, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('opr_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sems_master_payment_module',
            },
        ),
        migrations.CreateModel(
            name='PaymentBilldeskTransaction',
            fields=[
                ('utr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id_no_hoa', models.CharField(max_length=50)),
                ('payer_id', models.CharField(max_length=50)),
                ('payment_module_code', models.CharField(max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('request_merchantid', models.CharField(blank=True, max_length=100, null=True)),
                ('request_currencytype', models.CharField(blank=True, max_length=10, null=True)),
                ('request_typefield1', models.CharField(blank=True, max_length=10, null=True)),
                ('request_securityid', models.CharField(blank=True, max_length=100, null=True)),
                ('request_typefield2', models.CharField(blank=True, max_length=10, null=True)),
                ('request_additionalinfo1', models.CharField(blank=True, max_length=200, null=True)),
                ('request_additionalinfo2', models.CharField(blank=True, max_length=200, null=True)),
                ('request_additionalinfo3', models.CharField(blank=True, max_length=200, null=True)),
                ('request_additionalinfo4', models.CharField(blank=True, max_length=200, null=True)),
                ('request_additionalinfo5', models.CharField(blank=True, max_length=200, null=True)),
                ('request_additionalinfo6', models.CharField(blank=True, max_length=200, null=True)),
                ('request_additionalinfo7', models.CharField(blank=True, max_length=200, null=True)),
                ('request_return_url', models.CharField(blank=True, max_length=500, null=True)),
                ('request_checksum', models.CharField(blank=True, max_length=500, null=True)),
                ('request_string', models.TextField(blank=True, null=True)),
                ('response_string', models.TextField(blank=True, null=True)),
                ('response_merchantid', models.CharField(blank=True, max_length=100, null=True)),
                ('response_customerid', models.CharField(blank=True, max_length=100, null=True)),
                ('response_txnreferenceno', models.CharField(blank=True, max_length=100, null=True)),
                ('response_bankreferenceno', models.CharField(blank=True, max_length=100, null=True)),
                ('response_txnamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('response_bankid', models.CharField(blank=True, max_length=50, null=True)),
                ('response_bankmerchantid', models.CharField(blank=True, max_length=100, null=True)),
                ('response_txntype', models.CharField(blank=True, max_length=50, null=True)),
                ('response_currencyname', models.CharField(blank=True, max_length=10, null=True)),
                ('response_itemcode', models.CharField(blank=True, max_length=50, null=True)),
                ('response_securitytype', models.CharField(blank=True, max_length=50, null=True)),
                ('response_securityid', models.CharField(blank=True, max_length=100, null=True)),
                ('response_securitypassword', models.CharField(blank=True, max_length=100, null=True)),
                ('response_txndate', models.DateTimeField(blank=True, null=True)),
                ('response_authstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('response_settlementtype', models.CharField(blank=True, max_length=50, null=True)),
                ('response_additionalinfo1', models.CharField(blank=True, max_length=200, null=True)),
                ('response_additionalinfo2', models.CharField(blank=True, max_length=200, null=True)),
                ('response_additionalinfo3', models.CharField(blank=True, max_length=200, null=True)),
                ('response_additionalinfo4', models.CharField(blank=True, max_length=200, null=True)),
                ('response_additionalinfo5', models.CharField(blank=True, max_length=200, null=True)),
                ('response_additionalinfo6', models.CharField(blank=True, max_length=200, null=True)),
                ('response_additionalinfo7', models.CharField(blank=True, max_length=200, null=True)),
                ('response_errorstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('response_errordescription', models.CharField(blank=True, max_length=500, null=True)),
                ('response_checksum', models.CharField(blank=True, max_length=500, null=True)),
                ('response_checksum_calculated', models.CharField(blank=True, max_length=500, null=True)),
                ('response_initial_authstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('response_initial_datetime', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='P', max_length=1)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('opr_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sems_payment_transaction_billdesk',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayParameters',
            fields=[
                ('sl_no', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_gateway_name', models.CharField(max_length=50)),
                ('merchantid', models.CharField(max_length=100)),
                ('securityid', models.CharField(max_length=100)),
                ('encryption_key', models.CharField(max_length=255)),
                ('return_url', models.CharField(max_length=500)),
                ('frontend_success_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sems_gateway_Parameters',
            },
        ),
        migrations.CreateModel(
            name='PaymentSendHOA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id_no', models.CharField(max_length=50)),
                ('head_of_account', models.CharField(max_length=50)),
                ('licensee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_module_code', models.CharField(blank=True, max_length=20, null=True)),
                ('requisition_no', models.CharField(blank=True, max_length=50, null=True)),
                ('opr_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sems_payment_send_hoa',
            },
        ),
        migrations.CreateModel(
            name='PaymentModuleHoa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('opr_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('head_of_account', models.ForeignKey(db_column='head_of_account', on_delete=django.db.models.deletion.RESTRICT, to='payment_gateway.masterheadofaccount')),
                ('module_code', models.ForeignKey(db_column='module_code', on_delete=django.db.models.deletion.RESTRICT, to='payment_gateway.masterpaymentmodule')),
            ],
            options={
                'db_table': 'sems_module_hoa',
            },
        ),
    ]
