# Generated by Django 5.1.7 on 2026-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_masterheadofaccount_masterpaymentmodule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpaymentmodule',
            name='payment_invoking_page',
        ),
        migrations.RemoveField(
            model_name='masterpaymentmodule',
            name='payment_response_page',
        ),
        migrations.AddField(
            model_name='masterpaymentmodule',
            name='license_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
