# Generated by Django 5.1.7 on 2026-05-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_remove_masterpaymentmodule_payment_invoking_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodulehoa',
            name='head_of_account',
            field=models.ForeignKey(db_column='sl_no', on_delete=django.db.models.deletion.RESTRICT, to='payment_gateway.masterheadofaccount'),
        ),
    ]
