# Generated by Django 5.1.7 on 2026-04-24 04:30

from django.db import migrations, models


def backfill_requisition_no(apps, schema_editor):
    PaymentSendHOA = apps.get_model("payment_gateway", "PaymentSendHOA")
    for row in PaymentSendHOA.objects.all().only("id", "requisition_id_no", "requisition_no"):
        value = str(getattr(row, "requisition_id_no", "") or "").strip()
        if not value:
            value = "NA"
        row.requisition_no = value[:50]
        row.save(update_fields=["requisition_no"])


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_add_frontend_success_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsendhoa',
            name='requisition_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(backfill_requisition_no, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="paymentsendhoa",
            name="requisition_id_no",
        ),
        migrations.RemoveField(
            model_name="paymentsendhoa",
            name="user_id",
        ),
    ]
