# Generated by Django 5.1.7 on 2026-05-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_alter_paymentmodulehoa_head_of_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodulehoa',
            name='head_of_account',
            field=models.ForeignKey(db_column='head_of_account', on_delete=django.db.models.deletion.RESTRICT, to='payment_gateway.masterheadofaccount'),
        ),
    ]
