# Generated by Django 5.1.7 on 2026-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0005_alter_paymentmodulehoa_head_of_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpaymentmodule',
            name='active_payment_mode',
        ),
        migrations.AlterField(
            model_name='masterheadofaccount',
            name='visible_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='masterpaymentmodule',
            name='visibility_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentmodulehoa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
