# Generated by Django 5.1.7 on 2026-04-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0006_masterheadofaccount_masterpaymentmodule_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentgatewayparameters',
            table='sems_gateway_Parameters',
        ),
    ]
