# Generated by Django 5.1.7 on 2026-05-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0006_remove_masterpaymentmodule_active_payment_mode_and_more'),
        ('wallet', '0005_alter_walletbalance_wallet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodulehoa',
            name='wallet_type',
            field=models.ForeignKey(db_column='wallet_type', default='license_fee', on_delete=django.db.models.deletion.RESTRICT, to='wallet.masterwallettype'),
            preserve_default=False,
        ),
    ]
