# Generated by Django 5.1.7 on 2026-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0007_paymentmodulehoa_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayparameters',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
