# Generated by Codex on 2026-05-29

from decimal import Decimal
from django.db import migrations


PACHWAI_MODULE_CODE = "NLI_ADD_PACHWAI"
DRAUGHT_BEER_MODULE_CODE = "NLI_ADD_DRAUGHT_BEER"


def _upsert(apps, module_code: str, module_desc: str, license_fee: Decimal):
    MasterPaymentModule = apps.get_model("payment_gateway", "MasterPaymentModule")
    obj, _created = MasterPaymentModule.objects.update_or_create(
        module_code=str(module_code),
        defaults={
            "module_desc": str(module_desc)[:200],
            "license_fee": license_fee,
            "visibility_status": True,
        },
    )
    return obj


def forwards(apps, schema_editor):
    _upsert(apps, PACHWAI_MODULE_CODE, "New License (Additional Charge) - Pachwai", Decimal("3000.00"))
    _upsert(apps, DRAUGHT_BEER_MODULE_CODE, "New License (Additional Charge) - Draught Beer", Decimal("5000.00"))


def backwards(apps, schema_editor):
    MasterPaymentModule = apps.get_model("payment_gateway", "MasterPaymentModule")
    MasterPaymentModule.objects.filter(module_code__in=[PACHWAI_MODULE_CODE, DRAUGHT_BEER_MODULE_CODE]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0008_alter_paymentgatewayparameters_is_active"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

