# Generated by Django 5.1.7 on 2026-06-17 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0009_seed_additional_new_license_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSBIePayTransaction',
            fields=[
                ('order_ref_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sbi_order_ref_number', models.CharField(blank=True, max_length=50, null=True)),
                ('atrn', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_id', models.CharField(max_length=50)),
                ('payment_module_code', models.CharField(max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('head_of_account', models.CharField(blank=True, max_length=200, null=True)),
                ('wallet_type', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('request_payload', models.TextField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(default='P', max_length=1)),
                ('transaction_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ref_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('opr_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sems_payment_transaction_sbiepay',
            },
        ),
        migrations.DeleteModel(
            name='PaymentBilldeskTransaction',
        ),
    ]
