# Generated by Django 5.1.7 on 2026-04-06 08:24

from models.transactional.license_application.models import upload_document_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseApplication',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('license', models.CharField(max_length=100)),
                ('establishment_name', models.CharField(max_length=255)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('license_no', models.CharField(blank=True, max_length=60, null=True)),
                ('initial_grant_date', models.DateField(blank=True, null=True)),
                ('renewed_from', models.DateField(blank=True, null=True)),
                ('valid_up_to', models.DateField(blank=True, null=True)),
                ('yearly_license_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('license_nature', models.CharField(max_length=100)),
                ('functioning_status', models.CharField(max_length=100)),
                ('mode_of_operation', models.CharField(max_length=100)),
                ('location_category', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('road_name', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('company_cin', models.CharField(blank=True, max_length=30, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('company_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('father_husband_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('pan', models.CharField(max_length=20)),
                ('member_mobile_number', models.BigIntegerField()),
                ('member_email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to=upload_document_path)),
                ('is_fee_calculated', models.BooleanField(default=False)),
                ('is_license_fee_paid', models.BooleanField(default=False)),
                ('is_license_category_updated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'license_application',
            },
        ),
    ]
