# Generated by Django 5.1.7 on 2025-11-13 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0001_initial'),
        ('roles', '0001_initial'),
        ('workflow', '0002_alter_workflowtransition_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenseApplicationTransaction',
            new_name='Transaction',
        ),
    ]
