# Generated by Django 5.1.7 on 2025-08-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='licenseapplication',
            new_name='license_app_current_78da4e_idx',
            old_name='license_app_current_87409b_idx',
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='workflow',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workflow.workflow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objection',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstage'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workflow.workflowstage'),
        ),
    ]
