# Generated by Django 5.1.7 on 2025-08-19 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0002_rename_license_app_current_87409b_idx_license_app_current_78da4e_idx_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplicationtransaction',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='workflow.workflowstage'),
        ),
    ]
