# Generated by Django 5.1.7 on 2025-11-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0002_rename_licenseapplicationtransaction_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='forwarded_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='forwarded_to',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='license_application',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Objection',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
