# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('license', '0002_initial'),
        ('license_application', '0002_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='excise_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_excise_districts', to='core.district'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='excise_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_excise_subdivisions', to='core.subdivision'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='license_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensetype'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.policestation'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='renewal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_application_renewal', to='license.license'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='site_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_site_subdivisions', to='core.subdivision'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workflow.workflow'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['excise_district'], name='license_app_excise__a9c318_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['license_type'], name='license_app_license_ec78a8_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['excise_subdivision'], name='license_app_excise__d291fc_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['current_stage'], name='license_app_current_78da4e_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['applicant'], name='license_app_applica_f971a2_idx'),
        ),
    ]
