# Generated by Django 5.1.7 on 2025-12-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0003_remove_transaction_forwarded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseapplication',
            name='is_print_fee_paid',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='print_count',
        ),
        migrations.DeleteModel(
            name='SiteEnquiryReport',
        ),
    ]
