# Generated by Django 5.1.7 on 2025-10-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0003_alter_licenseapplicationtransaction_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='license_application.licenseapplication'),
        ),
    ]
