# Generated by Django 5.1.7 on 2025-12-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_application', '0004_remove_licenseapplication_is_print_fee_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationFee',
        ),
    ]
