"""
Django settings for excise_backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&9z_bt2h_b0gz8dho0u$j-g@569rl^@i071z4&j&p!qz7ez*(m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['sems.sikkim.gov.in', 'localhost', '127.0.0.1', '*']

CSRF_TRUSTED_ORIGINS = [
    "https://sems.sikkim.gov.in",
    "https://sems.sikkim.gov.in:8443",
]

# Application definition

INSTALLED_APPS = [
    #####################
    # External Packages #
    #####################

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # jwt stuff

    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'rest_framework_simplejwt',

    # Cross-Origin Resource Sharing
    'corsheaders',
    'captcha',

    #########################
    # User defined packages #
    #########################
    
    # masters models

    'models.masters',
    'models.masters.core',
    'models.masters.license',
    'models.masters.contact_us',
    'models.masters.about_us',
    'models.masters.preventive_raids',
    'models.masters.company_collaboration',

    'models.masters.supply_chain.bulk_spirit',
    'models.masters.supply_chain.distributor_data_details',
    'models.masters.supply_chain.ena_checkpost',
    'models.masters.supply_chain.ena_purpose',
    'models.masters.supply_chain.liquor_data',
    'models.masters.supply_chain.ena_distillery_details',
    'models.masters.supply_chain.profile',
    'models.masters.supply_chain.transit_permit',
    'models.masters.supply_chain.vehicles',
    'models.masters.supply_chain.hologram_supplier',

    # transcational models
    'models.transactional',
    'models.transactional.company_registration',
    'models.transactional.company_collaboration',
    'models.transactional.license_renewal_application',
    'models.transactional.special_permit',
    'models.transactional.distributor_permit',
    'models.transactional.site_enquiry',
    'models.transactional.new_license_application',
    'models.transactional.label_registration',
    'models.transactional.salesman_barman',
    'models.transactional.logs',
    'models.transactional.wallet',
    'models.transactional.payment_gateway',
    'models.transactional.supply_chain.ena_transit_permit_details',
    'models.transactional.supply_chain.ena_revalidation_details',
    'models.transactional.supply_chain.ena_requisition_details',  
    'models.transactional.supply_chain.ena_cancellation_details',
    'models.transactional.supply_chain.hologram',
    'models.transactional.supply_chain.brand_warehouse', 
    'auth.roles',
    'auth.user',
    'auth.workflow'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'excise_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'excise_backend.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}   

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'eAbkari_db',       # Database name
        'USER': 'postgres',         # Your PostgreSQL username
        'PASSWORD': 'postgres',     # Your PostgreSQL password
        'HOST': 'localhost',        
        'PORT': '5433',             # Default PostgreSQL port
        'CONN_MAX_AGE': 300,        # Don't reuse connections — avoids aborted transaction state
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'amritraj97.nic@gmail.com'
EMAIL_HOST_PASSWORD = 'gzrt qieo egth zjpt'
DEFAULT_FROM_EMAIL = 'amritraj97.nic@gmail.com'

# Frontend URL used for password reset emails.
PASSWORD_RESET_FRONTEND_URL = os.getenv(
    "PASSWORD_RESET_FRONTEND_URL",
    "https://sems.sikkim.gov.in/reset-password",
    # "http://localhost:4200/reset-password"
).rstrip("/")

DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20MB

# OTP Configuration
OTP_EXPIRY_SECONDS = 600  # 10 minutes

# Redis cache configuration for CAPTCHA storage
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 1,
            "SOCKET_TIMEOUT": 1,
        }
    }
}
DASHBOARD_COUNTS_CACHE_TIMEOUT = int(os.getenv("DASHBOARD_COUNTS_CACHE_TIMEOUT", "600"))
DASHBOARD_CACHE_FAILURE_COOLDOWN = int(os.getenv("DASHBOARD_CACHE_FAILURE_COOLDOWN", "60"))

AUTH_USER_MODEL = 'user.CustomUser'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "https://sems.sikkim.gov.in:8443",
    "https://sems.sikkim.gov.in",
    "http://localhost:4200", 
]

CORS_ALLOW_CREDENTIALS = True

# OTP SMS gateway configuration (environment-driven)
OTP_SMS_BASE_URL = os.getenv('OTP_SMS_BASE_URL', 'https://smsgw.sms.gov.in/failsafe/MLink')
# Keep sensitive values empty by default; prefer DB-backed SMSServiceConfig.
OTP_SMS_USERNAME = os.getenv('OTP_SMS_USERNAME', '')
OTP_SMS_PIN = os.getenv('OTP_SMS_PIN', '')
OTP_SMS_SIGNATURE = os.getenv('OTP_SMS_SIGNATURE', '')
OTP_SMS_ENTITY_ID = os.getenv('OTP_SMS_ENTITY_ID', '')
OTP_SMS_TEMPLATE_ID = os.getenv('OTP_SMS_TEMPLATE_ID', '1007722920127309405')
OTP_SMS_MESSAGE_TEMPLATE = os.getenv(
    'OTP_SMS_MESSAGE_TEMPLATE',
    'From eAbkari, GoSK :\nYour OTP is {otp}\n Thanks'
)
OTP_SMS_VERIFY_SSL = os.getenv('OTP_SMS_VERIFY_SSL', 'false').strip().lower() == 'true'

OTP_SMS_CA_BUNDLE = os.getenv('OTP_SMS_CA_BUNDLE', '').strip()
OTP_SMS_TIMEOUT_SECONDS = int(os.getenv('OTP_SMS_TIMEOUT_SECONDS', '10'))
OTP_SMS_FORCE_SEND_IN_DEBUG = os.getenv('OTP_SMS_FORCE_SEND_IN_DEBUG', 'true').strip().lower() == 'true'
OTP_EXPOSE_IN_RESPONSE = os.getenv('OTP_EXPOSE_IN_RESPONSE', 'false').strip().lower() == 'true'
OTP_REQUEST_LIMIT = int(os.getenv('OTP_REQUEST_LIMIT', '15'))
OTP_REQUEST_WINDOW_MINUTES = int(os.getenv('OTP_REQUEST_WINDOW_MINUTES', '15'))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),       # default: 5 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # default: 1 day
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Payment gateway (BillDesk) defaults for local/UAT.
BILLDESK_GATEWAY_URL = os.getenv(
    "BILLDESK_GATEWAY_URL",
    "https://uat1.billdesk.com/u2/payments/ve1_2/orders/create",
).strip()

# Where Django redirects the user after BillDesk response is validated.
PAYMENT_GATEWAY_FRONTEND_SUCCESS_URL = os.getenv(
    "PAYMENT_GATEWAY_FRONTEND_SUCCESS_URL",
    # "https://sems.sikkim.gov.in/dashboard/wallet-recharge/success",
    "http://localhost:4200/dashboard/wallet-recharge/success",
).strip()
PAYMENT_GATEWAY_FRONTEND_NEW_LICENSE_RECEIPT_URL = os.getenv(
    "PAYMENT_GATEWAY_FRONTEND_NEW_LICENSE_RECEIPT_URL",
    # "https://sems.sikkim.gov.in/dashboard/new-license/application-fee/receipt",
    "http://localhost:4200/dashboard/new-license/application-fee/receipt",
).strip()

# Captcha tuning: keep it readable with only light line noise.
CAPTCHA_LENGTH = 5
CAPTCHA_TIMEOUT = 300  # minutes
CAPTCHA_FONT_SIZE = 30
CAPTCHA_IMAGE_SIZE = (130, 42)
CAPTCHA_LETTER_ROTATION = (-5, 5)
CAPTCHA_NOISE_FUNCTIONS = (
    "captcha.helpers.noise_arcs",
    "auth.user.captcha_helpers.noise_dots_light",
)
CAPTCHA_FILTER_FUNCTIONS = ()
CAPTCHA_LETTER_COLOR_FUNCT = "auth.user.captcha_helpers.random_letter_color_dark"
CAPTCHA_FOREGROUND_COLOR = "#2b2b2b"
CAPTCHA_BACKGROUND_COLOR = "#ffffff"


# ==============================================================================
# SECURITY HEADERS CONFIGURATION
# ==============================================================================

# Strict-Transport-Security (HSTS)
# Forces browsers to connect over HTTPS for 1 year
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# X-Content-Type-Options
# Prevents browsers from MIME-sniffing responses
SECURE_CONTENT_TYPE_NOSNIFF = True

# Referrer-Policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Browser XSS Filtering
SECURE_BROWSER_XSS_FILTER = True


# ==============================================================================
# CONTENT SECURITY POLICY (django-csp)
# ==============================================================================

# Default policy for loading assets
CSP_DEFAULT_SRC = ("'self'",)

# Restrict allowed script origins
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
)

# Restrict allowed stylesheet origins (Includes fonts and Bootstrap CDNs)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
)

# Restrict allowed image sources (allows base64 and blob previews)
CSP_IMG_SRC = ("'self'", "data:", "blob:")

# Fonts: Allow local fonts, Google Fonts, and Bootstrap Icon CDNs
CSP_FONT_SRC = (
    "'self'",
    "data:",
    "https://fonts.gstatic.com",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
)

# API Connections & Payment Gateways
CSP_CONNECT_SRC = (
    "'self'",
    "https://sems.sikkim.gov.in:8443",
    "https://sems.sikkim.gov.in",
    "http://localhost:4200",
    "https://*.billdesk.com",
)

# Restrict iframe embedded sources (Required for PDF/Document previews)
CSP_FRAME_SRC = (
    "'self'",
    "blob:",
    "data:",
    "https://*.billdesk.com",
)

CSP_OBJECT_SRC = ("'none'",)

# Allowed destinations for form submissions
CSP_FORM_ACTION = (
    "'self'",
    "https://*.billdesk.com",
)


# ==============================================================================
# PRODUCTION HTTPS, REVERSE PROXY & COOKIE SECURITY
# ==============================================================================

# Detect HTTPS header from reverse proxy (Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Enforce secure cookies (Cookies only transmitted over HTTPS)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True