"""
Django settings for excise_backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&9z_bt2h_b0gz8dho0u$j-g@569rl^@i071z4&j&p!qz7ez*(m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    #####################
    # External Packages #
    #####################

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # jwt stuff

    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'rest_framework_simplejwt',

    # captcha
    'captcha',

    # Cross-Origin Resource Sharing
    'corsheaders',

    #########################
    # User defined packages #
    #########################
    
    # masters models

    'models.masters',
    'models.masters.core',
    'models.masters.license',
    'models.masters.contact_us',
    'models.masters.company_collaboration',

    'models.masters.supply_chain.bulk_spirit',
    'models.masters.supply_chain.distributor_data_details',
    'models.masters.supply_chain.ena_checkpost',
    'models.masters.supply_chain.ena_purpose',
    'models.masters.supply_chain.liquor_data',
    'models.masters.supply_chain.ena_distillery_details',
    'models.masters.supply_chain.profile',
    'models.masters.supply_chain.transit_permit',
    'models.masters.supply_chain.vehicles',
    # 'models.masters.supply_chain.status_master',

    # transcational models
    'models.transactional',
    'models.transactional.company_registration',
    'models.transactional.company_collaboration',
    'models.transactional.license_application',
    'models.transactional.site_enquiry',
    'models.transactional.new_license_application',
    'models.transactional.label_registration',
    'models.transactional.salesman_barman',
    'models.transactional.logs',
    'models.transactional.wallet',
    'models.transactional.payment_gateway',
    'models.transactional.supply_chain.ena_transit_permit_details',
    'models.transactional.supply_chain.ena_revalidation_details',
    'models.transactional.supply_chain.ena_requisition_details',  
    'models.transactional.supply_chain.ena_cancellation_details',
    'models.transactional.supply_chain.hologram',
    'models.transactional.supply_chain.brand_warehouse',
    # auth models 
    'auth.roles',
    'auth.user',
    'auth.workflow'
]

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'excise_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'excise_backend.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sems_db',       # Database name
        'USER': 'postgres',         # Your PostgreSQL username
        'PASSWORD': 'sameer123',  # Your PostgreSQL password
        'HOST': 'localhost',        # Default host
        'PORT': '5433',             # Default PostgreSQL port
        'CONN_MAX_AGE': 0,          # Don't reuse connections — avoids aborted transaction state
    }
}

# Forgot Password Email Settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# For production, use SMTP:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'amritraj97.nic@gmail.com'
EMAIL_HOST_PASSWORD = 'gzrt qieo egth zjpt'
DEFAULT_FROM_EMAIL = 'amritraj97.nic@gmail.com'

# Frontend URL used for password reset emails.
PASSWORD_RESET_FRONTEND_URL = os.getenv(
    "PASSWORD_RESET_FRONTEND_URL",
    "https://sems.sikkim.gov.in/reset-password",
    # "http://localhost:4200/reset-password"
).rstrip("/")

DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520 

FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440


AUTH_USER_MODEL = 'user.CustomUser'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#    {
#        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#    },
#]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

CORS_ORIGIN_ALLOW_ALL = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),       # default: 5 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # default: 1 day
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Payment gateway (BillDesk) defaults for local/UAT.
BILLDESK_GATEWAY_URL = os.getenv(
    "BILLDESK_GATEWAY_URL",
    "https://uat1.billdesk.com/pgidsk/PGIMerchantPayment",
).strip()

# # Local testing: simulate BillDesk ProcessPayment and callback without hitting BillDesk servers.
# # Default to mock in DEBUG to avoid hanging redirects to external UAT/Prod gateways during local dev.
# _billdesk_use_mock_raw = os.getenv("BILLDESK_USE_MOCK")
# if _billdesk_use_mock_raw is None:
#     BILLDESK_USE_MOCK = bool(DEBUG)
# else:
#     BILLDESK_USE_MOCK = _billdesk_use_mock_raw.strip() in ("1", "true", "True", "YES", "yes")
# BILLDESK_MOCK_AUTH_STATUS = os.getenv("BILLDESK_MOCK_AUTH_STATUS", "0300").strip()  # 0300=success
# _billdesk_mock_pending_raw = os.getenv("BILLDESK_MOCK_SIMULATE_PENDING", "0")
# BILLDESK_MOCK_SIMULATE_PENDING = str(_billdesk_mock_pending_raw or "").strip() in ("1", "true", "True", "YES", "yes")

# Where Django redirects the user after BillDesk response is validated.
PAYMENT_GATEWAY_FRONTEND_SUCCESS_URL = os.getenv(
    "PAYMENT_GATEWAY_FRONTEND_SUCCESS_URL",
    "http://localhost:4200/dashboard/wallet-recharge/success",
).strip()
PAYMENT_GATEWAY_FRONTEND_NEW_LICENSE_RECEIPT_URL = os.getenv(
    "PAYMENT_GATEWAY_FRONTEND_NEW_LICENSE_RECEIPT_URL",
    "http://localhost:4200/dashboard/new-license/application-fee/receipt",
).strip()

# Captcha tuning: keep it readable with only light line noise.
CAPTCHA_LENGTH = 5
CAPTCHA_TIMEOUT = 5  # minutes
CAPTCHA_FONT_SIZE = 30
CAPTCHA_IMAGE_SIZE = (130, 42)
CAPTCHA_LETTER_ROTATION = (-5, 5)
CAPTCHA_NOISE_FUNCTIONS = (
    "captcha.helpers.noise_arcs",
    "auth.user.captcha_helpers.noise_dots_light",
)
CAPTCHA_FILTER_FUNCTIONS = ()
CAPTCHA_LETTER_COLOR_FUNCT = "auth.user.captcha_helpers.random_letter_color_dark"
CAPTCHA_FOREGROUND_COLOR = "#2b2b2b"
CAPTCHA_BACKGROUND_COLOR = "#ffffff"
