# Generated by Django 5.1.7 on 2025-12-10 10:21

import django.db.models.deletion
from models.transactional.site_enquiry.models import upload_site_image
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEnquiryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('has_traditional_place', models.BooleanField(default=False)),
                ('traditional_place_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('traditional_place_name', models.CharField(blank=True, max_length=1000)),
                ('traditional_place_nature', models.CharField(blank=True, max_length=1000)),
                ('traditional_place_construction', models.CharField(blank=True, choices=[('rcc', 'RCC'), ('wooden_structure', 'Wooden Structure'), ('temporary', 'Temporary')], max_length=20, null=True)),
                ('has_educational_institution', models.BooleanField(default=False)),
                ('educational_institution_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('educational_institution_name', models.CharField(blank=True, max_length=1000)),
                ('educational_institution_nature', models.CharField(blank=True, max_length=1000)),
                ('has_hospital', models.BooleanField(default=False)),
                ('hospital_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=1000)),
                ('has_taxi_stand', models.BooleanField(default=False)),
                ('taxi_stand_name', models.CharField(blank=True, max_length=1000)),
                ('taxi_stand_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_interconnected_with_shops', models.BooleanField(default=False)),
                ('interconnectivity_remarks', models.TextField(blank=True)),
                ('shop_construction_type', models.CharField(choices=[('rcc', 'RCC'), ('wooden_structure', 'Wooden Structure'), ('temporary', 'Temporary')], max_length=20)),
                ('has_excise_shops_nearby', models.BooleanField(default=False)),
                ('nearby_excise_shop_count', models.IntegerField(default=0)),
                ('nearby_excise_shops_remarks', models.TextField(blank=True)),
                ('is_on_highway', models.BooleanField(default=False)),
                ('highway_name', models.TextField(blank=True)),
                ('shop_image_document', models.FileField(upload_to=upload_site_image)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_shop_size_correct', models.BooleanField(default=True)),
                ('shop_size_remarks', models.TextField(blank=True)),
                ('enquiry_officer_comments', models.TextField(blank=True)),
                ('additional_enquiry_officer_comments', models.TextField(blank=True)),
                ('has_id_proof', models.BooleanField()),
                ('id_proof_comments', models.TextField(blank=True)),
                ('has_age_proof', models.BooleanField()),
                ('age_proof_comments', models.TextField(blank=True)),
                ('has_noc_from_landlord', models.BooleanField()),
                ('noc_comments', models.TextField(blank=True)),
                ('has_ownership_proof', models.BooleanField()),
                ('ownership_proof_comments', models.TextField(blank=True)),
                ('has_trade_license', models.BooleanField()),
                ('trade_license_comments', models.TextField(blank=True)),
                ('proposes_barman_or_salesman', models.BooleanField()),
                ('worker_proposal_comments', models.TextField(blank=True)),
                ('worker_docs_valid', models.BooleanField()),
                ('worker_docs_comments', models.TextField(blank=True)),
                ('license_recommendation', models.BooleanField()),
                ('recommendation_comments', models.TextField(blank=True)),
                ('special_remarks', models.TextField(blank=True)),
                ('reporting_place', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'site_enquiry_report',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='site_enquir_content_1637b5_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
