# Generated by Django 5.1.7 on 2026-10-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_enquiry', '0002_revert_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteenquiryreport',
            name='shop_construction_type',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteenquiryreport',
            name='traditional_place_construction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
