# Generated by Django 5.1.7 on 2026-10-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_enquiry', '0003_alter_siteenquiryreport_shop_construction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteenquiryreport',
            name='has_shop_construction',
            field=models.BooleanField(default=True),
        ),
    ]
