# Generated by Django 5.1.7 on 2025-08-18 07:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('REG', 'Registration'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASS_RESET', 'Password Reset'), ('USR_UPD', 'User Profile Update'), ('USR_DEL', 'User Account Deletion')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('target_user', models.ForeignKey(blank=True, help_text='The user whose profile was affected by the activity (e.g., updated or deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who performed the activity.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='logs_userac_user_id_d02984_idx'), models.Index(fields=['timestamp'], name='logs_userac_timesta_5af06e_idx'), models.Index(fields=['target_user', 'activity_type'], name='logs_userac_target__22213d_idx')],
            },
        ),
    ]
