# Generated by Django 5.1.7 on 2026-09-25 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(blank=True, db_index=True, help_text='Direct snapshot of the admin/user ID at the time of action.', max_length=100, null=True)),
                ('username', models.CharField(db_index=True, help_text='Snapshot of the admin/user username at the time of action.', max_length=150)),
                ('full_name', models.CharField(help_text='Snapshot of the admin/user full name (or designation) at the time of action.', max_length=255)),
                ('role', models.CharField(db_index=True, help_text='Snapshot of the role/designation (e.g. Commissioner, Joint Commissioner, OIC Admin, etc.).', max_length=100)),
                ('module_name', models.CharField(db_index=True, help_text='Module name (e.g. ENA Bulk Requisition, Revalidation, Cancellation, Hologram Procurement, etc.).', max_length=150)),
                ('application_id', models.CharField(db_index=True, help_text='Application / Request / Reference number of the target object.', max_length=150)),
                ('object_id', models.CharField(blank=True, help_text='Primary key of the target object.', max_length=255, null=True)),
                ('action', models.CharField(db_index=True, help_text='Action performed (e.g. APPROVE, REJECT, OBJECTION, REVERT, FORWARD, VERIFY, CANCEL, UPDATE, ISSUE, etc.).', max_length=100)),
                ('from_stage', models.CharField(blank=True, help_text='Stage / status before the action was executed.', max_length=150, null=True)),
                ('to_stage', models.CharField(blank=True, help_text='Stage / status after the action was executed.', max_length=150, null=True)),
                ('status', models.CharField(blank=True, help_text='Status summary or outcome of the action.', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Exact remarks, comments, objection details, or rejection reasons entered by the admin.', null=True)),
                ('reverted_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reverted_by_username', models.CharField(blank=True, max_length=150, null=True)),
                ('reverted_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reverted_by_role', models.CharField(blank=True, max_length=100, null=True)),
                ('reverted_to_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reverted_to_username', models.CharField(blank=True, max_length=150, null=True)),
                ('reverted_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reverted_to_role', models.CharField(blank=True, max_length=100, null=True)),
                ('reverted_to_stage', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured context (e.g., objection item list, field diffs, payload details).')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact date and time when the action took place.')),
                ('content_type', models.ForeignKey(blank=True, help_text='Polymorphic content type of the target object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Optional relational link to the user account. Direct identity snapshot columns preserve history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module_name', 'application_id'], name='admin_log_module__b82e35_idx'), models.Index(fields=['username', 'timestamp'], name='admin_log_usernam_6e3a11_idx'), models.Index(fields=['action', 'timestamp'], name='admin_log_action_217e47_idx'), models.Index(fields=['role', 'timestamp'], name='admin_log_role_34cb05_idx'), models.Index(fields=['timestamp'], name='admin_log_timesta_d73266_idx')],
            },
        ),
    ]
