# Generated by Django 5.1.7 on 2026-09-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_adminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='to_stage_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the target stage.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='to_stage_username',
            field=models.CharField(blank=True, db_index=True, help_text='Username of the admin/user to whom the application was forwarded in the next stage.', max_length=150, null=True),
        ),
    ]
