# Generated by Django 5.1.7 on 2026-09-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_adminlog_to_stage_name_adminlog_to_stage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='to_stage_full_name',
            field=models.CharField(blank=True, help_text='Full name of the admin/user to whom the application was forwarded in the next stage.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='to_stage_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Direct snapshot of the ID of the admin/user to whom the application was forwarded in the next stage.', max_length=100, null=True),
        ),
    ]
