# Generated by Django 5.2.8 on 2026-09-19 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0010_seed_new_license_payment_timer_and_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnaBulkSpiritUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('licensee_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('distillery_name', models.CharField(blank=True, default='', max_length=255)),
                ('bulk_spirit_type', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purpose', models.CharField(blank=True, default='Production / Blending', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('status_code', models.CharField(default='BSU_00', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_spirit_usages', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_spirit_usages', to='workflow.workflowstage')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_spirit_usages', to='workflow.workflow')),
            ],
            options={
                'db_table': 'ena_bulk_spirit_usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
