# Generated by Django 5.1.7 on 2025-11-07 10:13

import django.db.models.deletion
from models.transactional.new_license_application.models import upload_document_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('roles', '0001_initial'),
        ('workflow', '0002_alter_workflowtransition_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLicenseApplication',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('is_print_fee_paid', models.BooleanField(default=False)),
                ('is_fee_calculated', models.BooleanField(default=False)),
                ('is_license_fee_paid', models.BooleanField(default=False)),
                ('is_license_category_updated', models.BooleanField(default=False)),
                ('yearly_license_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment_name', models.CharField(max_length=150)),
                ('site_type', models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], max_length=10)),
                ('applicant_name', models.CharField(max_length=150)),
                ('father_husband_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('residential_status', models.CharField(choices=[('Resident', 'Resident'), ('Non-Resident', 'Non-Resident')], max_length=20)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('pan', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('mode_of_operation', models.CharField(choices=[('Self', 'Self'), ('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=20)),
                ('has_sikkim_certificate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('has_excise_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('family_excise_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('criminal_conviction', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('location_category', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('road_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('construction_type', models.CharField(max_length=50)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('site_owned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('noc_obtained', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('company_cin', models.CharField(blank=True, max_length=21, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('company_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pass_photo', models.FileField(upload_to=upload_document_path)),
                ('pan_card', models.FileField(upload_to=upload_document_path)),
                ('sikkim_certificate', models.FileField(upload_to=upload_document_path)),
                ('dob_proof', models.FileField(upload_to=upload_document_path)),
                ('noc_landlord', models.FileField(blank=True, null=True, upload_to=upload_document_path)),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_applications', to='workflow.workflowstage')),
                ('license_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory')),
                ('license_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensesubcategory')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensetype')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.policestation')),
                ('site_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_site_districts', to='core.district')),
                ('site_subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_site_subdivisions', to='core.subdivision')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_applications', to='workflow.workflow')),
            ],
            options={
                'db_table': 'new_license_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=255)),
                ('remarks', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('raised_on', models.DateTimeField(auto_now_add=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_license_objections', to='new_license_application.newlicenseapplication')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_license_objections', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_license_objections_stage', to='workflow.workflowstage')),
            ],
            options={
                'db_table': 'new_license_application_objection',
                'ordering': ['raised_on'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_license_forwarded_by_transactions', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_license_forwarded_to_transactions', to='roles.role')),
                ('license_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_license_transactions', to='new_license_application.newlicenseapplication')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_license_performed_transactions', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_transactions', to='workflow.workflowstage')),
            ],
            options={
                'db_table': 'new_license_application_transaction',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['site_district'], name='new_license_site_di_84321b_idx'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['license_type'], name='new_license_license_ee5332_idx'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['site_subdivision'], name='new_license_site_su_26cf21_idx'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['current_stage'], name='new_license_current_a8da04_idx'),
        ),
    ]
