# Generated by Django 5.1.7 on 2026-04-06 08:24

from models.transactional.new_license_application.models import upload_document_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewLicenseApplication',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('is_print_fee_paid', models.BooleanField(default=False)),
                ('is_fee_calculated', models.BooleanField(default=False)),
                ('is_license_fee_paid', models.BooleanField(default=False)),
                ('is_license_category_updated', models.BooleanField(default=False)),
                ('yearly_license_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment_name', models.CharField(max_length=150)),
                ('site_type', models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], max_length=10)),
                ('applicant_name', models.CharField(max_length=150)),
                ('father_husband_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('residential_status', models.CharField(choices=[('Resident', 'Resident'), ('Non-Resident', 'Non-Resident')], max_length=20)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('pan', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('mode_of_operation', models.CharField(choices=[('Self', 'Self'), ('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=20)),
                ('has_sikkim_certificate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('has_excise_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('family_excise_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('criminal_conviction', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('location_category', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('road_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('construction_type', models.CharField(max_length=50)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('site_owned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('noc_obtained', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('company_cin', models.CharField(blank=True, max_length=21, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('company_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pass_photo', models.FileField(upload_to=upload_document_path)),
                ('pan_card', models.FileField(upload_to=upload_document_path)),
                ('sikkim_certificate', models.FileField(upload_to=upload_document_path)),
                ('dob_proof', models.FileField(upload_to=upload_document_path)),
                ('noc_landlord', models.FileField(blank=True, null=True, upload_to=upload_document_path)),
            ],
            options={
                'db_table': 'new_license_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
