# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('license', '0002_initial'),
        ('new_license_application', '0002_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlicenseapplication',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_applications', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='license_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='license_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensesubcategory'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.licensetype'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.policestation'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='renewal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_license_renewal', to='license.license'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='site_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_site_districts', to='core.district'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='site_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_site_subdivisions', to='core.subdivision'),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_applications', to='workflow.workflow'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['site_district'], name='new_license_site_di_84321b_idx'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['license_type'], name='new_license_license_ee5332_idx'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['site_subdivision'], name='new_license_site_su_26cf21_idx'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['current_stage'], name='new_license_current_a8da04_idx'),
        ),
        migrations.AddIndex(
            model_name='newlicenseapplication',
            index=models.Index(fields=['applicant'], name='new_license_applica_813ea2_idx'),
        ),
    ]
