# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_license_application", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newlicenseapplication",
            name="print_count",
        ),
        migrations.RemoveField(
            model_name="newlicenseapplication",
            name="is_print_fee_paid",
        ),
        migrations.RemoveField(
            model_name="newlicenseapplication",
            name="yearly_license_fee",
        ),
        migrations.AddField(
            model_name="newlicenseapplication",
            name="is_application_fee_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newlicenseapplication",
            name="is_security_fee_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newlicenseapplication",
            name="licensee_fee_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]

