# Generated by Django 5.1.7 on 2026-05-05 04:19

from models.transactional.new_license_application.models import upload_document_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0004_fee_flags_and_license_fee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlicenseapplication',
            name='coi_rc_ss',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='existing_license_category_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='existing_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='existing_site_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='family_license_category_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='family_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='location_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='noc',
            field=models.FileField(blank=True, null=True, upload_to=upload_document_path),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='parcha',
            field=models.FileField(blank=True, null=True, upload_to=upload_document_path),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to=upload_document_path),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='trade_license_covered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
