# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_license_application", "0005_newlicenseapplication_coi_rc_ss_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newlicenseapplication",
            name="pachwai",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newlicenseapplication",
            name="draught_beer",
            field=models.BooleanField(default=False),
        ),
    ]

