# Generated by Django 5.1.7 on 2026-06-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0006_newlicenseapplication_additional_charges_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlicenseapplication',
            name='company_cin',
        ),
        migrations.RemoveField(
            model_name='newlicenseapplication',
            name='company_pan',
        ),
        migrations.RemoveField(
            model_name='newlicenseapplication',
            name='incorporation_date',
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='company_gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
