# Generated by Django 5.1.7 on 2026-06-19 04:45

from models.transactional.new_license_application.models import upload_document_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0007_remove_newlicenseapplication_company_cin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='sikkim_certificate',
            field=models.FileField(blank=True, null=True, upload_to=upload_document_path),
        ),
    ]

