# Generated by Django 5.1.7 on 2026-06-20 04:22

from django.db import migrations, models
import models.transactional.new_license_application.models as new_license_models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0008_alter_newlicenseapplication_sikkim_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='criminal_conviction',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='dob_proof',
            field=models.FileField(blank=True, null=True, upload_to=new_license_models.upload_document_path),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='family_excise_license',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='father_husband_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='has_excise_license',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='has_sikkim_certificate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='mode_of_operation',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Salesman', 'Salesman'), ('Barman', 'Barman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=new_license_models.upload_document_path),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='pass_photo',
            field=models.FileField(blank=True, null=True, upload_to=new_license_models.upload_document_path),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='residential_status',
            field=models.CharField(blank=True, choices=[('Resident', 'Resident'), ('Non-Resident', 'Non-Resident')], max_length=20, null=True),
        ),
    ]
