# Generated by Django 5.1.7 on 2026-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0009_alter_newlicenseapplication_applicant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlicenseapplication',
            name='block_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
