# Generated by Django 5.1.7 on 2026-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0010_newlicenseapplication_block_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
