# Generated by Django 5.2.8 on 2026-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0011_alter_newlicenseapplication_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlicenseapplication',
            name='mini_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='mini_bar_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
