# Generated by Django 5.1.7 on 2026-09-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_license_application', '0012_newlicenseapplication_mini_bar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='road_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
