# Generated by Django 5.1.7 on 2025-10-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnaRequisitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisiton_number_of_permits', models.IntegerField()),
                ('our_ref_no', models.CharField(max_length=50)),
                ('requisition_date', models.DateTimeField()),
                ('lifted_from_distillery_name', models.CharField(max_length=255)),
                ('branch_address', models.CharField(max_length=500)),
                ('branch_purpose', models.CharField(max_length=255)),
                ('via_route', models.CharField(max_length=255)),
                ('govt_officer', models.CharField(max_length=255)),
                ('grain_ena_number', models.DecimalField(decimal_places=2, max_digits=18)),
                ('strength_from', models.DecimalField(decimal_places=2, max_digits=8)),
                ('strength_to', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('totalbl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('approval_date', models.DateTimeField()),
                ('lifted_from', models.CharField(max_length=255)),
                ('purpose_name', models.CharField(max_length=255)),
                ('check_post_name', models.CharField(max_length=255)),
                ('permit_nocount', models.CharField(max_length=500)),
                ('br_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('evc_file_path', models.CharField(max_length=500)),
                ('cancellation_br_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cancellation_br_number', models.CharField(max_length=50)),
                ('licensee_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ena_requisition_detail',
                'ordering': ['-created_at'],
            },
        ),
    ]
