# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnaRequisitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisiton_number_of_permits', models.IntegerField()),
                ('details_permits_number', models.CharField(blank=True, max_length=500, null=True)),
                ('our_ref_no', models.CharField(max_length=50)),
                ('requisition_date', models.DateTimeField()),
                ('lifted_from_distillery_name', models.CharField(max_length=255)),
                ('branch_purpose', models.CharField(max_length=255)),
                ('via_route', models.CharField(max_length=255)),
                ('grain_ena_number', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bulk_spirit_type', models.CharField(blank=True, default='', max_length=255)),
                ('strength', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('rejected_by_role', models.CharField(blank=True, default='', max_length=100)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('state', models.CharField(max_length=100)),
                ('status_code', models.CharField(default='RQ_00', max_length=50)),
                ('totalbl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('approval_date', models.DateTimeField()),
                ('lifted_from', models.CharField(max_length=255)),
                ('purpose_name', models.CharField(max_length=255)),
                ('check_post_name', models.CharField(max_length=255)),
                ('licensee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ena_requisition_detail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnaRevalidationActivationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_ref_no', models.CharField(db_index=True, max_length=50)),
                ('approval_date', models.DateTimeField()),
                ('activation_due_at', models.DateTimeField(db_index=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ena_revalidation_activation_schedule',
                'ordering': ['activation_due_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionBulkLiterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(db_index=True, max_length=50)),
                ('licensee_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('tanker_count', models.PositiveIntegerField(default=0)),
                ('tanker_details', models.JSONField(blank=True, default=list)),
                ('total_bulk_liter', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=150)),
                ('review_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reqution_bulk_liter_details',
                'ordering': ['-updated_at'],
            },
        ),
    ]
