# Generated by Django 5.1.7 on 2025-11-13 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enarequisitiondetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enarequisitiondetail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
