# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ena_requisition_details', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enarequisitiondetail',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ena_requisitions', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='enarequisitiondetail',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ena_requisitions', to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='enarevalidationactivationschedule',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revalidation_activation_schedule', to='ena_requisition_details.enarequisitiondetail'),
        ),
        migrations.AddField(
            model_name='requisitionbulkliterdetail',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_liter_detail', to='ena_requisition_details.enarequisitiondetail'),
        ),
    ]
