# Generated by Django 5.1.7 on 2025-11-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0002_enarequisitiondetail_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='br_amount',
        ),
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='cancellation_br_amount',
        ),
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='cancellation_br_number',
        ),
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='evc_file_path',
        ),
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='licensee_id',
        ),
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='permit_nocount',
        ),
        migrations.AddField(
            model_name='enarequisitiondetail',
            name='bulk_spirit_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enarequisitiondetail',
            name='strength',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
