# Generated by Django 5.1.7 on 2025-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0003_remove_enarequisitiondetail_br_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enarequisitiondetail',
            name='status_code',
            field=models.CharField(default='RQ_00', max_length=50),
        ),
    ]
