# Generated by Django 5.1.7 on 2025-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0004_enarequisitiondetail_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enarequisitiondetail',
            name='strength',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='enarequisitiondetail',
            name='strength_from',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='enarequisitiondetail',
            name='strength_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
