# Generated by Django 5.1.7 on 2025-11-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0005_alter_enarequisitiondetail_strength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='branch_address',
        ),
    ]
