# Generated by Django 5.1.7 on 2025-11-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0006_remove_enarequisitiondetail_branch_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='govt_officer',
        ),
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='strength_from',
        ),
        migrations.RemoveField(
            model_name='enarequisitiondetail',
            name='strength_to',
        ),
    ]
