# Generated by Django 5.1.7 on 2026-05-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0006_drop_bulk_liter_requisition_unique'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisitionbulkliterdetail',
            table='requition_bl_details',
        ),
        migrations.AlterModelTable(
            name='requisitionbulkliterreviewaudit',
            table='requition_bl_request',
        ),
    ]
