# Generated by Django 5.1.7 on 2026-08-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_requisition_details', '0007_alter_requisitionbulkliterdetail_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enarequisitiondetail',
            name='valid_up_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
