# Generated by Django 5.2.8 on 2026-08-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryBulkSpiritLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_bl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Secretary Bulk Spirit Log',
                'verbose_name_plural': 'Secretary Bulk Spirit Logs',
                'db_table': 'secretary_bulk_spirit_log',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
