# Generated by Django 5.1.7 on 2026-04-06 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelRegistration',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Submitted', max_length=30)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('licensee_details', models.JSONField(blank=True, default=dict)),
                ('product_details', models.JSONField(blank=True, default=dict)),
                ('packaging_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'label_registration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant'], name='label_reg_applicant_idx'), models.Index(fields=['created_at'], name='label_reg_created_at_idx')],
            },
        ),
    ]
