# Generated by Django 5.1.6 on 2025-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excise_district', models.CharField(max_length=100)),
                ('license_category', models.CharField(max_length=100)),
                ('excise_sub_division', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=100)),
                ('establishment_name', models.CharField(max_length=255)),
                ('mobile_number', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('license_no', models.BigIntegerField(blank=True, null=True)),
                ('initial_grant_date', models.DateField(blank=True, null=True)),
                ('renewed_from', models.DateField(blank=True, null=True)),
                ('valid_up_to', models.DateField(blank=True, null=True)),
                ('yearly_license_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('license_nature', models.CharField(max_length=100)),
                ('functioning_status', models.CharField(max_length=100)),
                ('modeof_operation', models.CharField(max_length=100)),
                ('site_sub_division', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('location_category', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('road_name', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_pan', models.CharField(max_length=20)),
                ('company_cin', models.CharField(max_length=30)),
                ('incorporation_date', models.DateField()),
                ('company_phone_number', models.BigIntegerField()),
                ('company_email_id', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('father_husband_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('pan', models.BigIntegerField()),
                ('member_mobile_number', models.BigIntegerField()),
                ('member_email_id', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'db_table': 'license_application',
            },
        ),
    ]
