# Generated by Django 5.1.7 on 2025-07-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseapplication', '0001_initial'),
        ('masters', '0002_alter_district_state_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='excise_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.district'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='excise_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.subdivision'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.licensecategory'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.licensetype'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='pan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.policestation'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='site_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_subdivisions', to='masters.subdivision'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['excise_district'], name='license_app_excise__a9c318_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['license_type'], name='license_app_license_ec78a8_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['excise_subdivision'], name='license_app_excise__d291fc_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseapplication',
            index=models.Index(fields=['current_stage'], name='license_app_current_87409b_idx'),
        ),
    ]
