# Generated by Django 5.2.1 on 2025-05-08 17:46

import licenseapplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='business_address',
            field=models.TextField(db_column='business_address'),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='business_address',
            new_name='businessAddress',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='email_id',
            field=models.EmailField(db_column='email_id', max_length=254),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='email_id',
            new_name='emailId',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='establishment_name',
            field=models.CharField(db_column='establishment_name', max_length=255),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='establishment_name',
            new_name='establishmentName',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='excise_district',
            field=models.CharField(db_column='excise_district', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='excise_district',
            new_name='exciseDistrict',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='excise_sub_division',
            field=models.CharField(db_column='excise_sub_division', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='excise_sub_division',
            new_name='exciseSubDivision',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='father_husband_name',
            field=models.CharField(db_column='father_husband_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='father_husband_name',
            new_name='fatherHusbandName',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='functioning_status',
            field=models.CharField(db_column='functioning_status', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='functioning_status',
            new_name='functioningStatus',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='initial_grant_date',
            field=models.DateField(blank=True, db_column='initial_grant_date', null=True),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='initial_grant_date',
            new_name='initialGrantDate',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_category',
            field=models.CharField(db_column='license_category', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='license_category',
            new_name='licenseCategory',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_nature',
            field=models.CharField(db_column='license_nature', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='license_nature',
            new_name='licenseNature',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_no',
            field=models.BigIntegerField(blank=True, db_column='license_no', null=True),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='license_no',
            new_name='licenseNo',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='license_type',
            field=models.CharField(db_column='license_type', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='license_type',
            new_name='licenseType',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='location_category',
            field=models.CharField(db_column='location_category', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='location_category',
            new_name='locationCategory',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='location_name',
            field=models.CharField(db_column='location_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='location_name',
            new_name='locationName',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='member_email_id',
            field=models.EmailField(db_column='member_email_id', max_length=254),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='member_email_id',
            new_name='memberEmailId',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='member_mobile_number',
            field=models.BigIntegerField(db_column='member_mobile_number'),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='member_mobile_number',
            new_name='memberMobileNumber',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='member_name',
            field=models.CharField(db_column='member_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='member_name',
            new_name='memberName',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='mobile_number',
            field=models.BigIntegerField(db_column='mobile_number'),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='mobile_number',
            new_name='mobileNumber',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='pin_code',
            field=models.IntegerField(db_column='pin_code'),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='pin_code',
            new_name='pinCode',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='police_station',
            field=models.CharField(db_column='police_station', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='police_station',
            new_name='policeStation',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='renewed_from',
            field=models.DateField(blank=True, db_column='renewed_from', null=True),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='renewed_from',
            new_name='renewedFrom',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='road_name',
            field=models.CharField(db_column='road_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='road_name',
            new_name='roadName',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='site_sub_division',
            field=models.CharField(db_column='site_sub_division', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='site_sub_division',
            new_name='siteSubDivision',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='valid_up_to',
            field=models.DateField(blank=True, db_column='valid_up_to', null=True),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='valid_up_to',
            new_name='validUpTo',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='ward_name',
            field=models.CharField(db_column='ward_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='ward_name',
            new_name='wardName',
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='yearly_license_fee',
            field=models.CharField(blank=True, db_column='yearly_license_fee', max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='yearly_license_fee',
            new_name='yearlyLicenseFee',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='company_cin',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='company_email_id',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='company_pan',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='company_phone_number',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='incorporation_date',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='modeof_operation',
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='companyAddress',
            field=models.TextField(blank=True, db_column='company_address', null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='companyCin',
            field=models.CharField(blank=True, db_column='company_cin', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='companyEmailId',
            field=models.EmailField(blank=True, db_column='company_email_id', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='companyName',
            field=models.CharField(blank=True, db_column='company_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='companyPan',
            field=models.CharField(blank=True, db_column='company_pan', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='companyPhoneNumber',
            field=models.BigIntegerField(blank=True, db_column='company_phone_number', null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='incorporationDate',
            field=models.DateField(blank=True, db_column='incorporation_date', null=True),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='modeofOperation',
            field=models.CharField(db_column='mode_of_operation', default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='latitude',
            field=models.CharField(blank=True, db_column='latitude', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='longitude',
            field=models.CharField(blank=True, db_column='longitude', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='pan',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='photo',
            field=models.ImageField(upload_to=licenseapplication.models.upload_document_path),
        ),
    ]
