# Generated by Django 5.1.4 on 2025-06-28 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenseapplication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplicationtransaction',
            name='forwarded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_by_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenseapplicationtransaction',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenseapplicationtransaction',
            name='license_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='licenseapplication.licenseapplication'),
        ),
        migrations.AddField(
            model_name='licenseapplicationtransaction',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objection',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenseapplication.licenseapplication'),
        ),
        migrations.AddField(
            model_name='objection',
            name='raised_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteenquiryreport',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_enquiry_report', to='licenseapplication.licenseapplication'),
        ),
    ]
