# Generated by Django 5.1.7 on 2025-11-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ena_distillery_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enaDistilleryTypes',
        ),
    ]
