# Generated by Django 5.1.7 on 2026-04-06 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquor_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(blank=True, db_column='license_id', help_text='Stable licensee identifier used to scope stock per establishment', max_length=100, null=True)),
                ('purpose_of_sale', models.CharField(choices=[('LOCAL', 'Local'), ('EXPORT', 'Export'), ('DEFENCE', 'Defence')], db_column='purpose_of_sale', default='LOCAL', help_text='Purpose of sale: Local, Export, or Defence', max_length=50)),
                ('current_stock', models.IntegerField(db_column='current_stock', default=0, help_text='Current stock quantity in units')),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('OVERSTOCKED', 'Overstocked')], db_column='status', default='IN_STOCK', help_text='Current stock status', max_length=20)),
                ('liquor_data_id', models.IntegerField(blank=True, db_column='liquor_data_id', help_text='Legacy reference id from liquor_data_details', null=True)),
                ('is_sync', models.IntegerField(db_column='is_sync', default=0, help_text='Sync flag (0 = not synced, 1 = synced)')),
                ('ex_factory_price_rs_per_case', models.DecimalField(db_column='ex_factory_price_rs_per_case', decimal_places=2, default=0, max_digits=15)),
                ('excise_duty_rs_per_case', models.DecimalField(db_column='excise_duty_rs_per_case', decimal_places=2, default=0, max_digits=15)),
                ('education_cess_rs_per_case', models.DecimalField(db_column='education_cess_rs_per_case', decimal_places=2, default=0, max_digits=15)),
                ('additional_excise_duty_rs_per_case', models.DecimalField(db_column='additional_excise_duty_rs_per_case', decimal_places=2, default=0, max_digits=15)),
                ('additional_excise_duty_12_5_percent_rs_per_case', models.DecimalField(db_column='additional_excise_duty_12_5_percent_rs_per_case', decimal_places=2, default=0, max_digits=15)),
                ('mrp_rs_per_bottle', models.DecimalField(db_column='mrp_rs_per_bottle', decimal_places=2, default=0, max_digits=15)),
                ('reorder_level', models.IntegerField(db_column='reorder_level', default=0, help_text='Minimum stock level before reordering')),
                ('max_capacity', models.IntegerField(db_column='max_capacity', default=0, help_text='Maximum storage capacity')),
                ('average_daily_usage', models.DecimalField(db_column='average_daily_usage', decimal_places=2, default=0, help_text='Average daily usage in units', max_digits=10)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False, help_text='Soft delete flag to prevent accidental data loss')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Timestamp when the record was soft deleted', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='deleted_by', help_text='User who performed the soft delete', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', help_text='Master brand (FK to master_brand_list.id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_warehouses', to='liquor_data.masterbrandlist')),
                ('capacity_size', models.ForeignKey(blank=True, db_column='capacity_size', help_text='Pack size (FK to master_liquor_category.id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_warehouses', to='liquor_data.masterliquorcategory')),
                ('factory', models.ForeignKey(blank=True, db_column='factory_id', help_text='Master factory (FK to master_factory_list.id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_warehouses', to='liquor_data.masterfactorylist')),
                ('liquor_type', models.ForeignKey(blank=True, db_column='liquor_type', help_text='Master liquor type (FK to master_liquor_type.id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_warehouses', to='liquor_data.masterliquortype')),
            ],
            options={
                'verbose_name': 'Brand Warehouse',
                'verbose_name_plural': 'Brand Warehouses',
                'db_table': 'brand_warehouse',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandWarehouseArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(blank=True, db_column='license_id', help_text='Stable licensee identifier used to scope arrivals per establishment', max_length=100, null=True)),
                ('reference_no', models.CharField(db_column='reference_no', help_text='Reference number from source system (e.g., Daily Register Ref No)', max_length=100)),
                ('source_type', models.CharField(choices=[('HOLOGRAM_REGISTER', 'Monthly Statement of Hologram'), ('MANUAL_ADJUSTMENT', 'Manual Stock Adjustment'), ('PRODUCTION', 'Production Entry'), ('TRANSFER', 'Stock Transfer')], db_column='source_type', default='HOLOGRAM_REGISTER', help_text='Source of the stock arrival', max_length=50)),
                ('quantity_added', models.IntegerField(db_column='quantity_added', help_text='Quantity added to stock')),
                ('previous_stock', models.IntegerField(db_column='previous_stock', help_text='Stock level before this arrival')),
                ('new_stock', models.IntegerField(db_column='new_stock', help_text='Stock level after this arrival')),
                ('arrival_date', models.DateTimeField(db_column='arrival_date', default=django.utils.timezone.now, help_text='Date and time of stock arrival')),
                ('notes', models.TextField(blank=True, db_column='notes', help_text='Additional notes about the arrival', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('brand_warehouse', models.ForeignKey(db_column='brand_warehouse_id', help_text='Related brand warehouse entry', on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='brand_warehouse.brandwarehouse')),
            ],
            options={
                'verbose_name': 'Brand Warehouse Arrival',
                'verbose_name_plural': 'Brand Warehouse Arrivals',
                'db_table': 'brand_warehouse_arrival',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='BrandWarehouseTpCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(db_column='reference_no', help_text='Reference number of the cancelled transit permit', max_length=100)),
                ('cancellation_date', models.DateTimeField(auto_now_add=True, db_column='cancellation_date', help_text='Date and time of cancellation')),
                ('cancelled_by', models.CharField(db_column='cancelled_by', help_text='User who cancelled the permit (e.g. OIC)', max_length=255)),
                ('quantity_cases', models.IntegerField(db_column='quantity_cases', default=0, help_text='Number of cases restored')),
                ('quantity_bottles', models.IntegerField(db_column='quantity_bottles', default=0, help_text='Number of bottles restored')),
                ('amount_refunded', models.DecimalField(db_column='amount_refunded', decimal_places=2, default=0, help_text='Amount refunded to the licensee wallet', max_digits=12)),
                ('reason', models.TextField(blank=True, db_column='reason', help_text='Reason for cancellation', null=True)),
                ('previous_stock', models.IntegerField(db_column='previous_stock', default=0, help_text='Stock before restoration')),
                ('new_stock', models.IntegerField(db_column='new_stock', default=0, help_text='Stock after restoration')),
                ('permit_date', models.DateField(blank=True, db_column='permit_date', help_text='Date of the original permit', null=True)),
                ('destination', models.CharField(blank=True, db_column='destination', help_text='Destination/Distributor Name', max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, db_column='vehicle_no', help_text='Vehicle Number', max_length=50, null=True)),
                ('depot_address', models.TextField(blank=True, db_column='depot_address', help_text='Depot/Destination Address', null=True)),
                ('brand_name', models.CharField(blank=True, db_column='brand_name', help_text='Name of the brand cancelled', max_length=255, null=True)),
                ('brand_warehouse', models.ForeignKey(db_column='brand_warehouse_id', help_text='Related brand warehouse entry', on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='brand_warehouse.brandwarehouse')),
            ],
            options={
                'verbose_name': 'Brand Warehouse TP Cancellation',
                'verbose_name_plural': 'Brand Warehouse TP Cancellations',
                'db_table': 'brand_warehouse_tp_cancellation',
                'ordering': ['-cancellation_date'],
            },
        ),
        migrations.CreateModel(
            name='BrandWarehouseUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(blank=True, db_column='license_id', help_text='Approved license id (NA/NLI) used for permit scoping', max_length=100, null=True)),
                ('permit_no', models.CharField(db_column='permit_no', help_text='Transit permit number', max_length=100)),
                ('date', models.DateField(db_column='date', help_text='Date of transit permit')),
                ('distributor', models.CharField(db_column='distributor', help_text='Distributor name', max_length=255)),
                ('depot_address', models.TextField(db_column='depot_address', help_text='Depot/destination address')),
                ('vehicle', models.CharField(db_column='vehicle', help_text='Vehicle number', max_length=50)),
                ('quantity', models.IntegerField(db_column='quantity', help_text='Quantity utilized/dispatched')),
                ('cases', models.IntegerField(db_column='cases', default=0, help_text='Number of cases')),
                ('bottles_per_case', models.IntegerField(db_column='bottles_per_case', default=12, help_text='Number of bottles per case')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_column='status', default='PENDING', help_text='Status of the transit permit', max_length=20)),
                ('approved_by', models.CharField(blank=True, db_column='approved_by', help_text='Name of the approving officer', max_length=255, null=True)),
                ('approval_date', models.DateTimeField(blank=True, db_column='approval_date', help_text='Date and time of approval', null=True)),
                ('previous_stock', models.IntegerField(db_column='previous_stock', default=0, help_text='Stock before deduction')),
                ('new_stock', models.IntegerField(db_column='new_stock', default=0, help_text='Stock after deduction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('brand_warehouse', models.ForeignKey(db_column='brand_warehouse_id', help_text='Related brand warehouse entry', on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='brand_warehouse.brandwarehouse')),
            ],
            options={
                'verbose_name': 'Brand Warehouse Utilization',
                'verbose_name_plural': 'Brand Warehouse Utilizations',
                'db_table': 'brand_warehouse_utilization',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(db_column='batch_reference', help_text='Production batch reference number (e.g., PROD-2024-001)', max_length=100, unique=True)),
                ('source_reference', models.CharField(blank=True, db_column='source_reference', help_text='Source reference number from Request Register Entry or Hologram Register', max_length=100, null=True)),
                ('production_date', models.DateField(db_column='production_date', default=django.utils.timezone.now, help_text='Date of production')),
                ('production_time', models.TimeField(db_column='production_time', default=django.utils.timezone.now, help_text='Time of production')),
                ('quantity_produced', models.IntegerField(db_column='quantity_produced', help_text='Quantity produced in this batch (in units/bottles)')),
                ('stock_before', models.IntegerField(db_column='stock_before', help_text='Stock level before this production')),
                ('stock_after', models.IntegerField(db_column='stock_after', help_text='Stock level after this production')),
                ('production_manager', models.CharField(db_column='production_manager', help_text='Name of the production manager/officer', max_length=255)),
                ('approved_by', models.CharField(blank=True, db_column='approved_by', help_text='Name of the approving officer', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_column='status', default='COMPLETED', help_text='Status of the production batch', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='notes', help_text='Additional notes about the production batch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('brand_warehouse', models.ForeignKey(db_column='brand_warehouse_id', help_text='Related brand warehouse entry', on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='brand_warehouse.brandwarehouse')),
            ],
            options={
                'verbose_name': 'Production Batch',
                'verbose_name_plural': 'Production Batches',
                'db_table': 'production_batch',
                'ordering': ['-production_date', '-production_time'],
            },
        ),
        migrations.AddIndex(
            model_name='brandwarehouse',
            index=models.Index(fields=['license_id'], name='brand_wareh_license_cbfbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouse',
            index=models.Index(fields=['factory'], name='brand_wareh_factory_5b7251_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouse',
            index=models.Index(fields=['liquor_type'], name='brand_wareh_liquor__9b0da1_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouse',
            index=models.Index(fields=['brand'], name='brand_wareh_brand_i_04431e_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouse',
            index=models.Index(fields=['status'], name='brand_wareh_status_792ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehousearrival',
            index=models.Index(fields=['brand_warehouse', 'arrival_date'], name='brand_wareh_brand_w_9c99cb_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehousearrival',
            index=models.Index(fields=['license_id'], name='brand_wareh_license_283944_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehousearrival',
            index=models.Index(fields=['reference_no'], name='brand_wareh_referen_213d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehousearrival',
            index=models.Index(fields=['source_type'], name='brand_wareh_source__7cfe86_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouseutilization',
            index=models.Index(fields=['license_id'], name='brand_wareh_license_b5d7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouseutilization',
            index=models.Index(fields=['permit_no'], name='brand_wareh_permit__0e0b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouseutilization',
            index=models.Index(fields=['date'], name='brand_wareh_date_433960_idx'),
        ),
        migrations.AddIndex(
            model_name='brandwarehouseutilization',
            index=models.Index(fields=['status'], name='brand_wareh_status_91f96b_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['brand_warehouse', 'production_date'], name='production__brand_w_8a77c4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['batch_reference'], name='production__batch_r_79bb29_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['status'], name='production__status_9fdff2_idx'),
        ),
    ]
