# Generated by Django 5.1.7 on 2026-05-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_data', '0002_rename_masterliquorcategory_to_masterliquorcapacity'),
        ('brand_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandwarehouse',
            name='capacity_size',
            field=models.ForeignKey(
                blank=True,
                db_column='capacity_size',
                help_text='Pack size (FK to master_liquor_capacity.id)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='brand_warehouses',
                to='liquor_data.masterliquorcapacity',
            ),
        ),
    ]

