# Generated by Django 5.1.7 on 2026-09-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_warehouse', '0002_update_capacity_size_fk_to_masterliquorcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandwarehouse',
            name='bottling_fee',
            field=models.DecimalField(db_column='bottling_fee', decimal_places=2, default=0, help_text='Bottling fee (Rs/Case)', max_digits=15),
        ),
    ]
