# Generated by Django 5.1.7 on 2026-06-01 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_alter_supplychaintimerconfig_delay_unit'),
        ('workflow', '0006_seed_license_renewal_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseApplication',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('old_license_id', models.CharField(blank=True, max_length=60, null=True)),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, db_column='applicant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_renewal_applications', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, db_column='current_stage_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_renewal_applications', to='workflow.workflowstage')),
                ('license_category', models.ForeignKey(db_column='license_category_id', on_delete=django.db.models.deletion.PROTECT, to='core.licensecategory')),
                ('license_sub_category', models.ForeignKey(blank=True, db_column='license_sub_category_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.licensesubcategory')),
                ('source_content_type', models.ForeignKey(blank=True, db_column='source_content_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('workflow', models.ForeignKey(blank=True, db_column='workflow_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_renewal_applications', to='workflow.workflow')),
            ],
            options={
                'db_table': 'license_renewal_application',
                'indexes': [models.Index(fields=['applicant'], name='license_ren_applica_33d8ac_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='license_ren_source__cca73e_idx')],
            },
        ),
    ]
