# Generated by Django 5.2.8 on 2026-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_renewal_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='is_license_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='is_security_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
