# Generated by Django 5.2.8 on 2026-06-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_renewal_application', '0002_licenseapplication_is_license_fee_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='source_object_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
