# Generated by Django 5.2.8 on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


def backfill_workflow_and_stage(apps, schema_editor):
    Workflow = apps.get_model("workflow", "Workflow")
    WorkflowStage = apps.get_model("workflow", "WorkflowStage")
    LicenseRenewalApplication = apps.get_model("license_renewal_application", "LicenseApplication")

    wf = (
        Workflow.objects.filter(name="License Renewal Application").order_by("id").first()
        or Workflow.objects.filter(name="License Approval").order_by("id").first()
    )
    if not wf:
        return

    initial = WorkflowStage.objects.filter(workflow_id=wf.id, is_initial=True).order_by("id").first()
    LicenseRenewalApplication.objects.filter(workflow__isnull=True).update(workflow_id=wf.id)
    if initial:
        LicenseRenewalApplication.objects.filter(current_stage__isnull=True, workflow_id=wf.id).update(
            current_stage_id=initial.id
        )


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0006_seed_license_renewal_workflow"),
        ("license_renewal_application", "0005_rename_table_to_license_renewal_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseapplication",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                db_column="workflow_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="license_renewal_applications",
                to="workflow.workflow",
            ),
        ),
        migrations.AddField(
            model_name="licenseapplication",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                db_column="current_stage_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="license_renewal_applications",
                to="workflow.workflowstage",
            ),
        ),
        migrations.AddField(
            model_name="licenseapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="licenseapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(backfill_workflow_and_stage, migrations.RunPython.noop),
    ]

