# Generated by Django 5.1.7 on 2026-04-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSpiritType',
            fields=[
                ('sprit_id', models.AutoField(primary_key=True, serialize=False)),
                ('bulk_spirit_kind_type', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('price_bl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ena_bulk_spirit',
                'ordering': ['sprit_id'],
            },
        ),
    ]
