# Generated by Django 5.1.7 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('brand_type', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('application_year', models.CharField(default='2025-2026', max_length=9)),
                ('company_name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=10)),
                ('office_address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('factory_address', models.TextField()),
                ('pin_code', models.PositiveIntegerField()),
                ('company_mobile_number', models.BigIntegerField()),
                ('company_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_name', models.CharField(max_length=255)),
                ('member_designation', models.CharField(max_length=255)),
                ('member_mobile_number', models.BigIntegerField()),
                ('member_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_address', models.TextField()),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_remarks', models.TextField(blank=True, null=True)),
                ('undertaking', models.FileField(upload_to='company_registration/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_registration',
                'ordering': ['-created_at'],
            },
        ),
    ]
