# Generated by Django 5.1.7 on 2026-02-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0004_rename_workflowobjection_objection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('brand_type', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('application_year', models.CharField(default='2025-2026', max_length=9)),
                ('company_name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=10)),
                ('office_address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('factory_address', models.TextField()),
                ('pin_code', models.PositiveIntegerField()),
                ('company_mobile_number', models.BigIntegerField()),
                ('company_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_name', models.CharField(max_length=255)),
                ('member_designation', models.CharField(max_length=255)),
                ('member_mobile_number', models.BigIntegerField()),
                ('member_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_address', models.TextField()),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_remarks', models.TextField(blank=True, null=True)),
                ('undertaking', models.FileField(upload_to='company_registration/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_registrations', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_registrations', to='workflow.workflowstage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_registrations', to='workflow.workflow')),
            ],
            options={
                'db_table': 'company_registration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='company_reg_company_99a91e_idx'), models.Index(fields=['pan'], name='company_reg_pan_64f701_idx'), models.Index(fields=['application_year'], name='company_reg_applica_97382f_idx'), models.Index(fields=['current_stage'], name='company_reg_current_55de29_idx'), models.Index(fields=['applicant'], name='company_reg_applica_d75647_idx')],
            },
        ),
    ]
