# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_registration', '0002_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_registrations', to='workflow.workflowstage'),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_registrations', to='workflow.workflow'),
        ),
        migrations.AddIndex(
            model_name='companyregistration',
            index=models.Index(fields=['company_name'], name='company_reg_company_99a91e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyregistration',
            index=models.Index(fields=['pan'], name='company_reg_pan_64f701_idx'),
        ),
        migrations.AddIndex(
            model_name='companyregistration',
            index=models.Index(fields=['application_year'], name='company_reg_applica_97382f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyregistration',
            index=models.Index(fields=['current_stage'], name='company_reg_current_55de29_idx'),
        ),
        migrations.AddIndex(
            model_name='companyregistration',
            index=models.Index(fields=['applicant'], name='company_reg_applica_d75647_idx'),
        ),
    ]
