# Generated by Django 5.2.8 on 2026-06-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyregistration',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='payment_id',
        ),
    ]
