# Generated by Django 5.2.8 on 2026-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0004_remove_companyregistration_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='deed_of_partnership',
            field=models.FileField(blank=True, null=True, upload_to='company_registration/'),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='excise_license',
            field=models.FileField(blank=True, null=True, upload_to='company_registration/'),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='memorandum_of_association',
            field=models.FileField(blank=True, null=True, upload_to='company_registration/'),
        ),
    ]
