# Generated by Django 5.1.7 on 2026-06-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0005_companyregistration_deed_of_partnership_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companyregistration',
            name='company_reg_pan_64f701_idx',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='pan',
        ),
    ]
