# Generated by Django 5.1.7 on 2026-06-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0006_remove_pan_and_office_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
