# Generated by Django 5.1.7 on 2026-08-04 07:21

from models.transactional.company_registration.models import upload_company_registration_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0007_companyregistration_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='deed_of_partnership',
            field=models.FileField(blank=True, null=True, upload_to=upload_company_registration_file_path),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='excise_license',
            field=models.FileField(blank=True, null=True, upload_to=upload_company_registration_file_path),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='memorandum_of_association',
            field=models.FileField(blank=True, null=True, upload_to=upload_company_registration_file_path),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='undertaking',
            field=models.FileField(upload_to=upload_company_registration_file_path),
        ),
    ]
