# Generated by Django 5.1.7 on 2026-07-01 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_whatscurrent'),
        ('license', '0004_alter_license_source_type'),
        ('workflow', '0006_seed_license_renewal_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPermitApplication',
            fields=[
                ('application_id', models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=9)),
                ('permission_duration', models.CharField(choices=[('per_annum', 'Per Annum'), ('per_day', 'Per Day')], default='per_annum', max_length=20)),
                ('permission_date', models.DateField(blank=True, null=True)),
                ('is_fee_paid', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, related_name='special_permit_applications', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, db_column='current_stage_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_permit_applications', to='workflow.workflowstage')),
                ('excise_district', models.ForeignKey(db_column='excise_district_id', on_delete=django.db.models.deletion.PROTECT, related_name='special_permit_applications', to='core.district')),
                ('license', models.ForeignKey(db_column='license_id', on_delete=django.db.models.deletion.PROTECT, related_name='special_permit_applications', to='license.license')),
                ('license_category', models.ForeignKey(db_column='license_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='special_permit_applications', to='core.licensecategory')),
                ('license_sub_category', models.ForeignKey(blank=True, db_column='license_sub_category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_permit_applications', to='core.licensesubcategory')),
                ('workflow', models.ForeignKey(blank=True, db_column='workflow_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_permit_applications', to='workflow.workflow')),
            ],
            options={
                'db_table': 'special_permit_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license'], name='special_per_license_3e1471_idx'), models.Index(fields=['applicant'], name='special_per_applica_e545e2_idx'), models.Index(fields=['excise_district'], name='special_per_excise__8f97fc_idx'), models.Index(fields=['license_category'], name='special_per_license_b6cea5_idx'), models.Index(fields=['current_stage'], name='special_per_current_2d265f_idx'), models.Index(fields=['financial_year'], name='special_per_financi_82241e_idx'), models.Index(fields=['permission_duration'], name='special_per_permiss_652c49_idx')],
            },
        ),
    ]
