# Generated by Django 5.2.8 on 2026-07-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_permit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9, unique=True)),
                ('allowed_dates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_dry_day_calendar',
                'ordering': ['-financial_year'],
            },
        ),
        migrations.AddField(
            model_name='specialpermitapplication',
            name='selected_dates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
