# Generated by Django 5.2.8 on 2026-07-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_permit', '0002_masterdryday_specialpermitapplication_selected_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialpermitapplication',
            name='permission_date',
        ),
    ]
