# Generated by Django 5.1.7 on 2025-07-24 06:36

import auth.user.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(error_messages={'blank': 'First name cannot be blank.'}, max_length=50, validators=[auth.user.validators.validate_name])),
                ('middle_name', models.CharField(blank=True, max_length=50, validators=[auth.user.validators.validate_name])),
                ('last_name', models.CharField(error_messages={'blank': 'Last name cannot be blank.'}, max_length=50, validators=[auth.user.validators.validate_name])),
                ('phone_number', models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=10, unique=True, validators=[auth.user.validators.validate_phone_number])),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(db_column='district', on_delete=django.db.models.deletion.CASCADE, to='core.district', to_field='district_code')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles.role')),
                ('subdivision', models.ForeignKey(db_column='subdivision', on_delete=django.db.models.deletion.CASCADE, to='core.subdivision', to_field='subdivision_code')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'custom_user',
                'ordering': ['-date_joined'],
            },
        ),
    ]
