# Generated by Django 5.2.8 on 2026-08-22 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_license_source_type'),
        ('new_license_application', '0012_newlicenseapplication_mini_bar_and_more'),
        ('user', '0003_alter_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oicofficerassignment',
            name='assignment_type',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('distributor', 'Distributor')], db_index=True, default='manufacturing', max_length=50),
        ),
        migrations.AddField(
            model_name='oicofficerassignment',
            name='distributor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_distributor_oic_officers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oicofficerassignment',
            name='approved_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oic_officers', to='new_license_application.newlicenseapplication'),
        ),
        migrations.AlterField(
            model_name='oicofficerassignment',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oic_officers', to='license.license'),
        ),
        migrations.AlterField(
            model_name='oicofficerassignment',
            name='licensee_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
