# Generated by Django 5.1.7 on 2026-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=50)),
                ('dlt_entity_id', models.CharField(max_length=50)),
                ('dlt_template_id', models.CharField(default='1007722920127309405', max_length=50)),
                ('base_url', models.URLField(default='https://smsgw.sms.gov.in/failsafe/MLink')),
                ('message_template', models.TextField(default='From eAbkari, GoSK :\nYour OTP is {otp}\n Thanks')),
                ('verify_ssl', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Service Config',
                'verbose_name_plural': 'SMS Service Configs',
                'db_table': 'sms_service_config',
                'ordering': ['-updated_at'],
            },
        ),
    ]
