# Generated by Django 5.1.6 on 2025-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorateAndDistrictOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrievanceRedressalOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('office_level', models.CharField(choices=[('Head Quarter', 'Head Quarter'), ('Permit Section', 'Permit Section'), ('Administration Section', 'Administration Section'), ('Accounts Section', 'Accounts Section'), ('IT Cell', 'IT Cell')], default='Excise Head Office', max_length=255)),
                ('office_sub_level', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodalOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Excise Department', max_length=255)),
                ('cell', models.CharField(default='IT Cell', max_length=255)),
                ('phone_number', models.CharField(default='(035) 9220-3963', max_length=20)),
                ('email', models.EmailField(default='helpdesk-excise@sikkim.gov.in', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PublicInformationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(choices=[('HQ', 'Headquarter'), ('District', 'District')], default='HQ', max_length=10)),
                ('officer_name_headquarter', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_headquarter', models.CharField(blank=True, max_length=255, null=True)),
                ('address_headquarter', models.TextField(blank=True, null=True)),
                ('phone_number_headquarter', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_name_district', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_district', models.CharField(blank=True, max_length=255, null=True)),
                ('address_district', models.TextField(blank=True, null=True)),
                ('phone_number_district', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
