# Generated by Django 5.1.6 on 2025-04-01 08:34

import contact_us.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='designation',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_designation]),
        ),
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='email',
            field=models.EmailField(max_length=254, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='name',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='designation',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_designation]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='email',
            field=models.EmailField(max_length=254, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='name',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='office_level',
            field=models.CharField(choices=[('Head Quarter', 'Head Quarter'), ('Permit Section', 'Permit Section'), ('Administration Section', 'Administration Section'), ('Accounts Section', 'Accounts Section'), ('IT Cell', 'IT Cell')], default='Excise Head Office', max_length=255, validators=[contact_us.validators.validate_office_level]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='office_sub_level',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='cell',
            field=models.CharField(default='IT Cell', max_length=255, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='department',
            field=models.CharField(default='Excise Department', max_length=255, validators=[contact_us.validators.validate_department_name]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='email',
            field=models.EmailField(default='helpdesk-excise@sikkim.gov.in', max_length=254, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='phone_number',
            field=models.CharField(default='(035) 9220-3963', max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='address_district',
            field=models.TextField(blank=True, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='address_headquarter',
            field=models.TextField(blank=True, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='designation',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_designation]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='designation_district',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[contact_us.validators.validate_designation]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='designation_headquarter',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[contact_us.validators.validate_designation]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='email',
            field=models.EmailField(max_length=254, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='location',
            field=models.CharField(choices=[('HQ', 'Headquarter'), ('District', 'District')], default='HQ', max_length=10, validators=[contact_us.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='name',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='officer_name_district',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='officer_name_headquarter',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='phone_number_district',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='phone_number_headquarter',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[contact_us.validators.validate_phone_number]),
        ),
    ]
