# Generated by Django 5.2.1 on 2025-05-08 17:46

import contact_us.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorateanddistrictofficials',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='grievanceredressalofficer',
            name='office_level',
        ),
        migrations.RemoveField(
            model_name='grievanceredressalofficer',
            name='office_sub_level',
        ),
        migrations.RemoveField(
            model_name='grievanceredressalofficer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='nodalofficer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='address_headquarter',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='designation_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='designation_headquarter',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='officer_name_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='officer_name_headquarter',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='phone_number_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='phone_number_headquarter',
        ),
        migrations.AddField(
            model_name='directorateanddistrictofficials',
            name='phoneNumber',
            field=models.CharField(blank=True, db_column='phone_number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grievanceredressalofficer',
            name='officeLevel',
            field=models.CharField(choices=[('Head Quarter', 'Head Quarter'), ('Permit Section', 'Permit Section'), ('Administration Section', 'Administration Section'), ('Accounts Section', 'Accounts Section'), ('IT Cell', 'IT Cell')], db_column='office_level', default='Excise Head Office', max_length=255, validators=[contact_us.validators.validate_office_level]),
        ),
        migrations.AddField(
            model_name='grievanceredressalofficer',
            name='officeSubLevel',
            field=models.CharField(blank=True, db_column='office_sub_level', max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AddField(
            model_name='grievanceredressalofficer',
            name='phoneNumber',
            field=models.CharField(db_column='phone_number', default='00000000000', max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='nodalofficer',
            name='phoneNumber',
            field=models.CharField(db_column='phone_number', default='(035) 9220-3963', max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='publicinformationofficer',
            name='address',
            field=models.CharField(default='Not Available', max_length=255),
        ),
        migrations.AddField(
            model_name='publicinformationofficer',
            name='locationType',
            field=models.CharField(choices=[('Headquarter', 'Headquarter'), ('District', 'District'), ('unset', 'unset')], db_column='location_type', default='unset', max_length=20),
        ),
        migrations.AddField(
            model_name='publicinformationofficer',
            name='phoneNumber',
            field=models.CharField(db_column='phone_number', default='00000000000', max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='designation',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_designation]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='email',
            field=models.EmailField(max_length=254, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='name',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='cell',
            field=models.CharField(default='IT Cell', max_length=255, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='department',
            field=models.CharField(default='Excise Department', max_length=255, validators=[contact_us.validators.validate_department_name]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='email',
            field=models.EmailField(default='helpdesk-excise@sikkim.gov.in', max_length=254, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='designation',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_designation]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='email',
            field=models.EmailField(max_length=254, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='name',
            field=models.CharField(max_length=255, validators=[contact_us.validators.validate_non_empty]),
        ),
    ]
