# Generated by Django 5.1.7 on 2025-07-07 05:03

import contact_us.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='office_level',
            field=models.CharField(choices=[('Head Quarter', 'Head Quarter'), ('Permit Section', 'Permit Section'), ('Administration Section', 'Administration Section'), ('Field Section', 'Field Section'), ('Accounts Section', 'Accounts Section'), ('IT Cell', 'IT Cell')], default='Excise Head Office', max_length=255, validators=[contact_us.validators.validate_office_level]),
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='cell',
            field=models.CharField(default='IT Cell', max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
    ]
