# Generated by Django 5.2 on 2025-04-18 09:23

import contact_us.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_directorateanddistrictofficials_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='office_level',
            field=models.CharField(choices=[('Head Quarter', 'Head Quarter'), ('Permit Section', 'Permit Section'), ('Administration Section', 'Administration Section'), ('Accounts Section', 'Accounts Section'), ('IT Cell', 'IT Cell')], db_column='office_level', default='Excise Head Office', max_length=255, validators=[contact_us.validators.validate_office_level]),
        ),
        migrations.RenameField(
            model_name='grievanceredressalofficer',
            old_name='office_level',
            new_name='officeLevel',
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='office_sub_level',
            field=models.CharField(blank=True, db_column='office_sub_level', max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
        migrations.RenameField(
            model_name='grievanceredressalofficer',
            old_name='office_sub_level',
            new_name='officeSubLevel',
        ),
        migrations.AlterField(
            model_name='grievanceredressalofficer',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.RenameField(
            model_name='grievanceredressalofficer',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='nodalofficer',
            name='phone_number',
            field=models.CharField(db_column='phone_number', default='(035) 9220-3963', max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.RenameField(
            model_name='nodalofficer',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=20, validators=[contact_us.validators.validate_phone_number]),
        ),
        migrations.RenameField(
            model_name='publicinformationofficer',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='directorateanddistrictofficials',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='address_headquarter',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='designation_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='designation_headquarter',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='officer_name_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='officer_name_headquarter',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='phone_number_district',
        ),
        migrations.RemoveField(
            model_name='publicinformationofficer',
            name='phone_number_headquarter',
        ),
        migrations.AddField(
            model_name='directorateanddistrictofficials',
            name='phoneNumber',
            field=models.CharField(blank=True, db_column='phone_number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publicinformationofficer',
            name='address',
            field=models.CharField(default='Not Available', max_length=255),
        ),
        migrations.AddField(
            model_name='publicinformationofficer',
            name='locationType',
            field=models.CharField(choices=[('Headquarter', 'Headquarter'), ('District', 'District'), ('unset', 'unset')], db_column='location_type', default='unset', max_length=20),
        ),
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[contact_us.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='directorateanddistrictofficials',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publicinformationofficer',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
