# Generated by Django 5.1.7 on 2025-06-24 08:44

import contact_us.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_directorateanddistrictofficials_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodalofficer',
            name='cell',
            field=models.CharField(default='IT Cell', max_length=255, null=True, validators=[contact_us.validators.validate_non_empty]),
        ),
    ]
