# Generated by Django 5.1.7 on 2025-11-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiquorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='slno', null=True)),
                ('manufacturing_unit_name', models.CharField(blank=True, db_column='manufacturingunitname', max_length=255, null=True)),
                ('brand_owner', models.CharField(blank=True, db_column='brandowner', max_length=255, null=True)),
                ('liquor_type', models.CharField(blank=True, db_column='liquortype', max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, db_column='brandname', max_length=255, null=True)),
                ('pack_size_ml', models.IntegerField(blank=True, db_column='packsize_ml', null=True)),
                ('purpose_of_sale', models.CharField(blank=True, db_column='purposeofsale', max_length=255, null=True)),
                ('ex_factory_price_rs_per_case', models.DecimalField(blank=True, db_column='exfactoryprice_rspercase', decimal_places=2, max_digits=15, null=True)),
                ('excise_duty_rs_per_case', models.DecimalField(blank=True, db_column='exciseduty_rspercase', decimal_places=2, max_digits=15, null=True)),
                ('education_cess_rs_per_case', models.DecimalField(blank=True, db_column='educationcess_rspercase', decimal_places=2, max_digits=15, null=True)),
                ('additional_excise_duty_rs_per_case', models.DecimalField(blank=True, db_column='additionalexciseduty_rspercase', decimal_places=2, max_digits=15, null=True)),
                ('additional_excise_duty_12_5_percent_rs_per_case', models.DecimalField(blank=True, db_column='additionalexciseduty_12_5percent_rspercase', decimal_places=2, max_digits=15, null=True)),
                ('mrp_rs_per_bottle', models.DecimalField(blank=True, db_column='mrp_rsperbottle', decimal_places=2, max_digits=15, null=True)),
                ('bottling_fee_rs_per_case', models.DecimalField(blank=True, db_column='bottlingfee_rspercase', decimal_places=2, max_digits=15, null=True)),
                ('export_fee_rs_per_case', models.DecimalField(blank=True, db_column='exportfee_rspercase', decimal_places=2, max_digits=15, null=True)),
                ('licensee_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Liquor Data',
                'verbose_name_plural': 'Liquor Data',
                'db_table': 'liquor_data_details',
                'ordering': ['id'],
            },
        ),
    ]
