# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, db_column='sl_no', null=True)),
                ('manufacturing_unit_name', models.CharField(blank=True, db_column='manufacturing_unit_name', max_length=255, null=True)),
                ('brand_owner', models.CharField(blank=True, db_column='brand_owner', max_length=255, null=True)),
                ('liquor_type', models.CharField(blank=True, db_column='liquor_type', max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, db_column='brand_name', max_length=255, null=True)),
                ('pack_size_ml', models.IntegerField(blank=True, db_column='pack_size_ml', null=True)),
                ('purpose_of_sale', models.CharField(blank=True, db_column='purpose_of_sale', max_length=255, null=True)),
                ('ex_factory_price_rs_per_case', models.DecimalField(blank=True, db_column='ex_factory_price_rs_per_case', decimal_places=2, max_digits=15, null=True)),
                ('excise_duty_rs_per_case', models.DecimalField(blank=True, db_column='excise_duty_rs_per_case', decimal_places=2, max_digits=15, null=True)),
                ('education_cess_rs_per_case', models.DecimalField(blank=True, db_column='education_cess_rs_per_case', decimal_places=2, max_digits=15, null=True)),
                ('additional_excise_duty_rs_per_case', models.DecimalField(blank=True, db_column='additional_excise_duty_rs_per_case', decimal_places=2, max_digits=15, null=True)),
                ('additional_excise_duty_12_5_percent_rs_per_case', models.DecimalField(blank=True, db_column='additional_excise_duty_12_5_percent_rs_per_case', decimal_places=2, max_digits=15, null=True)),
                ('mrp_rs_per_bottle', models.DecimalField(blank=True, db_column='mrp_rs_per_bottle', decimal_places=2, max_digits=15, null=True)),
                ('bottling_fee_rs_per_case', models.DecimalField(blank=True, db_column='bottling_fee_rs_per_case', decimal_places=2, max_digits=15, null=True)),
                ('export_fee_rs_per_case', models.DecimalField(blank=True, db_column='export_fee_rs_per_case', decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Liquor Data',
                'verbose_name_plural': 'Liquor Data',
                'db_table': 'liquor_data_details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MasterBottleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_type', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sync', models.IntegerField(db_column='is_sync', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Bottle Type',
                'verbose_name_plural': 'Master Bottle Types',
                'db_table': 'master_bottle_type',
                'ordering': ['bottle_type'],
            },
        ),
        migrations.CreateModel(
            name='MasterLiquorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_ml', models.IntegerField(db_column='size_ml', unique=True)),
                ('is_sync', models.IntegerField(db_column='is_sync', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Master Liquor Category',
                'verbose_name_plural': 'Master Liquor Categories',
                'db_table': 'master_liquor_category',
                'ordering': ['size_ml'],
            },
        ),
        migrations.CreateModel(
            name='MasterLiquorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_type', models.CharField(db_column='liquor_type', max_length=100, unique=True)),
                ('is_sync', models.IntegerField(db_column='is_sync', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Master Liquor Type',
                'verbose_name_plural': 'Master Liquor Types',
                'db_table': 'master_liquor_type',
                'ordering': ['liquor_type'],
            },
        ),
        migrations.CreateModel(
            name='MasterFactoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(db_column='factory_name', max_length=255, unique=True)),
                ('source_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_sync', models.IntegerField(db_column='is_sync', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Master Factory',
                'verbose_name_plural': 'Master Factories',
                'db_table': 'master_factory_list',
                'ordering': ['factory_name'],
            },
        ),
        migrations.CreateModel(
            name='MasterBrandList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_column='brand_name', max_length=255, unique=True)),
                ('is_sync', models.IntegerField(db_column='is_sync', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('factory', models.ForeignKey(blank=True, db_column='factory_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='liquor_data.masterfactorylist')),
                ('liquor_type', models.ForeignKey(blank=True, db_column='liquor_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='liquor_data.masterliquortype')),
            ],
            options={
                'verbose_name': 'Master Brand',
                'verbose_name_plural': 'Master Brands',
                'db_table': 'master_brand_list',
                'ordering': ['brand_name'],
            },
        ),
    ]
