# Generated by Django 5.1.7 on 2026-05-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterLiquorCategory',
            new_name='MasterLiquorCapacity',
        ),
        migrations.AlterModelTable(
            name='masterliquorcapacity',
            table='master_liquor_capacity',
        ),
    ]

