# Generated by Django 5.1.7 on 2026-05-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_data', '0002_rename_masterliquorcategory_to_masterliquorcapacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterliquorcapacity',
            options={'ordering': ['size_ml'], 'verbose_name': 'Master Liquor Capacity', 'verbose_name_plural': 'Master Liquor Capacities'},
        ),
    ]
