# Generated by Django 5.1.7 on 2025-08-18 07:49

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_add', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of app labels with create permission', size=None)),
                ('can_update', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of app labels with update permission', size=None)),
                ('can_delete', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of app labels with delete permission', size=None)),
                ('can_view', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of app labels with view permission', size=None)),
                ('role_precedence', models.IntegerField(default=0, help_text='Higher number = higher privileges', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
            ],
            options={
                'verbose_name': 'RBAC Role',
                'verbose_name_plural': 'RBAC Roles',
                'db_table': 'roles',
                'ordering': ['-role_precedence'],
            },
        ),
    ]
