# Generated by Django 5.1.7 on 2025-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ena_cancellation_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enacancellationdetail',
            name='strength_from',
        ),
        migrations.RemoveField(
            model_name='enacancellationdetail',
            name='strength_to',
        ),
        migrations.AddField(
            model_name='enacancellationdetail',
            name='bulk_spirit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enacancellationdetail',
            name='status_code',
            field=models.CharField(default='CN_00', max_length=50),
        ),
        migrations.AddField(
            model_name='enacancellationdetail',
            name='strength',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
