# Generated by Django 5.1.4 on 2025-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('company_registration_access', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read & Write'), ('none', 'None')], default='none', max_length=10, verbose_name='Company Registration Access')),
                ('contact_us_access', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read & Write'), ('none', 'None')], default='none', max_length=10, verbose_name='Contact Us Access')),
                ('license_application_access', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read & Write'), ('none', 'None')], default='none', max_length=10, verbose_name='License Application Access')),
                ('masters_access', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read & Write'), ('none', 'None')], default='none', max_length=10, verbose_name='Masters Access')),
                ('roles_access', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read & Write'), ('none', 'None')], default='none', max_length=10, verbose_name='Roles Access')),
                ('salesman_barman_registration_access', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read & Write'), ('none', 'None')], default='none', max_length=10, verbose_name='Salesman/Barman Access')),
                ('user_access', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read & Write'), ('none', 'None')], default='none', max_length=10, verbose_name='User Access')),
            ],
        ),
    ]
