# Generated by Django 5.1.7 on 2026-04-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMlInCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml', models.IntegerField(db_column='ml', unique=True)),
                ('pieces_in_case', models.IntegerField(db_column='pieces_in_case')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand ML in Cases',
                'verbose_name_plural': 'Brand ML in Cases',
                'db_table': 'brand_ml_in_cases',
                'unique_together': {('ml', 'pieces_in_case')},
            },
        ),
    ]
