# Generated by Django 5.1.7 on 2025-07-14 05:39

import django.db.models.deletion
from models.masters.core.validators import (
    validate_name,
    validate_name_extended,
    )
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30, validators=[validate_name])),
                ('district_code', models.IntegerField(default=117, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_district',
            },
        ),
        migrations.CreateModel(
            name='LicenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_category', models.CharField(help_text='Name of license category', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'License Categories',
                'db_table': 'masters_licensecategory',
            },
        ),
        migrations.CreateModel(
            name='LicenseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200)),
            ],
            options={
                'db_table': 'masters_licensetitle',
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(help_text='Type of license', max_length=200)),
            ],
            options={
                'db_table': 'masters_licensetype',
            },
        ),
        migrations.CreateModel(
            name='LicenseSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200, validators=[validate_name_extended])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.licensecategory')),
            ],
            options={
                'db_table': 'masters_licensesubcategory',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=100, validators=[validate_name_extended])),
                ('road_type', models.CharField(choices=[('NH', 'National Highway'), ('SH', 'State Highway'), ('LINK ROAD', 'Link Road')], default='NH', max_length=10)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='core.district', to_field='district_code')),
            ],
            options={
                'db_table': 'masters_road',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Sikkim', max_length=50)),
                ('state_code', models.IntegerField(default=11, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_state',
                'constraints': [models.UniqueConstraint(fields=('state', 'state_code'), name='unique_state_identifier')],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state_code',
            field=models.ForeignKey(db_column='state_code', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.state', to_field='state_code'),
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(blank=True, max_length=30, null=True, validators=[validate_name])),
                ('subdivision_code', models.IntegerField(default=1001, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district_code', models.ForeignKey(db_column='district_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='core.district', to_field='district_code')),
            ],
            options={
                'db_table': 'masters_subdivision',
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.CharField(blank=True, max_length=30, null=True, validators=[validate_name])),
                ('police_station_code', models.IntegerField(default=11999, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subdivision_code', models.ForeignKey(db_column='subdivision_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='core.subdivision', to_field='subdivision_code')),
            ],
            options={
                'db_table': 'masters_policestation',
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('state_code', 'district_code'), name='unique_district_code_per_state'),
        ),
        migrations.AddConstraint(
            model_name='subdivision',
            constraint=models.UniqueConstraint(fields=('district_code', 'subdivision_code'), name='unique_subdivision_code_per_district'),
        ),
    ]
