# Generated by Django 5.1.7 on 2026-04-06 08:24

from models.masters.core.validators import validate_name, validate_name_extended
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30, validators=[validate_name])),
                ('district_code', models.IntegerField(default=225, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_district',
            },
        ),
        migrations.CreateModel(
            name='LicenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_category', models.CharField(help_text='Name of license category', max_length=200)),
                ('old_license_cat_code', models.IntegerField(blank=True, db_index=True, help_text='Legacy license category code used in old system', null=True)),
            ],
            options={
                'verbose_name_plural': 'License Categories',
                'db_table': 'masters_licensecategory',
            },
        ),
        migrations.CreateModel(
            name='LicenseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renewal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'license_fee',
            },
        ),
        migrations.CreateModel(
            name='LicenseSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200, validators=[validate_name_extended])),
                ('old_license_cat_code', models.IntegerField(blank=True, db_index=True, help_text='Legacy license category code used in old system', null=True)),
                ('old_license_scat_code', models.IntegerField(blank=True, db_index=True, help_text='Legacy license subcategory code used in old system', null=True)),
            ],
            options={
                'db_table': 'masters_licensesubcategory',
            },
        ),
        migrations.CreateModel(
            name='LicenseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200)),
            ],
            options={
                'db_table': 'masters_licensetitle',
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(help_text='Type of license', max_length=200)),
            ],
            options={
                'db_table': 'masters_licensetype',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.IntegerField(help_text='Unique location code', unique=True)),
                ('location_description', models.CharField(help_text='Description of the location', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_location',
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Name of the location category', max_length=100, unique=True, validators=[validate_name_extended])),
                ('description', models.TextField(blank=True, help_text='Detailed description', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location Category',
                'verbose_name_plural': 'Location Categories',
                'db_table': 'masters_locationcategory',
            },
        ),
        migrations.CreateModel(
            name='LocationSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(help_text='Name of the location subcategory', max_length=100, validators=[validate_name_extended])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location Subcategory',
                'verbose_name_plural': 'Location Subcategories',
                'db_table': 'masters_locationsubcategory',
                'ordering': ['category', 'subcategory_name'],
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station', models.CharField(blank=True, max_length=30, null=True, validators=[validate_name])),
                ('police_station_code', models.IntegerField(default=11999, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_policestation',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=100, validators=[validate_name_extended])),
                ('road_type', models.CharField(choices=[('NH', 'National Highway'), ('SH', 'State Highway'), ('LINK ROAD', 'Link Road')], default='NH', max_length=10)),
            ],
            options={
                'db_table': 'masters_road',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Sikkim', max_length=50)),
                ('state_code', models.IntegerField(default=11, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_state',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(blank=True, max_length=30, null=True, validators=[validate_name])),
                ('subdivision_code', models.IntegerField(default=1553, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_subdivision',
            },
        ),
        migrations.CreateModel(
            name='SupplyChainTimerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('delay_value', models.PositiveIntegerField(default=10)),
                ('delay_unit', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], default='second', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supply Chain Timer Config',
                'verbose_name_plural': 'Supply Chain Timer Configs',
                'db_table': 'timer',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100, validators=[validate_name_extended])),
                ('ward_number', models.IntegerField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'db_table': 'masters_ward',
                'ordering': ['location_code', 'ward_number'],
            },
        ),
    ]
