# Generated by Django 5.1.7 on 2026-04-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licensefee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_license_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensefee',
            name='license_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_fees', to='core.licensecategory'),
        ),
        migrations.AddField(
            model_name='licensesubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.licensecategory'),
        ),
        migrations.AddField(
            model_name='licensefee',
            name='license_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_fees', to='core.licensesubcategory'),
        ),
        migrations.AddField(
            model_name='location',
            name='district_code',
            field=models.ForeignKey(db_column='district_code', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.district', to_field='district_code'),
        ),
        migrations.AddField(
            model_name='licensefee',
            name='location_code',
            field=models.ForeignKey(db_column='location_code', on_delete=django.db.models.deletion.CASCADE, related_name='license_fees', to='core.location', to_field='location_code'),
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_location_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.locationcategory'),
        ),
        migrations.AddField(
            model_name='locationsubcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_location_subcategories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='road',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='core.district', to_field='district_code'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('state', 'state_code'), name='unique_state_identifier'),
        ),
        migrations.AddField(
            model_name='district',
            name='state_code',
            field=models.ForeignKey(db_column='state_code', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.state', to_field='state_code'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='district_code',
            field=models.ForeignKey(db_column='district_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='core.district', to_field='district_code'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='subdivision_code',
            field=models.ForeignKey(db_column='subdivision_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='core.subdivision', to_field='subdivision_code'),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='location_code',
            field=models.ForeignKey(db_column='location_code', on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.location', to_field='location_code'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('district_code', 'location_code'), name='unique_location_code_per_district'),
        ),
        migrations.AddConstraint(
            model_name='licensefee',
            constraint=models.UniqueConstraint(fields=('license_category', 'license_subcategory', 'location_code'), name='unique_license_fee_combination'),
        ),
        migrations.AddConstraint(
            model_name='locationsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'subcategory_name'), name='unique_subcategory_per_category'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('state_code', 'district_code'), name='unique_district_code_per_state'),
        ),
        migrations.AddConstraint(
            model_name='subdivision',
            constraint=models.UniqueConstraint(fields=('district_code', 'subdivision_code'), name='unique_subdivision_code_per_district'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('location_code', 'ward_number'), name='unique_ward_number_per_location'),
        ),
    ]
