# Generated by Django 5.1.7 on 2025-07-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='district_id',
            new_name='district',
        ),
    ]
