# Generated by Django 5.1.7 on 2026-04-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_supplychaintimerconfig_delay_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychaintimerconfig',
            name='validity_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
