# Generated by Django 5.1.7 on 2026-05-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplychaintimerconfig_validity_period_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensefee',
            name='location_code',
            field=models.ForeignKey(blank=True, db_column='location_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_fees', to='core.location', to_field='location_code'),
        ),
    ]
