# Generated by Django 5.2.8 on 2026-05-30

from django.db import migrations


def seed_license_renewal_timer(apps, schema_editor):
    SupplyChainTimerConfig = apps.get_model("core", "SupplyChainTimerConfig")

    # Configurable from public.timer via /masters/core/timer-config/?code=LICENSE_RENEWAL_TIMER
    SupplyChainTimerConfig.objects.update_or_create(
        code="LICENSE_RENEWAL_TIMER",
        defaults={
            "description": "Default license renewal period (editable).",
            "delay_value": 12,
            "delay_unit": "month",
            "is_active": True,
            "validity_period_days": 365,
        },
    )


def unseed_license_renewal_timer(apps, schema_editor):
    SupplyChainTimerConfig = apps.get_model("core", "SupplyChainTimerConfig")
    SupplyChainTimerConfig.objects.filter(code="LICENSE_RENEWAL_TIMER").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_licensefee_location_code"),
    ]

    operations = [
        migrations.RunPython(seed_license_renewal_timer, unseed_license_renewal_timer),
    ]

