# Generated by Django 5.2.8 on 2026-05-30

from django.db import migrations


def seed_license_renewal_reminder_timer(apps, schema_editor):
    SupplyChainTimerConfig = apps.get_model("core", "SupplyChainTimerConfig")

    # Configurable from public.timer via /masters/core/timer-config/?code=LICENSE_RENEWAL_REMINDER_TIMER
    # Used to decide when renewal becomes allowed before expiry.
    SupplyChainTimerConfig.objects.update_or_create(
        code="LICENSE_RENEWAL_REMINDER_TIMER",
        defaults={
            "description": "License renewal reminder/eligibility window before expiry (editable).",
            "delay_value": 90,
            "delay_unit": "day",
            "is_active": True,
            "validity_period_days": 90,
        },
    )


def unseed_license_renewal_reminder_timer(apps, schema_editor):
    SupplyChainTimerConfig = apps.get_model("core", "SupplyChainTimerConfig")
    SupplyChainTimerConfig.objects.filter(code="LICENSE_RENEWAL_REMINDER_TIMER").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_seed_license_renewal_timer"),
    ]

    operations = [
        migrations.RunPython(
            seed_license_renewal_reminder_timer, unseed_license_renewal_reminder_timer
        ),
    ]

