# Generated by Django 5.1.7 on 2026-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_license_renewal_reminder_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychaintimerconfig',
            name='delay_unit',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='second', max_length=10),
        ),
    ]
