# Generated by Django 5.2.8 on 2026-06-03 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_supplychaintimerconfig_delay_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRenewalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_month', models.PositiveIntegerField(default=3, help_text='Month of renewal (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('renewal_day', models.PositiveIntegerField(default=31, help_text='Day of renewal (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
            options={
                'verbose_name': 'License Renewal Date Configuration',
                'verbose_name_plural': 'License Renewal Date Configurations',
                'db_table': 'license_renewal_config',
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='location_description',
            field=models.CharField(help_text='Description of the of the location', max_length=200),
        ),
    ]
