# Generated by Django 5.2.8 on 2026-06-03 07:18

from django.db import migrations

def seed_license_renewal_config(apps, schema_editor):
    LicenseRenewalConfig = apps.get_model('core', 'LicenseRenewalConfig')
    LicenseRenewalConfig.objects.get_or_create(
        id=1,
        defaults={'renewal_month': 3, 'renewal_day': 31}
    )

def unseed_license_renewal_config(apps, schema_editor):
    LicenseRenewalConfig = apps.get_model('core', 'LicenseRenewalConfig')
    LicenseRenewalConfig.objects.filter(id=1).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_licenserenewalconfig_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_license_renewal_config, unseed_license_renewal_config)
    ]
