# Generated by Django 5.2.8 on 2026-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_license_renewal_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserenewalconfig',
            name='renewal_time',
            field=models.TimeField(default='23:59:59', help_text='Time of day when the license expires'),
        ),
    ]
