# Generated by Django 5.2.8 on 2026-06-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_licenserenewalconfig_renewal_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenseRenewalConfig',
            new_name='RenewalApplicationConfig',
        ),
        migrations.AlterModelOptions(
            name='renewalapplicationconfig',
            options={'verbose_name': 'License Validity Period', 'verbose_name_plural': 'License Validity Periods'},
        ),
        migrations.AlterModelTable(
            name='renewalapplicationconfig',
            table='renewal_application_config',
        ),
    ]
