# Generated by Django 5.2.8 on 2026-06-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_licenserenewalconfig_renewalapplicationconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('pachwai', 'Pachwai'), ('draught_beer', 'Draught Beer')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='core.licensecategory')),
            ],
            options={
                'db_table': 'masters_additionalchargeconfig',
                'constraints': [models.UniqueConstraint(fields=('category', 'charge_type'), name='unique_category_charge_type')],
            },
        ),
    ]
