# Generated by Django 5.2.8 on 2026-06-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_additionalchargeconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalchargeconfig',
            name='amount',
        ),
    ]
