# Generated by Django 5.1.7 on 2026-06-22 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_masterfixedfee_and_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('act', 'Acts'), ('rule', 'Rules'), ('circular', 'Circulars'), ('bullet', 'Bullet Notifications'), ('license', 'License Info')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='whats_current/pdfs/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'masters_whatscurrent',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
