# Generated by Django 5.1.7 on 2026-07-03 12:32

import django.db.models.deletion
import models.masters.core.validators as core_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_whatscurrent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['location_code', 'ward_number'], 'verbose_name': 'Urban Ward', 'verbose_name_plural': 'Urban Wards'},
        ),
        migrations.AddField(
            model_name='locationsubcategory',
            name='sub_division',
            field=models.ForeignKey(blank=True, db_column='sub_division_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_subcategories', to='core.subdivision'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='is_rural',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='ward',
            table='master_urbanward',
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100, validators=[core_validators.validate_name_extended])),
                ('is_active', models.BooleanField(default=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocks', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.locationsubcategory')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'db_table': 'master_block',
            },
        ),
        migrations.CreateModel(
            name='RuralWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100, validators=[core_validators.validate_name_extended])),
                ('ward_number', models.IntegerField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rural_wards', to='core.block')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rural_wards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rural Ward',
                'verbose_name_plural': 'Rural Wards',
                'db_table': 'master_ruralward',
                'ordering': ['block', 'ward_number'],
                'constraints': [models.UniqueConstraint(fields=('block', 'ward_number'), name='unique_rural_ward_number_per_block')],
            },
        ),
    ]
