# Generated by Django 5.2.8 on 2026-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ward_options_locationsubcategory_sub_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='is_rural',
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='is_rural',
            field=models.BooleanField(default=False),
        ),
    ]
