# Generated by Django 5.2.8 on 2026-07-05 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_subdivision_is_rural_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['subcategory', 'ward_number'], 'verbose_name': 'Urban Ward', 'verbose_name_plural': 'Urban Wards'},
        ),
        migrations.RemoveConstraint(
            model_name='ward',
            name='unique_ward_number_per_location',
        ),
        migrations.AddField(
            model_name='ward',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='subcategory_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='core.locationsubcategory'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='location_code',
            field=models.ForeignKey(blank=True, db_column='location_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.location', to_field='location_code'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('subcategory', 'ward_number'), name='unique_ward_number_per_subcategory'),
        ),
    ]
