# Generated by Django 5.1.7 on 2026-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ward_add_subcategory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensesubcategory',
            name='dry_day_fee_type',
            field=models.CharField(blank=True, choices=[('per_annum', 'Per Annum'), ('per_day', 'Per Day')], default=None, max_length=20, null=True),
        ),
    ]
