# Generated by Django 5.1.7 on 2026-07-08 14:49

from django.db import migrations
from decimal import Decimal


def insert_dry_day_fee_rows(apps, schema_editor):
    MasterFixedFee = apps.get_model('core', 'MasterFixedFee')
    MasterFixedFee.objects.update_or_create(
        fee_code='DRY_DAY_PER_DAY',
        defaults={
            'fee_desc': 'DRY day per day fees',
            'amount': Decimal('500.00'),
            'is_active': True,
        }
    )
    MasterFixedFee.objects.update_or_create(
        fee_code='DRY_DAY_ANNUAL_RURAL',
        defaults={
            'fee_desc': 'dry day annual rural fees',
            'amount': Decimal('5000.00'),
            'is_active': True,
        }
    )
    MasterFixedFee.objects.update_or_create(
        fee_code='DRY_DAY_ANNUAL_URBAN',
        defaults={
            'fee_desc': 'dry day annual urban fees',
            'amount': Decimal('10000.00'),
            'is_active': True,
        }
    )


def remove_dry_day_fee_rows(apps, schema_editor):
    MasterFixedFee = apps.get_model('core', 'MasterFixedFee')
    MasterFixedFee.objects.filter(fee_code__in=['DRY_DAY_PER_DAY', 'DRY_DAY_ANNUAL_RURAL', 'DRY_DAY_ANNUAL_URBAN']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_licensesubcategory_dry_day_fee_type'),
    ]

    operations = [
        migrations.RunPython(insert_dry_day_fee_rows, remove_dry_day_fee_rows),
    ]
