# Generated by Django 5.1.7 on 2026-07-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20260708_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this license category is active'),
        ),
        migrations.AddField(
            model_name='licensesubcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this license subcategory is active'),
        ),
    ]
