# Generated by Django 5.1.7 on 2026-07-09 05:48

from django.db import migrations, models


def seed_special_permit_allowed(apps, schema_editor):
    """
    Set is_special_permit_allowed = True for the categories that are
    allowed to submit Special Permit (Dry Day) applications:
      - Bar - cum - Hotel & Lodge
      - Discotheque & Night Club
      - Restaurant - cum - Bar Shop
      - Grade Category Hotel
      - Special Category Hotel
    All other categories (including Foreign Liquor Retail Shop) remain False.
    """
    LicenseCategory = apps.get_model('core', 'LicenseCategory')
    allowed_names = [
        'Bar - cum - Hotel & Lodge',
        'Discotheque & Night Club',
        'Restaurant - cum - Bar Shop',
        'Grade Category Hotel',
        'Special Category Hotel',
    ]
    LicenseCategory.objects.filter(
        license_category__in=allowed_names
    ).update(is_special_permit_allowed=True)


def reverse_seed_special_permit_allowed(apps, schema_editor):
    LicenseCategory = apps.get_model('core', 'LicenseCategory')
    LicenseCategory.objects.all().update(is_special_permit_allowed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_is_active_to_license_category_and_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecategory',
            name='is_special_permit_allowed',
            field=models.BooleanField(default=False, help_text='Whether licenses of this category are allowed to submit Special Permit (Dry Day) applications'),
        ),
        migrations.RunPython(
            seed_special_permit_allowed,
            reverse_seed_special_permit_allowed,
        ),
    ]
