# Generated by Django 5.2.8 on 2026-07-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_licensecategory_is_special_permit_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetitle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
