# Generated by Django 5.2.8 on 2026-07-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_licensetitle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatscurrent',
            name='category',
            field=models.CharField(choices=[('act', 'Acts'), ('rule', 'Rules'), ('circular', 'Circulars'), ('bullet', 'Bullet Notifications'), ('license', 'Flash Notification')], max_length=50),
        ),
    ]
