# Generated by Django 5.1.7 on 2026-08-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_whatscurrent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfixedfee',
            name='license_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_fees', to='core.licensecategory'),
        ),
        migrations.AddField(
            model_name='masterfixedfee',
            name='license_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_fees', to='core.licensesubcategory'),
        ),
        migrations.AddField(
            model_name='masterfixedfee',
            name='mode',
            field=models.CharField(blank=True, choices=[('rural', 'Rural'), ('urban', 'Urban'), ('non', 'Non')], max_length=20, null=True),
        ),
    ]
