# Generated by Django 5.1.7 on 2026-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_masterfixedfee_license_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfixedfee',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('per_annum', 'Per Annum'), ('per_day', 'Per Day')], help_text='Whether this fee applies to annual or per-day dry day permits', max_length=20, null=True),
        ),
    ]
