# Generated by Django 5.2.8 on 2026-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_masterfixedfee_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalchargeconfig',
            name='charge_type',
            field=models.CharField(choices=[('pachwai', 'Pachwai'), ('draught_beer', 'Draught Beer'), ('mini_bar', 'Mini Bar')], max_length=50),
        ),
    ]
