# Generated by custom script

from django.db import migrations

def seed_minibar_fixed_fee(apps, schema_editor):
    MasterFixedFee = apps.get_model("core", "MasterFixedFee")
    MasterFixedFee.objects.update_or_create(
        fee_code="NLI_ADD_MINI_BAR",
        defaults={
            "fee_desc": "New License (Additional Charge) - Mini Bar",
            "amount": 1000.00,
            "is_active": True,
        }
    )

def rollback_minibar_fixed_fee(apps, schema_editor):
    MasterFixedFee = apps.get_model("core", "MasterFixedFee")
    MasterFixedFee.objects.filter(fee_code="NLI_ADD_MINI_BAR").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_additionalchargeconfig_charge_type'),
    ]

    operations = [
        migrations.RunPython(seed_minibar_fixed_fee, rollback_minibar_fixed_fee),
    ]
