# Generated by Django 5.1.7 on 2026-08-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_seed_minibar_fixed_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplychaintimerconfig',
            name='validity_period_days',
        ),
    ]
