# Generated by Django 5.1.7 on 2026-08-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_licensecategory_is_distributor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'GPU', 'verbose_name_plural': 'GPUs'},
        ),
        migrations.RenameField(
            model_name='block',
            old_name='block_name',
            new_name='gpu_name',
        ),
        migrations.AlterModelTable(
            name='block',
            table='master_gpu',
        ),
    ]
