# Generated by Django 5.1.7 on 2026-09-01 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_block_options_rename_block_name_block_gpu_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='subdivision_code',
        ),
        migrations.AddField(
            model_name='policestation',
            name='district_code',
            field=models.ForeignKey(db_column='district_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='core.district', to_field='district_code'),
        ),
    ]
