# Generated by Django 5.2.8 on 2026-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_policestation_subdivision_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensesubcategory',
            name='allow_company_collaboration',
            field=models.BooleanField(default=True, help_text='Whether Company Collaboration is enabled for licensees of this subcategory'),
        ),
        migrations.AddField(
            model_name='licensesubcategory',
            name='allow_company_registration',
            field=models.BooleanField(default=True, help_text='Whether Company Registration is enabled for licensees of this subcategory'),
        ),
        migrations.AddField(
            model_name='licensesubcategory',
            name='allow_label_registration',
            field=models.BooleanField(default=True, help_text='Whether Label Registration is enabled for licensees of this subcategory'),
        ),
        migrations.AddField(
            model_name='licensesubcategory',
            name='allow_salesman_barman',
            field=models.BooleanField(default=True, help_text='Whether Salesman/Barman Registration is enabled for licensees of this subcategory'),
        ),
    ]
