# Generated by Django 5.1.6 on 2025-03-20 07:53

import django.db.models.deletion
import salesman_barman.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_size_photo', models.ImageField(upload_to='documents/passport_photos/')),
                ('aadhar_card', models.FileField(upload_to='documents/aadhar_cards/')),
                ('sikkim_subject_certificate', models.FileField(upload_to='documents/sikkim_subject_certificates/')),
                ('date_of_birth_proof', models.FileField(upload_to='documents/date_of_birth_proofs/')),
            ],
            options={
                'db_table': 'documents_details',
            },
        ),
        migrations.CreateModel(
            name='SalesmanBarmanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_or_husband_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('nationality', models.CharField(choices=[('indian', 'Indian'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField(validators=[salesman_barman.helpers.validate_address])),
                ('pan_number', models.CharField(max_length=10, validators=[salesman_barman.helpers.validate_pan_number])),
                ('aadhar_number', models.CharField(max_length=12, validators=[salesman_barman.helpers.validate_aadhar_number])),
                ('email', models.EmailField(max_length=254, validators=[salesman_barman.helpers.validate_email])),
                ('mode_of_operation', models.CharField(choices=[('salesman', 'Salesman'), ('barman', 'Barman')], max_length=20)),
                ('application_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049), (2050, 2050)], default=2025)),
                ('application_id', models.CharField(max_length=100, unique=True)),
                ('application_date', models.DateField()),
                ('district', models.CharField(choices=[('district_1', 'District 1'), ('district_2', 'District 2'), ('district_3', 'District 3')], max_length=100)),
                ('license_category', models.CharField(choices=[('type_a', 'Type A'), ('type_b', 'Type B'), ('type_c', 'Type C')], max_length=100)),
                ('license_type', models.CharField(choices=[('type_a', 'Type A'), ('type_b', 'Type B'), ('type_c', 'Type C')], max_length=100)),
                ('salesman_specific_field', models.CharField(blank=True, max_length=255, null=True)),
                ('barman_specific_field', models.CharField(blank=True, max_length=255, null=True)),
                ('documents', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesman_barman.documentsdetails')),
            ],
            options={
                'db_table': 'salesman_barman_details',
            },
        ),
    ]
