# Generated by Django 5.1.7 on 2025-03-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanBarman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barman_first_name', models.CharField(max_length=100)),
                ('Barman_middle_name', models.CharField(max_length=100)),
                ('Barman_last_name', models.CharField(max_length=100)),
                ('Barman_Father_name', models.CharField(max_length=100)),
                ('Barman_Nationality', models.CharField(max_length=100)),
                ('Barman_Address', models.CharField(max_length=500)),
                ('Barman_Email', models.CharField(max_length=100)),
                ('Barman_Mobile_No', models.CharField(max_length=10, unique=True)),
                ('Barman_DOB', models.DateTimeField(blank=True, null=True)),
                ('Barman_PAN_ID', models.CharField(max_length=10, unique=True)),
                ('Barman_Aadhar_ID', models.CharField(max_length=12, unique=True)),
                ('Barman_Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
    ]
