# Generated by Django 5.1.6 on 2025-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='district',
            field=models.IntegerField(choices=[(1, 'District 1'), (2, 'District 2'), (3, 'District 3')]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='license_category',
            field=models.IntegerField(choices=[(1, 'Type A'), (2, 'Type B'), (3, 'Type C')]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='license_type',
            field=models.IntegerField(choices=[(1, 'Type A'), (2, 'Type B'), (3, 'Type C')]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='mode_of_operation',
            field=models.IntegerField(choices=[(1, 'Salesman'), (2, 'Barman')]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='nationality',
            field=models.IntegerField(choices=[(1, 'Indian'), (2, 'Other')]),
        ),
    ]
