# Generated by Django 5.1.6 on 2025-03-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanbarman',
            name='Barman_Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
