# Generated by Django 5.1.4 on 2025-04-06 05:13

import salesman_barman.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='emailId',
            field=models.EmailField(db_column='email_id', max_length=254, validators=[salesman_barman.helpers.validate_email]),
        ),
    ]
