# Generated by Django 5.1.6 on 2025-03-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0002_alter_salesmanbarman_barman_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanbarman',
            name='Barman_Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
