# Generated by Django 5.1.6 on 2025-05-07 07:55

import salesman_barman.helpers
import salesman_barman.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0002_alter_salesmanbarmanmodel_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='dateofBirthProof',
            field=models.FileField(db_column='dateofbirth_proof', upload_to=salesman_barman.models.upload_document_path),
        ),
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='emailId',
            field=models.EmailField(blank=True, db_column='email_id', max_length=254, validators=[salesman_barman.helpers.validate_email]),
        ),
    ]
