# Generated by Django 5.1.4 on 2025-03-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0002_alter_salesmanbarman_barman_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_Aadhar_ID',
            new_name='Aadhar_ID',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_Address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_DOB',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_Email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_Father_name',
            new_name='Father_name',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_Gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_Mobile_No',
            new_name='Mobile_No',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_Nationality',
            new_name='Nationality',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_PAN_ID',
            new_name='PAN_ID',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='salesmanbarman',
            old_name='Barman_middle_name',
            new_name='middle_name',
        ),
    ]
