# Generated by Django 5.1.4 on 2025-04-30 15:18

import salesman_barman.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0003_alter_salesmanbarmanmodel_dateofbirthproof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanbarmanmodel',
            name='dateofBirthProof',
            field=models.FileField(db_column='dateof_birth_proof', upload_to=salesman_barman.models.upload_document_path),
        ),
    ]
