# Generated by Django 5.1.6 on 2025-03-20 07:03

import salesman_barman.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_barman', '0003_alter_salesmanbarmandetails_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='aadhar_number',
            field=models.CharField(max_length=12, validators=[salesman_barman.helpers.validate_aadhar_number]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='address',
            field=models.TextField(validators=[salesman_barman.helpers.validate_address]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='email',
            field=models.EmailField(max_length=254, validators=[salesman_barman.helpers.validate_email]),
        ),
        migrations.AlterField(
            model_name='salesmanbarmandetails',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[salesman_barman.helpers.validate_pan_number]),
        ),
    ]
