# Generated by Django 5.2.1 on 2025-05-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('site_admin', 'Site Admin'), ('commissioner', 'Commissioner'), ('joint_commissioner', 'Joint Commissioner'), ('permit_section', 'Permit Section'), ('licensee', 'Licensee')], max_length=19),
        ),
    ]
