# Generated by Django 5.1.6 on 2025-03-20 07:03

import registration_renewal.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_renewal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[registration_renewal.helpers.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='name',
            field=models.CharField(max_length=100, validators=[registration_renewal.helpers.validate_name]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[registration_renewal.helpers.validate_pan_number]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='registered_office_address',
            field=models.CharField(max_length=255, validators=[registration_renewal.helpers.validate_address]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='email',
            field=models.EmailField(max_length=100, validators=[registration_renewal.helpers.validate_email]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='member_address',
            field=models.CharField(max_length=255, validators=[registration_renewal.helpers.validate_address]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='member_designation',
            field=models.CharField(max_length=100, validators=[registration_renewal.helpers.validate_address]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='member_name',
            field=models.CharField(max_length=100, validators=[registration_renewal.helpers.validate_name]),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[registration_renewal.helpers.validate_mobile_number]),
        ),
    ]
