# Generated by Django 5.2.1 on 2025-05-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('user', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
