# Generated by Django 5.1.7 on 2025-07-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.IntegerField(default=117),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subdivision',
            field=models.IntegerField(default=1001),
        ),
    ]
