# Generated by Django 5.1.7 on 2026-07-28 06:41

from models.masters.about_us.models import upload_head_image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_excisesecretary_from_date_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headoforganisation',
            name='image',
            field=models.ImageField(max_length=500, upload_to=upload_head_image_path),
        ),
    ]
