# Generated by Django 5.1.7 on 2026-09-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_alter_headoforganisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='accent_color',
            field=models.CharField(blank=True, default='#1C2B78', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_bg_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='header_color',
            field=models.CharField(blank=True, default='#1C2B78', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='header_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='page_key',
            field=models.CharField(db_index=True, default='department', max_length=100),
        ),
    ]
