# Generated by Django 5.1.7 on 2026-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_aboutus_accent_color_aboutus_card_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Department', max_length=255)),
                ('content', models.TextField()),
                ('header_color', models.CharField(blank=True, default='#1C2B78', max_length=50)),
                ('header_text_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('card_bg_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('accent_color', models.CharField(blank=True, default='#1C2B78', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Department',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Products & Services', max_length=255)),
                ('content', models.TextField()),
                ('header_color', models.CharField(blank=True, default='#1C2B78', max_length=50)),
                ('header_text_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('card_bg_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('accent_color', models.CharField(blank=True, default='#1C2B78', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products_Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Refund / Cancellation Policy', max_length=255)),
                ('content', models.TextField()),
                ('header_color', models.CharField(blank=True, default='#1C2B78', max_length=50)),
                ('header_text_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('card_bg_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('accent_color', models.CharField(blank=True, default='#1C2B78', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Refund_Cancellation_Policy',
                'ordering': ['-created_at'],
            },
        ),
    ]
