# Generated by Django 5.1.7 on 2026-09-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_department_productsservices_refundcancellationpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
