# Generated by Django 5.1.7 on 2025-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enaDistilleryTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distillery_name', models.CharField(max_length=100)),
                ('distillery_address', models.CharField(max_length=100)),
                ('distillery_state', models.CharField(max_length=100)),
                ('via_route', models.CharField(max_length=100)),
            ],
        ),
    ]
