# Generated by Django 5.1.7 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enaDistilleryTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distillery_name', models.CharField(max_length=255)),
                ('licensee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('distillery_address', models.TextField()),
                ('distillery_state', models.CharField(max_length=100)),
                ('via_route', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ENA Distillery',
                'verbose_name_plural': 'ENA Distilleries',
                'db_table': 'ena_distillery_details',
            },
        ),
    ]
