# Generated by Django 5.1.7 on 2026-05-10

from django.db import migrations, models
import models.masters.core.validators as core_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, validators=[core_validators.validate_name_extended])),
                ('category', models.CharField(choices=[('act', 'Act'), ('rule', 'Rule'), ('circular', 'Circular')], max_length=20)),
                ('notification_date', models.DateField()),
                ('notification_file', models.FileField(blank=True, max_length=500, null=True, upload_to='notifications/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_notification',
                'ordering': ['-notification_date', '-id'],
            },
        ),
    ]
