# Generated by Django 5.1.7 on 2026-05-10

from django.db import migrations, models
import models.masters.notification.models as notification_models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=255, validators=[notification_models.validate_notification_subject]),
        ),
    ]
