-- Payment schema for PostgreSQL (Phase 1: core tables)
-- Source reference: legacy SQL Server eAbgari payment tables
-- Run:
--   psql -U postgres -d eAbkari_db -f PAYMENT_POSTGRESQL_TABLES.sql

BEGIN;

-- 1) Gateway parameters
CREATE TABLE IF NOT EXISTS eabgari_payment_gateway_parameters (
    sl_no INTEGER PRIMARY KEY,
    payment_gateway_name VARCHAR(50) NOT NULL,
    merchantid VARCHAR(100) NOT NULL,
    securityid VARCHAR(100) NOT NULL,
    encryption_key VARCHAR(255) NOT NULL,
    return_url VARCHAR(500) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP NULL,
    is_active CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT chk_gateway_active CHECK (is_active IN ('Y', 'N'))
);

-- 2) BillDesk transaction (request + response)
CREATE TABLE IF NOT EXISTS eabgari_payment_trsansaction_billdesk (
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_id_no_hoa VARCHAR(50) NOT NULL,
    payer_id VARCHAR(50) NOT NULL,
    payment_module_code VARCHAR(20) NOT NULL,
    transaction_amount NUMERIC(18,2) NOT NULL,
    utr VARCHAR(100) PRIMARY KEY,

    request_merchantid VARCHAR(100),
    request_currencytype VARCHAR(10),
    request_typefield1 VARCHAR(10),
    request_securityid VARCHAR(100),
    request_typefield2 VARCHAR(10),
    request_additionalinfo1 VARCHAR(200),
    request_additionalinfo2 VARCHAR(200),
    request_additionalinfo3 VARCHAR(200),
    request_additionalinfo4 VARCHAR(200),
    request_additionalinfo5 VARCHAR(200),
    request_additionalinfo6 VARCHAR(200),
    request_additionalinfo7 VARCHAR(200),
    request_return_url VARCHAR(500),
    request_checksum VARCHAR(500),
    request_string TEXT,

    response_string TEXT,
    response_merchantid VARCHAR(100),
    response_customerid VARCHAR(100),
    response_txnreferenceno VARCHAR(100),
    response_bankreferenceno VARCHAR(100),
    response_txnamount NUMERIC(18,2),
    response_bankid VARCHAR(50),
    response_bankmerchantid VARCHAR(100),
    response_txntype VARCHAR(50),
    response_currencyname VARCHAR(10),
    response_itemcode VARCHAR(50),
    response_securitytype VARCHAR(50),
    response_securityid VARCHAR(100),
    response_securitypassword VARCHAR(100),
    response_txndate TIMESTAMP,
    response_authstatus VARCHAR(10),
    response_settlementtype VARCHAR(50),
    response_additionalinfo1 VARCHAR(200),
    response_additionalinfo2 VARCHAR(200),
    response_additionalinfo3 VARCHAR(200),
    response_additionalinfo4 VARCHAR(200),
    response_additionalinfo5 VARCHAR(200),
    response_additionalinfo6 VARCHAR(200),
    response_additionalinfo7 VARCHAR(200),
    response_errorstatus VARCHAR(50),
    response_errordescription VARCHAR(500),
    response_checksum VARCHAR(500),
    response_checksum_calculated VARCHAR(500),
    response_initial_authstatus VARCHAR(10),
    response_initial_datetime TIMESTAMP,

    payment_status CHAR(1) NOT NULL DEFAULT 'P',
    user_id VARCHAR(50),
    opr_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_payment_status CHECK (payment_status IN ('P', 'S', 'F'))
);

CREATE INDEX IF NOT EXISTS ix_payment_transaction_date
    ON eabgari_payment_trsansaction_billdesk (transaction_date);
CREATE INDEX IF NOT EXISTS ix_payment_payer_id
    ON eabgari_payment_trsansaction_billdesk (payer_id);
CREATE INDEX IF NOT EXISTS ix_payment_module_code
    ON eabgari_payment_trsansaction_billdesk (payment_module_code);
CREATE INDEX IF NOT EXISTS ix_payment_auth_status
    ON eabgari_payment_trsansaction_billdesk (response_authstatus);

-- 3) HOA breakup per transaction
CREATE TABLE IF NOT EXISTS eabgari_payment_send_hoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id_no VARCHAR(50) NOT NULL,
    head_of_account VARCHAR(50) NOT NULL,
    payer_id VARCHAR(50) NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    payment_module_code VARCHAR(20),
    requisition_id_no VARCHAR(50),
    user_id VARCHAR(50),
    opr_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_payment_hoa_transaction
    ON eabgari_payment_send_hoa (transaction_id_no);
CREATE INDEX IF NOT EXISTS ix_payment_hoa_payer
    ON eabgari_payment_send_hoa (payer_id);
CREATE INDEX IF NOT EXISTS ix_payment_hoa_account
    ON eabgari_payment_send_hoa (head_of_account);

-- 4) BillDesk auth/status mapping
CREATE TABLE IF NOT EXISTS eabgari_payment_status_master_billdesk (
    authstatus VARCHAR(10) PRIMARY KEY,
    authstatus_description VARCHAR(500) NOT NULL,
    payment_status CHAR(1) NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_status_master_payment_status CHECK (payment_status IN ('P', 'S', 'F'))
);

INSERT INTO eabgari_payment_status_master_billdesk (authstatus, authstatus_description, payment_status)
VALUES
    ('0300', 'Payment Successful', 'S'),
    ('0399', 'Payment Failed', 'F'),
    ('0002', 'Payment Pending', 'P'),
    ('0001', 'Transaction Initiated', 'P'),
    ('NA',   'Not Available', 'P'),
    ('0400', 'Invalid Input', 'F'),
    ('0401', 'Duplicate Transaction', 'F')
ON CONFLICT (authstatus) DO NOTHING;

-- 5) FDR parameters
CREATE TABLE IF NOT EXISTS eabgari_payment_billdesk_fdr_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_module_code VARCHAR(20) NOT NULL,
    requisition_id_no VARCHAR(50) NOT NULL,
    request_additionalinfo1 VARCHAR(200),
    request_additionalinfo2 VARCHAR(200),
    request_additionalinfo3 VARCHAR(200),
    request_additionalinfo4 VARCHAR(200),
    request_additionalinfo5 VARCHAR(200),
    request_additionalinfo6 VARCHAR(200),
    request_additionalinfo7 VARCHAR(200),
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    CONSTRAINT uq_fdr_params UNIQUE (payment_module_code, requisition_id_no)
);

-- 6) Wallet balance master
CREATE TABLE IF NOT EXISTS eabgari_pay_wallet_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licensee_id_no VARCHAR(50) NOT NULL,
    head_of_account VARCHAR(50) NOT NULL,
    wallet_amount NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP,
    CONSTRAINT uq_wallet_master UNIQUE (licensee_id_no, head_of_account)
);

CREATE INDEX IF NOT EXISTS ix_wallet_master_licensee
    ON eabgari_pay_wallet_master (licensee_id_no);
CREATE INDEX IF NOT EXISTS ix_wallet_master_hoa
    ON eabgari_pay_wallet_master (head_of_account);

-- 7) Wallet transaction ledger
CREATE TABLE IF NOT EXISTS eabgari_pay_wallet_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    implementing_state_code VARCHAR(10) NOT NULL DEFAULT '28',
    wallet_transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    wallet_transaction_type CHAR(1) NOT NULL,
    licensee_id_no VARCHAR(50) NOT NULL,
    head_of_account VARCHAR(50) NOT NULL,
    transaction_amount NUMERIC(18,2) NOT NULL,
    transaction_reference_number VARCHAR(100) NOT NULL,
    wallet_transaction_status CHAR(1) NOT NULL DEFAULT 'Y',
    initialization_flag CHAR(1) NOT NULL DEFAULT 'T',
    bank_utr VARCHAR(100),
    payment_module_code VARCHAR(20),
    transaction_remarks VARCHAR(500),
    user_id VARCHAR(50),
    opr_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_wallet_txn_type CHECK (wallet_transaction_type IN ('C', 'D')),
    CONSTRAINT chk_wallet_txn_status CHECK (wallet_transaction_status IN ('Y', 'N')),
    CONSTRAINT chk_wallet_init_flag CHECK (initialization_flag IN ('T', 'F'))
);

CREATE INDEX IF NOT EXISTS ix_wallet_transaction_date
    ON eabgari_pay_wallet_transaction (wallet_transaction_date);
CREATE INDEX IF NOT EXISTS ix_wallet_transaction_licensee
    ON eabgari_pay_wallet_transaction (licensee_id_no);
CREATE INDEX IF NOT EXISTS ix_wallet_transaction_utr
    ON eabgari_pay_wallet_transaction (bank_utr);

-- 8) HOA master
CREATE TABLE IF NOT EXISTS eabgari_master_head_of_accounts (
    head_of_account VARCHAR(50) PRIMARY KEY,
    sl_no INTEGER GENERATED BY DEFAULT AS IDENTITY,
    major_head VARCHAR(10) NOT NULL,
    sub_major_head VARCHAR(10),
    minor_head VARCHAR(10) NOT NULL,
    sub_head VARCHAR(10),
    detailed_head VARCHAR(20) NOT NULL,
    object_head VARCHAR(10),
    detailed_head_driscription VARCHAR(500) NOT NULL,
    pay_type VARCHAR(20),
    visible_status CHAR(1) NOT NULL DEFAULT 'Y',
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP,
    CONSTRAINT uq_hoa_slno UNIQUE (sl_no),
    CONSTRAINT chk_hoa_visible_status CHECK (visible_status IN ('Y', 'N'))
);

-- 9) Module master
CREATE TABLE IF NOT EXISTS eabgari_master_module (
    module_code VARCHAR(20) PRIMARY KEY,
    module_desc VARCHAR(200) NOT NULL,
    visibility_status CHAR(1) NOT NULL DEFAULT 'Y',
    active_payment_mode CHAR(1) NOT NULL DEFAULT 'O',
    payment_invoking_page VARCHAR(500),
    payment_response_page VARCHAR(500),
    user_id VARCHAR(50),
    opr_date TIMESTAMP,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP,
    CONSTRAINT chk_module_visibility CHECK (visibility_status IN ('Y', 'N')),
    CONSTRAINT chk_module_payment_mode CHECK (active_payment_mode IN ('O', 'W', 'B'))
);

-- 10) Module to HOA mapping
CREATE TABLE IF NOT EXISTS eabgari_module_hoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code VARCHAR(20) NOT NULL,
    head_of_account VARCHAR(50) NOT NULL,
    user_id VARCHAR(50),
    opr_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) NOT NULL DEFAULT 'Y',
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_module_hoa UNIQUE (module_code, head_of_account),
    CONSTRAINT chk_module_hoa_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT fk_module_hoa_module FOREIGN KEY (module_code)
        REFERENCES eabgari_master_module (module_code)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_module_hoa_hoa FOREIGN KEY (head_of_account)
        REFERENCES eabgari_master_head_of_accounts (head_of_account)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_module_hoa_module_code
    ON eabgari_module_hoa (module_code);
CREATE INDEX IF NOT EXISTS ix_module_hoa_head_of_account
    ON eabgari_module_hoa (head_of_account);

-- 11) Wallet transaction audit history
-- Legacy source table was in another DB (sikkimhousedb).
-- In PostgreSQL setup, keep in same database unless multi-DB routing is introduced.
CREATE TABLE IF NOT EXISTS wallet_transaction_history (
    wallet_txn_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    transaction_type VARCHAR(200) NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    licensee_id VARCHAR(50),
    approved_by VARCHAR(50),
    permitnumber VARCHAR(100),
    last_updated_date TIMESTAMP,
    remarks VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS ix_wallet_history_date
    ON wallet_transaction_history (created_at);
CREATE INDEX IF NOT EXISTS ix_wallet_history_licensee
    ON wallet_transaction_history (licensee_id);
CREATE INDEX IF NOT EXISTS ix_wallet_history_reference
    ON wallet_transaction_history (reference_id);
CREATE INDEX IF NOT EXISTS ix_wallet_history_type
    ON wallet_transaction_history (transaction_type);
CREATE INDEX IF NOT EXISTS ix_wallet_history_status
    ON wallet_transaction_history (status);

COMMIT;

-- Phase 2 (optional, legacy operations tables not created here):
--   eabgari_payment_billdesk_bank_response_file
--   eabgari_payment_billdesk_mis_dump
--   eabgari_payment_billdesk_refund
--   eabgari_pay_wallet_transaction_16072021 (archive)
--   eabgari_payment_trsansaction_billdesk_16072021 (archive)
