# Generated by Django 5.1.7 on 2026-04-06 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_unit_name', models.CharField(max_length=255)),
                ('licensee_id', models.CharField(max_length=100)),
                ('license_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supply_chain_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserManufacturingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_unit_name', models.CharField(max_length=255)),
                ('licensee_id', models.CharField(max_length=100)),
                ('license_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_manufacturing_units',
                'unique_together': {('user', 'licensee_id')},
            },
        ),
    ]
