# Generated by Codex on 2026-05-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
        ("hologram", "0004_migrate_licensee_to_units"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupplyChainUserProfile",
        ),
    ]

