# Generated by Django 5.1.7 on 2026-04-06 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('license', '0002_initial'),
        ('profile', '__first__'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HologramProcurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, unique=True)),
                ('manufacturing_unit', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('local_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('export_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('defence_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('carton_details', models.JSONField(blank=True, default=list)),
                ('arrival_date', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when OIC confirms carton arrival', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hologram_procurements', to='workflow.workflowstage')),
                ('license', models.ForeignKey(blank=True, help_text='License associated with this hologram procurement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hologram_procurements_by_license', to='license.license')),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hologram_procurements', to='profile.supplychainuserprofile')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hologram_procurements', to='workflow.workflow')),
            ],
            options={
                'db_table': 'hologram_procurement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HologramRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, unique=True)),
                ('license_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('usage_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('hologram_type', models.CharField(default='LOCAL', max_length=50)),
                ('issued_assets', models.JSONField(blank=True, default=list)),
                ('rolls_assigned', models.JSONField(blank=True, default=list, help_text='Assigned rolls for daily register - cartoon_number, from_serial, to_serial, quantity')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hologram_requests', to='workflow.workflowstage')),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hologram_requests', to='profile.supplychainuserprofile')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hologram_requests', to='workflow.workflow')),
            ],
            options={
                'db_table': 'hologram_request',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='HologramRollsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('carton_number', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('EXPORT', 'Export'), ('DEFENCE', 'Defence')], max_length=50, null=True)),
                ('from_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('to_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('damaged', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('COMPLETED', 'Completed'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=50)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('usage_history', models.JSONField(blank=True, default=list)),
                ('serial_ranges', models.JSONField(blank=True, default=list)),
                ('available_range', models.CharField(blank=True, help_text='Available serial range for this roll (e.g., "101-1000")', max_length=255, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('new_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_rolls', to=settings.AUTH_USER_MODEL)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls_details', to='hologram.hologramprocurement')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_hologram_rolls', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_rolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hologram_rolls_details',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyHologramRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('reference_no', models.CharField(max_length=100)),
                ('roll_range', models.TextField(blank=True, null=True)),
                ('cartoon_number', models.CharField(blank=True, max_length=100)),
                ('hologram_type', models.CharField(blank=True, max_length=50)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('usage_date', models.DateField()),
                ('brand_details', models.CharField(blank=True, max_length=255, null=True)),
                ('bottle_size', models.CharField(blank=True, max_length=100, null=True)),
                ('hologram_qty', models.IntegerField(default=0)),
                ('issued_from', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_qty', models.IntegerField(default=0)),
                ('issued_ranges', models.JSONField(blank=True, default=list)),
                ('wastage_from', models.CharField(blank=True, max_length=100, null=True)),
                ('wastage_to', models.CharField(blank=True, max_length=100, null=True)),
                ('wastage_qty', models.IntegerField(default=0)),
                ('wastage_ranges', models.JSONField(blank=True, default=list)),
                ('damage_reason', models.TextField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('stock_updated', models.BooleanField(default=False, help_text='Tracks if brand warehouse stock has been updated for this entry')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_daily_registers', to=settings.AUTH_USER_MODEL)),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_register_entries', to='profile.supplychainuserprofile')),
                ('hologram_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hologram.hologramrequest')),
                ('rolls_used', models.ManyToManyField(blank=True, related_name='daily_entries', to='hologram.hologramrollsdetails')),
            ],
            options={
                'db_table': 'daily_hologram_register',
                'ordering': ['-usage_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HologramSerialRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('from_serial', models.CharField(max_length=100)),
                ('to_serial', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('USED', 'Used'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=20)),
                ('used_date', models.DateField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('bottle_size', models.CharField(blank=True, max_length=100)),
                ('production_line', models.CharField(blank=True, max_length=100)),
                ('damage_date', models.DateField(blank=True, null=True)),
                ('damage_reason', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, max_length=255)),
                ('updated_by_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='hologram.hologramrollsdetails')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hologram_serial_ranges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hologram_serial_ranges',
                'ordering': ['from_serial'],
            },
        ),
        migrations.CreateModel(
            name='HologramUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('ISSUED', 'Issued for Production'), ('WASTAGE', 'Wastage/Damaged'), ('RETURNED', 'Returned to Stock')], max_length=20)),
                ('from_serial', models.CharField(max_length=100)),
                ('to_serial', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('bottle_size', models.CharField(blank=True, max_length=100)),
                ('damage_reason', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('license_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_hologram_usage', to=settings.AUTH_USER_MODEL)),
                ('daily_register_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_history', to='hologram.dailyhologramregister')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hologram.hologramrollsdetails')),
            ],
            options={
                'db_table': 'hologram_usage_history',
                'ordering': ['-date', '-approved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hologramprocurement',
            index=models.Index(fields=['licensee'], name='hologram_pr_license_f53671_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramprocurement',
            index=models.Index(fields=['current_stage'], name='hologram_pr_current_55b4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramrollsdetails',
            index=models.Index(fields=['carton_number'], name='hologram_ro_carton__287f59_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramrollsdetails',
            index=models.Index(fields=['type'], name='hologram_ro_type_9a37fe_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramrollsdetails',
            index=models.Index(fields=['status'], name='hologram_ro_status_fe6659_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramrollsdetails',
            index=models.Index(fields=['procurement'], name='hologram_ro_procure_669445_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyhologramregister',
            index=models.Index(fields=['licensee', 'approval_status'], name='daily_holog_license_1d8690_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyhologramregister',
            index=models.Index(fields=['license_id', 'approval_status'], name='daily_holog_license_6c7103_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyhologramregister',
            index=models.Index(fields=['cartoon_number', 'hologram_type'], name='daily_holog_cartoon_89d520_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyhologramregister',
            index=models.Index(fields=['usage_date'], name='daily_holog_usage_d_c68e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramserialrange',
            index=models.Index(fields=['roll', 'status'], name='hologram_se_roll_id_724744_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramserialrange',
            index=models.Index(fields=['license_id', 'status'], name='hologram_se_license_40ce41_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramserialrange',
            index=models.Index(fields=['from_serial', 'to_serial'], name='hologram_se_from_se_11b4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramusagehistory',
            index=models.Index(fields=['roll', 'usage_type'], name='hologram_us_roll_id_d1454e_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramusagehistory',
            index=models.Index(fields=['license_id', 'usage_type'], name='hologram_us_license_dc9e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='hologramusagehistory',
            index=models.Index(fields=['date'], name='hologram_us_date_2dd6da_idx'),
        ),
    ]
