# Generated by Codex on 2026-05-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hologram_supplier', '0002_seed_default_supplier'),
        ('hologram', '0004_migrate_licensee_to_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='hologramprocurement',
            name='supplier',
            field=models.ForeignKey(
                blank=True,
                help_text='Supplier used for the supply order letter (IT Cell selects after payment).',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='hologram_procurements',
                to='hologram_supplier.masterhologramsupplier',
            ),
        ),
    ]

