# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hologram', '0005_hologramprocurement_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hologramserialrange',
            name='status',
            field=models.CharField(
                choices=[
                    ('AVAILABLE', 'Available'),
                    ('IN_USE', 'In Use'),
                    ('USED', 'Used'),
                    ('DAMAGED', 'Damaged'),
                ],
                default='AVAILABLE',
                max_length=20,
            ),
        ),
    ]

