# Generated by Django 5.1.7 on 2025-09-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together=set(),
        ),
    ]
