# Generated by Django 5.1.7 on 2025-11-13 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('roles', '0001_initial'),
        ('workflow', '0003_workflowobjection_workflowtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkflowObjection',
            new_name='Objection',
        ),
        migrations.RenameModel(
            old_name='WorkflowTransaction',
            new_name='Transaction',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='workflow_tr_content_1e0081_idx',
            old_name='workflow_wo_content_64ee7f_idx',
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('workflow',), name='one_initial_stage_per_workflow'),
        ),
    ]
