# Generated by Django 5.1.7 on 2026-05-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_seed_workflow2_objection_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='after_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='before_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='objection',
            table='workflow_objection',
        ),
    ]
