# Generated by Django 5.2.8 on 2026-05-30

from django.db import migrations


def seed_license_renewal_workflow(apps, schema_editor):
    Workflow = apps.get_model("workflow", "Workflow")
    WorkflowStage = apps.get_model("workflow", "WorkflowStage")
    WorkflowTransition = apps.get_model("workflow", "WorkflowTransition")
    StagePermission = apps.get_model("workflow", "StagePermission")

    source = (
        Workflow.objects.filter(name="License Approval").order_by("id").first()
        or Workflow.objects.filter(id=1).first()
    )
    if not source:
        return

    target, _ = Workflow.objects.update_or_create(
        name="License Renewal Application",
        defaults={"description": "Workflow for application of a license renewal."},
    )

    # Create stages (idempotent per name).
    stage_map = {}
    for s in WorkflowStage.objects.filter(workflow_id=source.id).order_by("id"):
        ns, _ = WorkflowStage.objects.update_or_create(
            workflow_id=target.id,
            name=s.name,
            defaults={
                "description": getattr(s, "description", "") or "",
                "is_initial": bool(getattr(s, "is_initial", False)),
                "is_final": bool(getattr(s, "is_final", False)),
            },
        )
        stage_map[s.id] = ns

    # Copy transitions for this workflow only.
    for t in WorkflowTransition.objects.filter(workflow_id=source.id).order_by("id"):
        from_stage = stage_map.get(t.from_stage_id)
        to_stage = stage_map.get(t.to_stage_id)
        if not from_stage or not to_stage:
            continue

        # Prevent duplicates.
        if WorkflowTransition.objects.filter(
            workflow_id=target.id, from_stage_id=from_stage.id, to_stage_id=to_stage.id
        ).exists():
            continue

        WorkflowTransition.objects.create(
            workflow_id=target.id,
            from_stage_id=from_stage.id,
            to_stage_id=to_stage.id,
            condition=getattr(t, "condition", {}) or {},
        )

    # Copy stage permissions.
    for p in StagePermission.objects.filter(stage__workflow_id=source.id).order_by("id"):
        new_stage = stage_map.get(p.stage_id)
        if not new_stage:
            continue
        StagePermission.objects.update_or_create(
            stage_id=new_stage.id,
            role_id=p.role_id,
            defaults={"can_process": bool(getattr(p, "can_process", True))},
        )


def unseed_license_renewal_workflow(apps, schema_editor):
    Workflow = apps.get_model("workflow", "Workflow")
    WorkflowStage = apps.get_model("workflow", "WorkflowStage")
    WorkflowTransition = apps.get_model("workflow", "WorkflowTransition")
    StagePermission = apps.get_model("workflow", "StagePermission")

    wf = Workflow.objects.filter(name="License Renewal Application").first()
    if not wf:
        return

    StagePermission.objects.filter(stage__workflow_id=wf.id).delete()
    WorkflowTransition.objects.filter(workflow_id=wf.id).delete()
    WorkflowStage.objects.filter(workflow_id=wf.id).delete()
    wf.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_objection_after_content_objection_before_content_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_license_renewal_workflow, unseed_license_renewal_workflow),
    ]

