# Generated by Django 5.1.7 on 2026-07-05 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('roles', '0002_backfill_company_registration_create'),
        ('workflow', '0006_seed_license_renewal_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=36)),
                ('remarks', models.TextField()),
                ('reverted_on', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reverted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_reverts_performed', to=settings.AUTH_USER_MODEL)),
                ('reverted_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_reverts_received', to='roles.role')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstage')),
            ],
            options={
                'db_table': 'workflow_reverted',
                'ordering': ['-reverted_on'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='workflow_re_content_8873c8_idx')],
            },
        ),
    ]
