# Generated by Django 5.1.7 on 2026-07-09 13:22

from django.db import migrations


def seed_special_permit_workflow(apps, schema_editor):
    Workflow = apps.get_model("workflow", "Workflow")
    WorkflowStage = apps.get_model("workflow", "WorkflowStage")
    WorkflowTransition = apps.get_model("workflow", "WorkflowTransition")
    StagePermission = apps.get_model("workflow", "StagePermission")
    Role = apps.get_model("roles", "Role")

    # Roles resolution
    licensee_role = Role.objects.filter(name="Licensee").first()
    district_role = Role.objects.filter(name="District User").first()
    commissioner_role = Role.objects.filter(name="Commissioner").first()

    # Create Workflow
    wf, _ = Workflow.objects.update_or_create(
        name="Special Permit",
        defaults={"description": "Workflow for Special Permission for Dry Day permit applications."}
    )

    # Create Stages
    applied_stage, _ = WorkflowStage.objects.update_or_create(
        workflow=wf,
        name="Applied",
        defaults={"description": "Application submitted by licensee", "is_initial": True, "is_final": False}
    )
    
    district_stage, _ = WorkflowStage.objects.update_or_create(
        workflow=wf,
        name="District User",
        defaults={"description": "Review by District User", "is_initial": False, "is_final": False}
    )
    
    commissioner_stage, _ = WorkflowStage.objects.update_or_create(
        workflow=wf,
        name="Commissioner",
        defaults={"description": "Review and Approval by Commissioner", "is_initial": False, "is_final": False}
    )
    
    payment_stage, _ = WorkflowStage.objects.update_or_create(
        workflow=wf,
        name="Awaiting Payment",
        defaults={"description": "Approved, Awaiting payment from licensee", "is_initial": False, "is_final": False}
    )
    
    approved_stage, _ = WorkflowStage.objects.update_or_create(
        workflow=wf,
        name="Approved",
        defaults={"description": "Permit issued successfully", "is_initial": False, "is_final": True}
    )
    
    rejected_stage, _ = WorkflowStage.objects.update_or_create(
        workflow=wf,
        name="Rejected",
        defaults={"description": "Application rejected", "is_initial": False, "is_final": True}
    )

    # Create Stage Permissions
    if district_role:
        StagePermission.objects.update_or_create(
            stage=district_stage,
            role=district_role,
            defaults={"can_process": True}
        )
    if commissioner_role:
        StagePermission.objects.update_or_create(
            stage=commissioner_stage,
            role=commissioner_role,
            defaults={"can_process": True}
        )
    if licensee_role:
        StagePermission.objects.update_or_create(
            stage=payment_stage,
            role=licensee_role,
            defaults={"can_process": True}
        )

    # Create Transitions
    WorkflowTransition.objects.update_or_create(
        workflow=wf,
        from_stage=applied_stage,
        to_stage=district_stage,
        defaults={"condition": {}}
    )
    WorkflowTransition.objects.update_or_create(
        workflow=wf,
        from_stage=district_stage,
        to_stage=commissioner_stage,
        defaults={"condition": {"action": "APPROVE"}}
    )
    WorkflowTransition.objects.update_or_create(
        workflow=wf,
        from_stage=district_stage,
        to_stage=rejected_stage,
        defaults={"condition": {"action": "REJECT"}}
    )
    WorkflowTransition.objects.update_or_create(
        workflow=wf,
        from_stage=commissioner_stage,
        to_stage=payment_stage,
        defaults={"condition": {"action": "APPROVE"}}
    )
    WorkflowTransition.objects.update_or_create(
        workflow=wf,
        from_stage=commissioner_stage,
        to_stage=rejected_stage,
        defaults={"condition": {"action": "REJECT"}}
    )
    WorkflowTransition.objects.update_or_create(
        workflow=wf,
        from_stage=payment_stage,
        to_stage=approved_stage,
        defaults={"condition": {"action": "PAY"}}
    )


def unseed_special_permit_workflow(apps, schema_editor):
    Workflow = apps.get_model("workflow", "Workflow")
    WorkflowStage = apps.get_model("workflow", "WorkflowStage")
    WorkflowTransition = apps.get_model("workflow", "WorkflowTransition")
    StagePermission = apps.get_model("workflow", "StagePermission")

    wf = Workflow.objects.filter(name="Special Permit").first()
    if wf:
        StagePermission.objects.filter(stage__workflow_id=wf.id).delete()
        WorkflowTransition.objects.filter(workflow_id=wf.id).delete()
        WorkflowStage.objects.filter(workflow_id=wf.id).delete()
        wf.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_revert'),
    ]

    operations = [
        migrations.RunPython(seed_special_permit_workflow, unseed_special_permit_workflow),
    ]
